callstack/react-native-paper

- example/main.js
- example/src/ExampleList.js
- example/src/PaperExample.js
- index.js
- src/components/Paper.js
- src/styles/shadow.js
Since Google doesn't document the shadow values anywhere (it was documented earlier, but only upto 5dp), this is an approximation.
> feat: add a paper component. fixes #42

- src/core/withTheme.js
> fix: copy static properties in HOC

- example/src/TextExamples.js
- index.js
- src/components/Typography/Caption.js
- src/components/Typography/Headline.js
- src/components/Typography/Paragraph.js
- src/components/Typography/Subheading.js
- src/components/Typography/Text.js
- src/components/Typography/Title.js
- src/components/Typography/createStyledText.js
- src/core/withTheme.js
- src/styles/DefaultTheme.js
- src/types/Theme.js
> fix: follow line height and opacity guidelines for text

- example/src/ButtonsExample.js
- example/src/ExampleList.js
- example/src/RippleExample.js
- example/src/TextExample.js
- index.js
- src/components/Button.js
- src/components/Paper.js
- src/components/TouchableRipple/TouchableRipple.android.js
- src/components/TouchableRipple/TouchableRipple.js
- src/components/Typography/Text.js
- src/core/withTheme.js
> feat: add <Button /> component

- .eslintrc
- example/src/CardExample.js
- example/src/ExampleList.js
- example/src/PaperExample.js
- index.js
- src/components/Card.js
> feat: add <Card /> component

- example/src/ButtonExample.js
- src/components/Button.js
> feat: add color prop, don't add bg for non-raised button

- example/src/CheckboxExample.js
- example/src/ExampleList.js
- example/src/RadioButtonExample.js
- index.js
- src/components/Checkbox.js
- src/components/RadioButton.js
- src/components/TouchableRipple/TouchableRipple.android.js
- src/components/TouchableRipple/TouchableRipple.js
> Add radio and check buttons

- example/src/CheckboxExample.js
- example/src/ExampleList.js
- example/src/RadioButtonExample.js
- index.js
- src/components/Checkbox.js
- src/components/RadioButton.js
- src/components/TouchableRipple/TouchableRipple.android.js
- src/components/TouchableRipple/TouchableRipple.js
Reverts react-native-paper/react-native-paper#64
> Revert "Revert "Add radio and check buttons""

- example/src/ExampleList.js
- example/src/GridViewExample.js
- src/components/GridView.js
- src/index.js
> feat: add GridView component. fixes #44

- .flowconfig
- .travis.yml
- docs/.gitignore
- docs/deploy.sh
- docs/index.js
- docs/package.json
- docs/templates/ComponentDocs.js
- docs/templates/HTML.js
- docs/templates/Home.js
- docs/templates/Page.js
- docs/templates/styles/body.js
- docs/templates/styles/mono.js
- src/components/Button.js
The development workflow is not very good right now since you need to rebuild after every change. Will need to revisit the approach.
Need to setup travis to build docs and push to the repo.
https://react-native-paper.github.io/
> docs: generate static html pages

- docs/deploy.sh
- docs/index.js
- docs/package.json
- docs/templates/App.js
- docs/templates/Link.js
- docs/templates/Page.js
- docs/templates/Router.js
- Generate a single bundle
- Implement routing which works with/without JS
- Enable HMR for function components as well as documentation
> docs: improvements to docs generation

- src/index.js
`DefaultTheme` is useful as a starting point to override defaults when tweaking the theme.
> Exported DefaultTheme in src/index.js for users to access

- .eslintrc
- example/src/ExampleList.js
- example/src/SearchExample.js
- src/components/SearchBar.js
- src/index.js
- src/styles/DefaultTheme.js
- src/types/Theme.js
First version of the component:
- It does not include list with suggestions
- It does not include integration with Toolbar (we do not have this one yet)
- It should have cursor color and highlighted color using the `accent` color. Right now, it is not possible to change the cursor color so just changing the highlighted would look weird.
> SearchBar component

- example/src/ExampleList.js
- example/src/SearchBarExample.js
- src/components/SearchBar.js
> fix: fix searchbar styles

- .eslintrc
- example/src/ExampleList.js
- example/src/FABExample.js
- src/components/FAB.js
- src/index.js
> feat: add a FAB component

- example/src/SearchBarExample.js
- example/yarn.lock
- src/components/SearchBar.js
- src/components/TouchableIcon.js
- src/index.js
You can see two uses cases on the example, back button and drawer.
> SearchBar - Left icon can be used as a button

- example/src/ButtonExample.js
- src/components/Button.js
- src/components/DrawerItem.js
- src/components/FAB.js
- src/components/Icon.js
- src/components/SearchBar.js
- src/components/Toolbar/ToolbarAction.js
- src/components/TouchableIcon.js
In regards to #122 
Question: when passing a component as a prop `name` should we allow to custom styles of that component?
It could lead to large icons in small button...
> Enhance  Icon component

- example/src/CheckboxExample.js
Solves #134 
Added:
- New example in CheckboxExample which present checkbox as a part of a list item (clickable whole row)
> refactor: checkbox as a part of a list item

- example/src/CheckboxExample.js
- example/src/ExampleList.js
- example/src/RadioButtonExample.js
- example/src/SwitchExample.js
- src/components/Checkbox.ios.js
- src/components/Checkbox.js
- src/components/RadioButton.ios.js
- src/components/RadioButton.js
- src/components/Switch.js
- src/index.js
- src/styles/DefaultTheme.js
> feat: Controls adaptation to IOS

- example/src/RadioButtonExample.js
- example/src/RootNavigator.js
- example/src/ToolbarExample.js
> refactor: use own toolbar in examples

- src/components/FAB.js
- src/components/TouchableIcon.js
> fix: wrap icon in view

- src/core/withTheme.js
> fix: Be able to override nested theme component

- src/components/Toolbar/Toolbar.js
> refactor: disable shadow on ios toolbar

- example/src/RippleExample.js
> feat: add ripple example

- docs/package.json
- docs/yarn.lock
- src/components/Button.js
- src/components/Card/Card.js
- src/components/Checkbox.js
- src/components/Dialog/Dialog.js
- src/components/Divider.js
- src/components/DrawerItem.js
- src/components/DrawerSection.js
- src/components/FAB.js
- src/components/GridView.js
- src/components/Modal.js
- src/components/Paper.js
- src/components/ProgressBar.js
- src/components/RadioButton.js
- src/components/SearchBar.js
- src/components/Switch.js
- src/components/TextInput.js
- src/components/Toolbar/Toolbar.js
- src/components/TouchableRipple.js
- src/components/Typography/Caption.js
- src/components/Typography/Headline.js
- src/components/Typography/Paragraph.js
- src/components/Typography/Subheading.js
- src/components/Typography/Title.js
> docs: set js inside component for proper highlight

- example/DrawerItems.js
- src/components/Button.js
- src/components/Card/Card.js
- src/components/Checkbox.js
- src/components/GridView.js
- src/components/RadioButton.js
- src/components/TextInput.js
- src/core/withTheme.js
There seems to be some issue with defaultProps after this change, but it's better than not typechecking props at all
https://github.com/facebook/flow/issues/5382#issuecomment-351804070
> fix: fix flow typing with withTheme

- example/src/ProgressBarExample.js
- example/src/RadioButtonExample.js
- example/src/RippleExample.js
- example/src/RootNavigator.js
- example/src/SwitchExample.js
- example/src/ToolbarExample.js
- src/components/Button.js
- src/components/Checkbox.js
- src/components/Divider.js
- src/components/RadioButton.js
- src/components/SearchBar.js
- src/components/Switch.js
- src/styles/DarkTheme.js
- src/styles/DefaultTheme.js
> Various fixes

- CONTRIBUTING.md
- package.json
Add bootstrap script to run yarn in example and docs folder
> add bootstrap script to run yarn

- src/components/Divider.js
- src/components/TouchableRipple.js
> TouchableRipple using proper color on dark theme

- docs/pages/3.icons.md
- src/components/Button.js
- src/components/Card/Card.js
- src/components/Card/CardActions.js
- src/components/Card/CardContent.js
- src/components/Card/CardCover.js
- src/components/Checkbox.js
- src/components/Dialog/Dialog.js
- src/components/Dialog/DialogActions.js
- src/components/Dialog/DialogContent.js
- src/components/Dialog/DialogScrollArea.js
- src/components/Dialog/DialogTitle.js
- src/components/Divider.js
- src/components/DrawerItem.js
- src/components/DrawerSection.js
- src/components/FAB.js
- src/components/Modal.js
- src/components/Paper.js
- src/components/ProgressBar.js
- src/components/RadioButton.js
- src/components/SearchBar.js
- src/components/Switch.js
- src/components/TextInput.js
- src/components/Toolbar/Toolbar.js
- src/components/TouchableRipple.js
- src/components/Typography/Caption.js
- src/components/Typography/Headline.js
- src/components/Typography/Paragraph.js
- src/components/Typography/Subheading.js
- src/components/Typography/Title.js
Adds imports to docs for better DX.
I know that some of the docs are missing altogether. I thought maybe that could be done in a separate PR? I can add to this one if you'd like those finished up. Just let me know!
> docs: Add imports to doc examples - closes #223

- src/components/Checkbox.ios.js
- src/components/Checkbox.js
- src/components/FAB.js
- src/components/Icon.js
- src/components/RadioButton.ios.js
- src/components/SearchBar.js
- src/components/TouchableIcon.js
> fix: use color prop instead of style in Icon

- src/components/Dialog/DialogActions.js
- src/components/Dialog/DialogContent.js
- src/components/Dialog/DialogScrollArea.js
- src/components/Dialog/DialogTitle.js
- src/components/Modal.js
Fixes all the remaining `visble` typos for docs.
> docs: fix typos

- src/components/List/ListItem.js
- src/components/__tests__/__snapshots__/ListItem.test.js.snap
- src/components/__tests__/__snapshots__/ListSection.test.js.snap
> Show ripple in same position where user touched (ListItem).

- src/components/FABGroup.js
This PR makes it possible to pass style prop to FABGroup component and for example change it's position.
> Add style prop to FABGroup component.

- src/components/Snackbar.js
`StyleSheet`must be imported from `react-native`itself.
n/a
> docs: fix wrong import in example

- src/components/Snackbar.js
Minor english fix. `contain` should be used normally when followed by `should`, `following` also asks for an article.
> docs: minor english fix in snackbar actions doc

- src/components/Dialog/Dialog.js
Dialog borderRadius was explicitly set 2, i have updated it to get the roundness from theme prop.
> fix: dialog borderRadius

- src/components/Card/Card.js
- src/components/Portal/PortalHost.js
- src/components/__tests__/__snapshots__/Portal.test.js.snap
- src/components/__tests__/__snapshots__/Snackbar.test.js.snap
> Fix bug with non-portal components that appear above portal components.

- src/components/FAB/FAB.js
> fix: FAB elevation to match material design

- example/src/RootNavigator.js
> fix: broken menu button of example app

- src/components/TextInput.js
#499 This can be done in a single line.
> fix: TextInput RTL support

- src/components/Dialog/DialogActions.js
Minor typo in example usage
Suppose there's no need to test it very deeply 😄
> Typo in example of DialogActions.js

- src/components/RadioButton.js
Update documentation with new version `2.0.1` of `react-native-paper`. RadioButton props are quite different from version 1 to 2, so docs needed an update.
See docs.
> docs: Update RadioButton docs with new version 2.0.1

- src/components/BottomNavigation.js
- src/components/Button.js
- src/components/Card/Card.js
- src/components/Chip.js
- src/components/Dialog/Dialog.js
- src/components/FAB/FAB.js
- src/components/Surface.js
- src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
- src/components/__tests__/__snapshots__/Button.test.js.snap
- src/components/__tests__/__snapshots__/Chip.test.js.snap
- src/components/__tests__/__snapshots__/FAB.test.js.snap
- src/components/__tests__/__snapshots__/Snackbar.test.js.snap
As @satya164  mentioned [here](https://github.com/callstack/react-native-paper/pull/485#discussion_r219710052)
> fix: Surface View to Animated.View

- src/components/__tests__/__snapshots__/Banner.test.js.snap
Fix for failing master branch.
> fix: Update test snapshots

- src/components/FAB/FAB.js
People open issues asking how to style fab properly. This PR adds style object to fab docs so it should be clear from now how to do it.
> docs: improve docs for fab component by adding styles.

- docs/pages/4.icons.md
- src/components/Icon.js
The render prop didn't support RTL, so I added `direction` to the render prop arguments so that you have access to it. I also added the neccessary docs needed for using the RTL features within icons.
> docs: RTL usage for icons

- src/components/Typography/Caption.js
- src/components/__tests__/Typography/Caption.test.js
- src/components/__tests__/Typography/__snapshots__/Caption.test.js.snap
This PR aims to fix #563 
Use the example App and check if `font-size` of Captions are 12
I also added Snapshot tests for this Component
> Fix caption font size

- typings/types.d.ts
> fix: Fix withTheme typescript type

- typings/components/TextInput.d.ts
- typings/components/Typography.d.ts
> fix: Fix component types

- docs/pages/src/Showcase.js
While i was trying to update React and Flow versions, i found a small issue in docs.  We were trying to access `android` and `ios` properties on wrong object.
> fix: fix small issue in docs (Showcase section).

- package.json
- yarn.lock
Fix Typescript type for `withTheme`.
```typescript
const Wrapped = withTheme(Component);
render = () => <Wrapped theme={somePartialTheme} />
```
> fix: Fix Typescript withTheme return type

- package.json
- yarn.lock
Upgrade react-theme-provider for new types.
> fix: upgrade react-theme-provider

- example/src/TextInputExample.js
Added KeyBoardAvoidingView because it is hard to check the last TextInput in the example
Check the TextInput view in the [snack example](https://snack.expo.io/@satya164/github.com-callstack-react-native-paper:example)
Screenshot - Todo
> fix: add keyboardavoidingview

- example/src/TextInputExample.js
It should accept both uppercase and lowercase letters.
> fix: TextInput example using HelperText

- example/src/SearchbarExample.js
- src/components/Searchbar.js
> fix: searchbar RTL support

- typings/components/TouchableRipple.d.ts
Fix TouchableRipple props types
> Fix TouchableRipple props types

- typings/components/Drawer.d.ts
> updating typescript definition for Drawer.Item

- src/components/Chip.js
- typings/components/Chip.d.ts
Make Detox (https://github.com/wix/Detox) testing available for Chips by passing down testID to Touchable.
Now you can test it with Detox.
> Pass down testID from Chip props to Touchable for Detox tests.

- src/components/Button.js
Ability to change case of text in button. The button with mode text look a bit ugly when the text is long. This PR will give more control to the developer.
Pass `upperCase={false}` as props to the button element
> feat: ability to change button text case

- src/components/IconButton.js
- src/components/__tests__/__snapshots__/IconButton.test.js.snap
Whenever the icon of `IconButton` changes, the change looks quite hard. This change will introduce the same effect as in `FAB`s.
n/a
> feat: smooth icon change in `IconButton`

- docs/assets/styles.css
- docs/index.js
- docs/package.json
- docs/pages/0.index.js
- docs/pages/1.showcase.js
- docs/pages/4.icons.mdx
- docs/pages/src/components/IconsList.js
- docs/yarn.lock
Issue no #687  - That PR will add a SearchBar component in documents on Icons page to allow user search for specific icon.
> docs: add SearchBar to find an icon name on Icons page

- example/src/BottomNavigationExample.js
Close https://github.com/callstack/react-native-paper/issues/741
Just a typo
> fix: typo in bottom navigation example

- src/components/BottomNavigation.js
- src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
- typings/components/BottomNavigation.d.ts
> feat: hide bottom navigation when keyboard is shown. closes #676

- src/components/Chip.js
- src/components/Dialog/Dialog.js
- src/components/FAB/FABGroup.js
- src/components/Modal.js
- src/components/Snackbar.js
- src/components/__tests__/__snapshots__/Chip.test.js.snap
- src/components/__tests__/__snapshots__/Snackbar.test.js.snap
On Android P, if a view with elevation is inside another view which animates the opacity, the elevation doesn't animate when the opacity changes.
This PR refactors components to animate opacity on the same views those have elevation to workaround this behaviour.
> fix: fix elevation not animating in some components

- example/App.web.js
- example/assets/styles/fonts.css
- example/package.json
- example/public/index.html
- example/webpack.config.js
- example/yarn.lock
- src/styles/fonts.js
`Roboto Medium` was not properly displayed in the example app since only `Roboto` font was loaded. This PR loads all necessary fonts locally (which also helps when you work in places without internet) and also adds fallback fonts.
Open examples app on web.
> fix: improve fonts on web

- src/components/Appbar/AppbarAction.js
- src/components/IconButton.js
- src/components/__tests__/IconButton.test.js
- src/components/__tests__/__snapshots__/DataTable.test.js.snap
- src/components/__tests__/__snapshots__/IconButton.test.js.snap
- src/components/__tests__/__snapshots__/ToggleButton.test.js.snap
- typings/components/IconButton.d.ts
This PR introduces a new property `animated` on `IconButton` which determines whether an icon change is animated or not. For example, for `ToggleButton` we do not want to have an animation but for `Appbar.Action` we want it (i.e. for contextual appbar). This will fix https://github.com/callstack/react-native-paper/issues/764.
See examples app.
> fix: animated icon change

- src/components/IconButton.js
- src/components/TouchableRipple.js
- src/components/__tests__/__snapshots__/Banner.test.js.snap
- src/components/__tests__/__snapshots__/Button.test.js.snap
- src/components/__tests__/__snapshots__/Checkbox.test.js.snap
- src/components/__tests__/__snapshots__/Chip.test.js.snap
- src/components/__tests__/__snapshots__/DataTable.test.js.snap
- src/components/__tests__/__snapshots__/DrawerItem.test.js.snap
- src/components/__tests__/__snapshots__/FAB.test.js.snap
- src/components/__tests__/__snapshots__/IconButton.test.js.snap
- src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
- src/components/__tests__/__snapshots__/ListItem.test.js.snap
- src/components/__tests__/__snapshots__/ListSection.test.js.snap
- src/components/__tests__/__snapshots__/Searchbar.test.js.snap
- src/components/__tests__/__snapshots__/Snackbar.test.js.snap
- src/components/__tests__/__snapshots__/ToggleButton.test.js.snap
This https://github.com/facebook/react-native/issues/6480#issuecomment-454183413 works.
> fix: Android P ripple effect using overflow hidden and useForeground

- src/components/DataTable/DataTableRow.js
Fix https://github.com/callstack/react-native-paper/issues/813
See examples app.
> fix: collapsed content in DataTable

- typings/components/TextInput.d.ts
update the types
so it have compatibility with React-Native's TextInput Typing since react-native-paper is extending it
its related to my questions in here #823
> update TextInput Typing

- src/components/FAB/FAB.js
- src/components/__tests__/__snapshots__/FAB.test.js.snap
Fix for #851 
[Snack](https://snack.expo.io/@trensik/bad-salsa) that reproduces issue.
> fix: makes FAB not pressable when initially not visible

- src/components/Modal.js
- src/components/Snackbar.js
This is fix for issue mentioned in #855 .
> fix: fix visibility prop in Snackbar and Modal

- src/components/TouchableRipple/index.js
> fix: add onLongPress to TouchableRipple

- docs/pages/4.react-native-web.md
Added doc to use react-native-paper on existing CRA project.
Facilitate the integration of the project with the CRA
Not applicable.
> Documentation to use react-native-paper with CRA

- README.md
Giving more recognition to Callstack
Check README
> docs: add callstack-badge and note to readme

- src/components/Dialog/Dialog.js
- src/components/Modal.js
- typings/components/Dialog.d.ts
- typings/components/Modal.d.ts
There are use cases when you don't need `onDimiss`.
n/a
> fix: make onDismiss optional

- src/components/Button.js
Adds info about customizing height and width of button via contentStyle prop to prop description.
> docs: improve contentStyle prop description in Button

- src/components/Snackbar.js
> Don't add a setTimeout if Infinity is passed as duration

- src/components/List/ListItem.js
- src/components/__tests__/ListItem.test.js
- src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
- src/components/__tests__/__snapshots__/ListItem.test.js.snap
- src/components/__tests__/__snapshots__/ListSection.test.js.snap
- typings/components/List.d.ts
There was no input in #872 for some time, so I decided to create another PR with improved solution.
> feat: add titleStyle and descriptionStyle props to List.Item

- src/components/Modal.js
> fix: modal example

- src/components/Modal.js
- src/components/__tests__/ActivityIndicator.test.js
- typings/components/Modal.d.ts
The animation performance for showing and hiding modals can be improved using the native driver.
https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated
Supply an optional `useNativeDriver` prop to the Modal component.
Suppress a warning in `ActivityIndicator.test.js`.
> Use native driver in Modal

- src/components/TextInput/TextInput.js
> fix: fix issue with TextInput animation on iOS

- src/components/Menu/Menu.js
- src/components/__tests__/Menu.test.js
- src/components/__tests__/__snapshots__/Menu.test.js.snap
Menu was broken on iOS, implementation was really complex and animations didn't use native driver.
> fix: rewrite of menu component

- docs/component-docs.config.js
> docs: fix edit pencil button

- docs/component-docs.config.js
- src/components/List/ListIcon.js
- src/components/List/ListItem.js
- src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
- src/components/__tests__/__snapshots__/ListItem.test.js.snap
- src/components/__tests__/__snapshots__/ListSection.test.js.snap
fixes #914
change margin value in ListIcon and ListItem component
add condition to adjust margin when description prop is passed
Solves the issue with different ListItem height according to Material Design guidelines
Update snapshots during run tests
> fix: list item height and margins

- src/components/Searchbar.js
- typings/components/Searchbar.d.ts
Closes https://github.com/callstack/react-native-paper/issues/707
```
<Searchbar
placeholder="Search"
value="Test"
clearIcon="custom-icon-name"
/>
```
> feat: custom icon for clear in seachbar

- src/components/Menu/Menu.js
> fix: typo in menu component

- src/components/Menu/Menu.js
Pressing back button should only hide the menu instead hiding and navigating back.
> fix: menu handle dismiss

- src/components/FAB/FABGroup.js
> Remove StatusBar from FAB Group

- src/components/FAB/FABGroup.js
- typings/components/FAB.d.ts
> Change actions icon type

- example/src/Examples/TextInputExample.js
- src/components/TextInput/TextInput.js
- src/components/TextInput/TextInputFlat.js
- src/components/TextInput/TextInputOutlined.js
- src/components/TextInput/helpers.js
- src/components/TextInput/types.js
- typings/components/TextInput.d.ts
Take fontSize from style object passed to TextInput to modify font size
fix #348 
fix #774 
fix #870
fix #877
> feat: change input font size

- src/components/Card/CardTitle.js
- src/components/CrossFadeIcon.js
> Add scale property to control cross fade icon animation time

- src/components/TextInput/InputLabel.js
- src/components/TextInput/TextInputFlat.js
- src/components/TextInput/TextInputOutlined.js
- src/components/TextInput/constants.js
- src/components/TextInput/types.js
Refactor TextInputFlat and TextInputOutlined by:
1. Extract code to InputLabel as separate component
2. Extract Underline and Outline component from return() inside input file
The purpose is to increase maintainability, make code cleaner and simplify adding new feature in future
> refactor: extract inputs label and clean code 

- src/components/FAB/FABGroup.js
- src/components/Modal.js
Fix erros on modal and fab groups examples. #1105 
Check the docs, and run the snack examples.
> Fix example erros in docs

- src/components/Menu/Menu.tsx
This fix disables interaction with menu while it is hiding.
Similar to #1116 
N/A
> fix: disable menu interaction while hiding

- src/components/__tests__/ListItem.test.js
- src/components/__tests__/__snapshots__/ListItem.test.js.snap
This test(#996) is missing in master.
> test: add missing test to ListItem.test.js

- example/src/Examples/ToggleButtonExample.tsx
- src/components/ToggleButton/ToggleButton.tsx
- src/components/ToggleButton/ToggleButtonGroup.tsx
- src/components/ToggleButton/ToggleButtonRow.tsx
> feat: add ToggleButton.Row component

- src/components/List/ListItem.tsx
- src/components/__tests__/ListItem.test.js
- src/components/__tests__/__snapshots__/ListItem.test.js.snap
> fix(list.item): properly render prop description

- src/components/Chip.tsx
- src/components/__tests__/__snapshots__/Chip.test.js.snap
- src/components/__tests__/__snapshots__/ListItem.test.js.snap
Fixes: #1153 
Specify the `font` from the `theme`
Tested on a device.
> refactor: specify the font from theme in chip

- src/components/Modal.tsx
Fixes: #1159 
default | horizontal left | horizontal right |
--- | --- | ---
> fix: wrap modal children in SafeAreaView

- docs/pages/1.getting-started.md
Fixes the Default Theme link in the docs to direct user to the correct github page.  Currently it is a 404 because of the change to typescript files
Simple fix, click link to verify it takes user to the correct place.
> fix: update href for typescript extension

- docs/pages/src/Showcase.js
- example/package.json
- example/yarn.lock
- package.json
- src/components/Appbar/Appbar.tsx
- src/components/Avatar/AvatarIcon.tsx
- src/components/Avatar/AvatarText.tsx
- src/components/Badge.tsx
- src/components/BottomNavigation.tsx
- src/components/Button.tsx
- src/components/FAB/FAB.tsx
- yarn.lock
Keep dependencies updated.
n/a
> fix: upgrade color to 3.0

- src/components/Appbar/Appbar.tsx
- src/components/__tests__/Appbar/Appbar.test.js
- src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
This commit(#1001) is missing from master and I couldn't find a branch to cherry-pick, so I'm opening this PR again.
Resolve #1215
> fix(appbar): make allowed children to accept additional props

- docs/package.json
- docs/yarn.lock
color library in docs wasn't updated
> docs: fix color version

- src/components/HelperText.tsx
Declare testID for helper text
This PR fixes #1201
> fix: add testID to HelperText

- docs/component-docs.config.js
- src/components/Typography/Caption.tsx
- src/components/Typography/Headline.tsx
- src/components/Typography/Paragraph.tsx
- src/components/Typography/Subheading.tsx
- src/components/Typography/Text.tsx
- src/components/Typography/Title.tsx
This PR fixes #757, the [full motivation and other approaches are listed here](https://github.com/callstack/react-native-paper/issues/757#issuecomment-511245429).
It's a docs change only, all other tests are passing. But just to be complete 😄
> Add component group annotation for Typography

- docs/pages/4.fonts.md
File extension from `.js` to `.tsx`
Fixes broken link in docs
resolves broken link in https://callstack.github.io/react-native-paper/fonts.html
> [docs] Update fonts link

- example/src/Examples/ChipExample.tsx
- src/components/Chip.tsx
Fixes: #1205 	
Extending the `Chip` component with `onLongPress` functionality.
> feat: extend chip with onLongPress functionality

- src/components/Avatar/AvatarText.tsx
- src/components/__tests__/__snapshots__/Avatar.test.js.snap
This pr fixes #1136 
Added prop for avatar text to add custom text style.
> fix: add style prop to AvatarText

- docs/pages/4.fonts.md
The way assets are linked in RN 0.60 and above has changed
Read the docs?
> Update font docs for RN 0.60

- src/components/Card/CardTitle.js
- typings/components/Card.d.ts
> Add number of lines to subtitle 

- src/components/Menu/Menu.tsx
> fix: wrap overflowing menu in scrollView

- .all-contributorsrc
They did a lot of great contributions recently .
Check the readme.
> docs: add jay and pan-pawel as contributors

- src/components/Snackbar.tsx
> Fixed example

- src/components/Button.tsx
Fixes #1342 
Add borderRadius to style of button
> fix: pass borderRadius to touchableStyle of button

- src/components/RadioButton.tsx
> Fix RadioButton onPress

- example/src/Examples/BottomNavigationExample.tsx
- src/components/BottomNavigation.tsx
- src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
> fix: use custom color first

- package.json
- scripts/generate-mappings.js
- src/babel/__fixtures__/rewrite-imports/output.js
> fix: add commonjs step to bob and configure main and module fields properly

- src/index.tsx
This will allow component builders to mimic the adaptive dark mode behavior by applying the same overlaying algorithm.
> Export overlay function

- package.json
- scripts/generate-mappings.js
- src/babel/__fixtures__/rewrite-imports/code.js
- src/babel/__fixtures__/rewrite-imports/output.js
- src/babel/index.js
> fix: make sure only one version of the library is imported

- docs/pages/6.recommended-libraries.md
Add the recommendation for a datetime component to docs as seen in #1476.
Not needed, just docs.
> docs: add react-native-datetimeepicker to recommended libraries

- .github/workflows/publish.yml
> chore: add expo publish action

- src/components/CheckboxAndroid.tsx
- src/components/CheckboxIOS.tsx
- src/components/DataTable/DataTableTitle.tsx
- src/components/List/ListAccordion.tsx
- src/components/MaterialCommunityIcon.tsx
- src/components/RadioButton/RadioButtonIOS.tsx
> fix: use material community icon for hard coded names

- src/components/Menu/MenuItem.tsx
Add `testID` prop to `Menu.Item` component so it can be used in testing tools like Detox.
> feat: Add testID prop to MenuItem

- src/components/List/ListAccordion.tsx
Add testID prop to `List.Accordion` component so it can be used in testing tools like Detox.
> feat: Add testID prop to ListAccordion

- src/components/Portal/Portal.tsx
- src/core/Provider.tsx
fix #1688
fix #1665
I tested it with `patch-package` in my project, `patches/react-native-paper+3.6.0.patch`:
```patch
diff --git a/node_modules/react-native-paper/lib/module/core/Provider.js b/node_modules/react-native-paper/lib/module/core/Provider.js
index 7540773..97e7b7b 100644
--- a/node_modules/react-native-paper/lib/module/core/Provider.js
+++ b/node_modules/react-native-paper/lib/module/core/Provider.js
@@ -1,2 +1,2 @@
-import _classCallCheck from"@babel/runtime/helpers/classCallCheck";import _createClass from"@babel/runtime/helpers/createClass";import _possibleConstructorReturn from"@babel/runtime/helpers/possibleConstructorReturn";import _getPrototypeOf from"@babel/runtime/helpers/getPrototypeOf";import _inherits from"@babel/runtime/helpers/inherits";var …
```
> fix: custom icons doesn't work in portal component

- src/components/Menu/Menu.tsx
having one calls makes this a little more clear
not necessary in this case I hope
> remove extra setState from Menu

- CONTRIBUTING.md
- src/components/Card/Card.tsx
- src/components/FAB/FABGroup.tsx
- src/components/HelperText.tsx
- src/components/Searchbar.tsx
- src/components/Snackbar.tsx
- src/components/Switch.tsx
- src/components/ToggleButton/ToggleButton.tsx
Improve some exemple codes in the docs, also fix the link to the Code Of Conduct
[Code of Conduct link](https://15675-71323749-gh.circle-artifacts.com/0/docs/contributing.html)
[Card Exemple](https://15675-71323749-gh.circle-artifacts.com/0/docs/card.html)
[FAB Group exemple](https://15675-71323749-gh.circle-artifacts.com/0/docs/fab-group.html)
[HelperText exemple](https://15675-71323749-gh.circle-artifacts.com/0/docs/helper-text.html)
[SnackBar exemple](https://15675-71323749-gh.circle-artifacts.com/0/docs/snackbar.html)
[SearchBar exemple](https://15675-71323749-gh.circle-artifacts.com/0/docs/searchbar.html)
[Switch exemple](https://15675-71323749-gh.circle-artifacts.com/0/docs/switch.html)
[ToggleButton exemple](https://15675-71323749-gh.circle-artifacts.com/0/docs/toggle-button.html)
> docs: improve example code, fix code of conduct link

- package.json
- src/components/Chip.tsx
- src/components/__tests__/__snapshots__/Chip.test.js.snap
- src/components/__tests__/__snapshots__/ListItem.test.js.snap
- yarn.lock
We need to revert accessibility-related changes, cause these are breaking changes. They will be included in version 4.0.
> revert: revert accessibility related changes

- .github/workflows/create-pr-after-merge-to-master.yml
This will allow us to keep master and 4.0 branches in sync.
> chore: gh action for automatic PR creation

- src/components/FAB/FABGroup.tsx
Icon names have changed, updated the example to match
> Update FABGroup.tsx (new icon names)

- src/components/Button.tsx
https://github.com/callstack/react-native-paper/issues/1678
Nothing visual has changed
> Fix: button animation

- src/components/Checkbox/CheckboxAndroid.tsx
- src/components/Checkbox/CheckboxIOS.tsx
The checkbox icon is flipped in RTL apps. 
Closes #1675
> fix: flipped checkbox icon in RTL

- package.json
- yarn.lock
> chore: upgrade react-native-safe-area-view

- src/components/RadioButton/RadioButtonItem.tsx
#1891 
It was quite a simple task so I made a PR immediately.
> feat: add color and uncheckedColor prop to RadioButton.Item

- .circleci/config.yml
- example/babel.config.js
- example/metro.config.js
- example/package.json
- example/webpack.config.js
- example/yarn.lock
- package.json
- Simplify metro config and webpack configs for linking the project
- Update circleci config to 2.1
> chore: update project configurations

- .circleci/config.yml
- docs/package.json
- docs/yarn.lock
> TEST: bump component docs

- .github/workflows/versions.yml
The action will now comment even if the packages aren't mentioned in the issue at all.
> chore: improve check versions action

- src/components/Appbar/Appbar.tsx
Fix 4th `Appbar.Action` component icon prop invalid value of 'icon="delete"]=' to 'icon="delete"'
> fix: Appbar.tsx

- example/app.json
- example/src/index.tsx
I have add expo configuration that allows to use automatic change theme
Also I have fixed broken DarkTheme switch
> fix: allow auto change theme

- src/core/Provider.tsx
- src/core/__tests__/Provider.test.js
> fix: handle appearance module being null

- docs/pages/2.theming.md
- Updated: Latest available React Native doc instead of referencing old version.
- Fixed: TypeScript Code highlight.
> docs: updated latest reference URL & improved TS code highlight

- src/components/FAB/FAB.tsx
A few people have requested this and I could use it as well, I believe this should add long press support to the FAB component.
> feat: add support for long press to FAB

- src/components/Checkbox/CheckboxAndroid.tsx
- src/components/Checkbox/CheckboxIOS.tsx
- src/components/RadioButton/RadioButtonAndroid.tsx
- src/components/RadioButton/RadioButtonIOS.tsx
Added short phrase to highlight that the 4 "platformed-named components" can be used on all platforms.
(doc review)
> (docs) Clarify platform choices

- src/core/__tests__/Provider.test.js
Provider.test.js was throwing some warnings when running it.
```
console.error
The above error occurred in the <Context.Provider> component:
in Portal.Host (created by Provider)
in Provider
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```
> test: fix warnings in Provider.test.js

- src/components/Chip.tsx
> feat: use MaterialCommunityIcon for hard coded icons in Chip component

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- docs/pages/src/Home.js
- example/README.md
> fix: update link to the snack example app

- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/CheckboxAndroid.tsx
- src/components/Checkbox/CheckboxIOS.tsx
- src/components/Checkbox/CheckboxItem.tsx
Class components for Checkbox are rewritten to functional ones.
> refactor: update Checkbox from class components to functional

- src/components/Drawer/DrawerItem.tsx
- src/components/Drawer/DrawerSection.tsx
Class components for Drawer are rewritten to functional ones.
> refactor: update drawer class components to functional

- src/components/Dialog/Dialog.tsx
- src/components/Dialog/DialogActions.tsx
- src/components/Dialog/DialogContent.tsx
- src/components/Dialog/DialogScrollArea.tsx
- src/components/Dialog/DialogTitle.tsx
Class components for Dialog are rewritten to functional ones.
> refactor: update dialog class components to functional

- src/components/Surface.tsx
Surface class component is rewritten to a functional one.
> refactor: update surface class component to functional

- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/CheckboxAndroid.tsx
- src/components/Checkbox/CheckboxIOS.tsx
- src/components/Checkbox/CheckboxItem.tsx
- src/components/__tests__/Checkbox/Checkbox.test.js
- src/components/__tests__/Checkbox/__snapshots__/Checkbox.test.js.snap
> testID property for Checkbox

- src/components/Checkbox/CheckboxAndroid.tsx
> fix: useref instead of state for animated value in checkbox

- src/components/RadioButton/RadioButton.tsx
- src/components/RadioButton/RadioButtonAndroid.tsx
- src/components/RadioButton/RadioButtonGroup.tsx
- src/components/RadioButton/RadioButtonIOS.tsx
- src/components/RadioButton/RadioButtonItem.tsx
Radio button class components are rewritten to functional ones.
> refactor: update radio button class components to functional

- src/components/HelperText.tsx
HelperText class component is rewritten to a functional one
> refactor: update helper text from class component to functional

- src/components/ActivityIndicator.tsx
- src/components/__tests__/ActivityIndicator.test.js
ActivityIndicator class component is rewritten to a functional one.
> refactor: update activity indicator class component to functional

- src/components/Banner.tsx
Banner class component is rewritten to a functional one.
> refactor: update banner class component to functional

- src/components/Badge.tsx
- src/components/__tests__/Badge.test.js
Badge class component is rewritten to a functional one.
> refactor: update badge class component to functional

- src/components/ToggleButton/ToggleButton.tsx
- src/components/ToggleButton/ToggleButtonGroup.tsx
- src/components/ToggleButton/ToggleButtonRow.tsx
Toggle button class components are rewritten to functional ones.
> refactor: update toggle button class components to functional

- src/components/Snackbar.tsx
- src/components/__tests__/__snapshots__/Snackbar.test.js.snap
A class component for Snackbar is rewritten to a functional one with hooks.
Visually the component looks and works the same as before, but 2 snapshots were updated.
> refactor: update snackbar class component to functional with hooks

- src/components/Card/Card.tsx
- src/components/Card/CardActions.tsx
- src/components/Card/CardContent.tsx
- src/components/Card/CardCover.tsx
- src/components/Card/CardTitle.tsx
A class component for Card is rewritten to a functional one with hooks.
> refactor:  update card class components to functional with hooks

- src/components/Divider.tsx
Divider class component is rewritten as a functional one.
> refactor: update divider class component to functional

- src/components/Button.tsx
- src/components/__tests__/Button.test.js
Button class component is rewritten to a functional one.
> refactor: update button class component to functional

- src/components/Chip.tsx
Chip class component is rewritten to a functional one.
> refactor: update chip class component to functional

- src/components/TouchableRipple/TouchableRipple.native.tsx
- src/components/TouchableRipple/TouchableRipple.tsx
Touchable Ripple class components are rewritten to functional ones.
> refactor: update touchable ripple class components to functional

- src/components/Banner.tsx
- src/components/Checkbox/CheckboxAndroid.tsx
- src/components/HelperText.tsx
- src/components/RadioButton/RadioButtonAndroid.tsx
Fixed eslint hooks warnings about missing dependencies in the functional components which were merged before I fixed them.
> fix: eslint hooks warnings

- src/components/BottomNavigation.tsx
There were some typos on the bottom navigation page. This PR fixes them.
(docs review)
> [docs] Fix typos in bottom navigation

- src/components/Checkbox/CheckboxItem.tsx
> fix: add theme prop to ChecknoxItem

- src/components/List/ListItem.tsx
Prior to this change, it is not obvious what valid values are.
(docs review)
> [docs] add link to RN's Text.ellipsizeMode

- src/components/BottomNavigation.tsx
Previously, we kept an array with indices of the routes we've visited previously. However, if routes were re-ordered/removed, the indices may not represent the actual routes that were visited previously since the routes might have a different index after re-ordering.
Using route keys instead of indices makes sure that we only render screens that were visited previously even when routes are re-ordered.
Run the example app and ensure that lazy lading works correctly.
> fix: use route keys for lazy loading tabs instead of index

- src/components/Switch.tsx
Switch class component is rewritten to functional one.
> refactor: update Switch class component to functional

- src/components/ActivityIndicator.tsx
- src/components/Menu/MenuItem.tsx
- src/components/ProgressBar.tsx
- src/components/RadioButton/RadioButtonAndroid.tsx
- src/components/RadioButton/RadioButtonGroup.tsx
- src/components/RadioButton/RadioButtonIOS.tsx
- src/components/ToggleButton/ToggleButton.tsx
- src/components/__tests__/RadioButton/__snapshots__/RadioButton.test.js.snap
- src/components/__tests__/RadioButton/__snapshots__/RadioButtonGroup.test.js.snap
- src/components/__tests__/__snapshots__/ActivityIndicator.test.js.snap
- src/components/__tests__/__snapshots__/Button.test.js.snap
- src/components/__tests__/__snapshots__/ProgressBar.test.js.snap
- src/components/__tests__/__snapshots__/ToggleButton.test.js.snap
Update the following components with a more specific [accessibilityRole](https://reactnative.dev/docs/accessibility#accessibilityrole)
1. Download this branch and open the example app in your phone
2. Test with both TalkBack(Android) and VoiceOver(iOS)
> feat: improve accessibility updating accessibilityRole and accessibilityState

- src/components/__tests__/RadioButton/__snapshots__/RadioButton.test.js.snap
> test: update missing snapshot from #2263

- src/components/List/ListAccordion.tsx
- src/components/List/ListAccordionGroup.tsx
Changed some variables names and functions according to CR tips https://github.com/callstack/react-native-paper/pull/2188
> refactor: corrected code after CR

- src/components/Modal.tsx
Corrected code according to CR tips to https://github.com/callstack/react-native-paper/pull/2220
> fix: modal cr fixes

- src/components/CrossFadeIcon.tsx
- src/components/__tests__/Appbar/Appbar.test.js
- src/components/__tests__/FAB.test.js
- src/components/__tests__/IconButton.test.js
> fix: cross fade icons cr fixes

- src/components/__tests__/FAB.test.js
- src/components/__tests__/__snapshots__/FAB.test.js.snap
This PR adds testes to fab component
> test: added test to FAB component

- src/components/List/ListAccordion.tsx
- src/components/List/ListAccordionGroup.tsx
- src/components/List/ListIcon.tsx
- src/components/List/ListItem.tsx
- src/components/List/ListSection.tsx
- src/components/List/ListSubheader.tsx
Class components for List are rewritten to functional ones.
> refactor: update List class components to functional

- src/components/DataTable/DataTable.tsx
- src/components/DataTable/DataTableCell.tsx
- src/components/DataTable/DataTableHeader.tsx
- src/components/DataTable/DataTablePagination.tsx
- src/components/DataTable/DataTableRow.tsx
- src/components/DataTable/DataTableTitle.tsx
Class components for DataTable are rewritten to functional ones.
> refactor: update dataTable class components to functional with hooks

- src/components/Avatar/AvatarIcon.tsx
- src/components/Avatar/AvatarImage.tsx
- src/components/Avatar/AvatarText.tsx
Class components for Avatar is rewritten to functional ones.
> refactor: update avatar class components to functional

- src/components/Appbar/Appbar.tsx
- src/components/Appbar/AppbarAction.tsx
- src/components/Appbar/AppbarBackAction.tsx
- src/components/Appbar/AppbarContent.tsx
- src/components/Appbar/AppbarHeader.tsx
A class component for AppBar is rewritten to a functional one.
> refactor: update appBar class components to functional

- src/components/CrossFadeIcon.tsx
This PR fixes issue with broken animation in `CrossFadeIcon` component, probably introduced in a rewrite to hooks.
I've also cleaned up the code a bit by removing `previousPreviousIconRef` variable which didn't really make any sense to me.
Component seems to work fine without it. 
FAB example in the example app.
> fix: fix issue with broken animation in CrossFadeIcon

- src/components/Typography/StyledText.tsx
- src/components/Typography/Text.tsx
- src/components/__tests__/Typography/__snapshots__/Caption.test.js.snap
Typography class components are rewritten as functional ones
> refactor: update typography class components to functional

- src/components/Button.tsx
Add onLongPress to Button. Current only onPress is supported.
onLongPress support is needed on button .
> feat: Add OnLongPress to Button component

- docs/pages/6.recommended-libraries.md
There should be an enter https://callstack.github.io/react-native-paper/recommended-libraries.html
> fix: add enter in docs

- src/components/Divider.tsx
The fruit named in the example code differs from that in the screenshot on the same docs page. Why confused the reader?
[docs review]
> Example code to match the screenshot

- src/components/RadioButton/utils.ts
https://github.com/callstack/react-native-paper/issues/2338
https://github.com/callstack/react-native-paper/issues/2338
> fix: Support 0 as value in RadioButton.Group

- src/components/ToggleButton/ToggleButtonGroup.tsx
> Correct link to ToggleButton.Row

- src/components/TextInput/Adornment/TextInputAdornment.tsx
- src/components/TextInput/TextInputFlat.tsx
- src/components/TextInput/constants.tsx
> fix: padding in flat text input on web

- src/components/DataTable/DataTablePagination.tsx
> fix: datatable pagination

- docs/assets/styles.css
> docs: fix links showing underline

- src/components/TextInput/Label/LabelBackground.tsx
> fix: correct label bug related to some Android devices

- .github/workflows/check-repro.yml
- example/src/Examples/TextInputExample.tsx
PR introduces the github action for checking if issue author presented the repro
> chore: add GitHub action for check repro

- src/components/ActivityIndicator.tsx
- src/components/ProgressBar.tsx
- src/components/__tests__/__snapshots__/ActivityIndicator.test.js.snap
- src/components/__tests__/__snapshots__/Button.test.js.snap
- src/components/__tests__/__snapshots__/FAB.test.js.snap
- src/components/__tests__/__snapshots__/ProgressBar.test.js.snap
Improve ProgressBar and ActivityIndicator accessibility. It makes it easier to test as well.
1. Check with TalkBack or Voiceover in the example app.
> feat: improve ProgressBar and ActivityIndicator accessibility

- src/components/Checkbox/CheckboxItem.tsx
- src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.js.snap
- src/components/__tests__/RadioButton/__snapshots__/RadioButtonItem.test.js.snap
Two patches before upcoming release:
* correct text position according to new prop `position` defining location of control component
* update snapshots
> fix: correct text position in CheckboxItem, update snapshots

- src/components/BottomNavigation.tsx
Fixes #2751
Per request @satya164 here: https://github.com/callstack/react-native-paper/pull/2746#discussion_r641439714
> Revert bottom navigation width for web

- src/components/List/ListAccordion.tsx
> fix: do not render empty string as accordion description

- src/components/Menu/Menu.tsx
- src/components/Menu/MenuItem.tsx
Fixes #2844
The changes closely follow Card: https://github.com/callstack/react-native-paper/blob/main/src/components/Card/Card.tsx
> fix: missing Menu.Item theme prop

- src/components/TextInput/TextInput.tsx
Fix typo in `TextInput` comments
> docs: fix typo

- src/components/Checkbox/CheckboxItem.tsx
- src/components/RadioButton/RadioButtonItem.tsx
Resolve inconsistency described in #2859. There's no need to specify in the description
> docs: fix CheckBox/RadioButton position prop

- src/components/RadioButton/RadioButtonGroup.tsx
- src/components/__tests__/RadioButton/__snapshots__/RadioButtonGroup.test.js.snap
Resolve #2922
Before | After
--- | --
> fix: make RadioButtonGroup accessible

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/check-repro.yml
- .github/workflows/publish-each-pr.yml
- .github/workflows/triage.yaml
- CONTRIBUTING.md
- README.md
- docs/assets/snack.js
- docs/pages/src/Home.js
- example/README.md
Update the expo domain from `.io` to `.dev`.
> chore: update snack domain to .dev

- src/components/Searchbar.tsx
> fix: remove outline from Searchbar on Web

- src/components/Button.tsx
- src/components/__tests__/Button.test.js
- src/components/__tests__/__snapshots__/Button.test.js.snap
Add `accessibilityHint` prop to `Button` component.
- set `accessibilityHint` prop
- Add missing `accessibilityLabel` prop test
> feat(a11y): button: add accessibility hint prop

- .eslintrc
- example/src/Examples/ButtonExample.tsx
- example/src/Examples/CheckboxItemExample.tsx
- example/src/Examples/MenuExample.tsx
- example/src/Examples/RadioButtonItemExample.tsx
- example/src/Examples/ToggleButtonExample.tsx
- example/src/RootNavigator.tsx
- example/src/index.tsx
- package.json
- src/components/Badge.tsx
- src/components/Chip.tsx
- src/components/FAB/FAB.tsx
- src/components/List/ListAccordionGroup.tsx
- src/components/MaterialCommunityIcon.tsx
- src/components/Modal.tsx
- src/components/ProgressBar.tsx
- src/components/Snackbar.tsx
- src/components/TextInput/Adornment/TextInputAdornment.tsx
- src/components/TextInput/Adornment/TextInputAffix.tsx
- src/components/TextInput/Adornment/TextInputIcon.tsx
- src/components/TextInput/TextInput.tsx
- src/components/TextInput/TextInputFlat.tsx
- src/components/TextInput/TextInputOutlined.tsx
- src/components/ToggleButton/ToggleButtonGroup.tsx
- src/core/Provider.tsx
- src/core/theming.tsx
- src/styles/fonts.tsx
- yarn.lock
* updates typescript to `4.5.4`
* updates prettier to `2.5.0`
1. CI should be green (lint, tests, typescript)
2. App mustn't crash
> chore: update typescript and prettier versions

- example/src/DrawerItems.tsx
- example/src/index.tsx
- src/index.tsx
Adds "Switch back to Material 2" toggle in Drawer component. Will make our lives easier when comparing to old Material 2 theme
https://user-images.githubusercontent.com/24693481/152169887-4a1d6e23-eca4-4b4e-9c78-d41024dd322e.mov
> feat: add theme switcher

- example/package.json
- example/src/ExampleList.tsx
- example/yarn.lock
PR:
* updates reanimated library in example
* adds background color to example flat list styles
> chore: update reanimated in example app

- src/components/DataTable/DataTableCell.tsx
- src/components/__tests__/__snapshots__/DataTable.test.js.snap
Fixes lint and updates test for CI.
CI should pass.
> chore: fix lint and tests

- example/src/Examples/TextExample.tsx
- src/styles/themes/v3/tokens.tsx
Correct kind of font used on Android, by overriding a default type.
> fix: correct android font

- .all-contributorsrc
- README.md
> chore: update contributor data

- example/src/Examples/AppbarExample.tsx
- src/components/Appbar/Appbar.tsx
- src/components/Appbar/AppbarContent.tsx
- src/components/Appbar/utils.ts
PR introduces:
* fix for appbar height for MD3
* appbar action color correction
* example adjustments
> refactor: correct MD3 default appbar height

- docs/pages/10.migration-guide-to-5.0.md
- example/src/Examples/CardExample.tsx
- src/components/Card/Card.tsx
- src/components/Card/helpers.tsx
To be consistent with other similar props, I've renamed `filled` to `contained`.
> refactor: renamed card mode prop filled to contained

- src/components/IconButton/IconButton.tsx
- src/components/ToggleButton/utils.ts
- src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
- src/components/__tests__/__snapshots__/DataTable.test.js.snap
- src/components/__tests__/__snapshots__/IconButton.test.js.snap
- src/components/__tests__/__snapshots__/Searchbar.test.js.snap
- src/components/__tests__/__snapshots__/TextInput.test.js.snap
- src/components/__tests__/__snapshots__/ToggleButton.test.js.snap
PR removes elevation introduced due to wrapping touchable into `Surface`, especially on theme version 2, where there was no surface wrapper.
Snapshots are updated according to elevation deletion.
> fix: correct icon button surface

- docs/pages/10.migration-guide-to-5.0.md
- Replace localhost url to relative hash link
- It's a very small change, so haven't tested it 😬
> fix: tiny typo in versioning link

- example/src/Examples/CardExample.tsx
- src/styles/themes/v3/tokens.tsx
PR adds correct fonts for web platforms. 
Fixes `Card` examples where and alert should be displayed.
> fix: correct web font

- src/components/__tests__/Appbar/Appbar.test.js
- src/components/__tests__/Button.test.js
- src/components/__tests__/Checkbox/utils.test.js
- src/components/__tests__/Chip.test.js
- src/components/__tests__/FAB.test.js
- src/components/__tests__/IconButton.test.js
- src/components/__tests__/MenuItem.test.js
- src/components/__tests__/Switch.test.js
- src/components/__tests__/TextInput.test.js
- src/components/__tests__/ToggleButton.test.js
- src/core/theming.tsx
Extracted `getTheme` util to the theming and used it within tests.
Tests should pass.
> refactor: extract getTheme util to the theming

- docs/pages/10.migration-guide-to-5.0.md
Updating migration guide after adding `customSize` prop to `FAB`.
> docs: add information about FAB customSize prop

- docs/package.json
- docs/pages/src/components/IconsList.js
- docs/yarn.lock
- example/package.json
- example/src/Examples/BottomNavigationExample.tsx
- example/yarn.lock
- package.json
- yarn.lock
Fixes: https://github.com/callstack/react-native-paper/issues/3209
PR updates `react-native-vector-icons` to the latest version.
> chore: update react-native-vector-icons

- src/components/Surface.tsx
Fixes: https://github.com/callstack/react-native-paper/issues/3237
PR adds fallback for missing styles in `Surface` component.
> fix: add style fallback in Surface

- docs/pages/10.migration-guide-to-5.0.md
- docs/pages/2.theming.md
- example/index.d.ts
- example/src/ScreenWrapper.tsx
- example/src/index.tsx
- index.d.ts
- src/components/List/ListSubheader.tsx
- src/components/TextInput/helpers.tsx
- src/components/__tests__/TextInput.test.js
- src/core/Provider.tsx
- src/core/__tests__/Provider.test.js
- src/core/theming.tsx
- src/index.tsx
- src/styles/overlay.tsx
- src/styles/themes/index.ts
- src/styles/themes/v2/DarkTheme.tsx
- src/styles/themes/v2/LightTheme.tsx
- src/styles/themes/v3/DarkTheme.tsx
- src/styles/themes/v3/LightTheme.tsx
- src/types.tsx
Solves: https://github.com/callstack/react-native-paper/issues/3223
Changes here are meant to fix outstanding issues with types in Material You. It also allows to pass a global type definition for cases where you want to have the Material Design 2 theme's static typechecking
> feat: update types to match global approach

- docs/pages/10.migration-guide-to-5.0.md
Small changes to improve readability of Material You documentation
> docs: improve readability

- docs/pages/1.getting-started.md
- docs/pages/2.theming.md
Update links related to default themes in `theming` and `getting started` sections.
> docs: update theming and getting started sections

- docs/component-docs.config.js
> Fix Github edit link: master -> main

- src/core/theming.tsx
- src/index.tsx
PR exports `DefaultTheme`, which basically is `MD3LightTheme` and was imported in the previous version as well.
> feat: export DefaultTheme

- example/README.md
Update the link
Tested link, it works!
> fix: update link to example app

- package.json
- src/components/__tests__/BottomNavigation.test.js
- src/components/__tests__/Button.test.js
- src/components/__tests__/Card/Card.test.js
- src/components/__tests__/DataTable.test.js
- src/components/__tests__/Modal.test.js
- src/components/__tests__/Surface.test.js
- src/components/__tests__/TextInput.test.js
- yarn.lock
PR introduces some adjustments according to the [comment](https://github.com/callstack/react-native-paper/pull/3300#issuecomment-1212871400) from the previously merged PR.
Test and CI should pass.
> chore: testing library adjustments

- .github/workflows/semantic-pr.yml
Since [semantic pr](https://github.com/zeke/semantic-pull-requests) service is no longer supported, the PR is introducing the alternative: https://github.com/amannn/action-semantic-pull-request.
CI should have a new step: Semantic PR and should pass.
> chore: add semantic pr title check

- docs/pages/1.getting-started.md
remove "," on example documentation
fix typo on example documentation
> docs: update example on getting-started.md

- src/components/BottomNavigation/BottomNavigationRouteScreen.tsx
- src/components/__tests__/BottomNavigation.test.js
- src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
Adds display flex / none only on web. Fixes: #3292
CI test
> fix: change RouteScreen visibility only on web

- src/components/TextInput/Label/LabelBackground.tsx
- src/components/__tests__/__snapshots__/TextInput.test.js.snap
PR corrects `TextInput`'s label layout.
Updated snapshots
> fix: correct text input label background layout

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/workflows/check-repro.yml
PR improves GitHub issue templates:
* add label `bug` to "bug report" issue template
* add label `feature request` to "feature request" issue template
* add label `question` to "question" issue template
Additionally adds `if` condition to the `check_repro` GitHub action to be run only on `bug` issues.
> chore: update github issue templates

- src/components/Banner.tsx
Correct type for `children` in `Banner` component
- #3394
> fix: correct Banner children type

- src/components/Divider.tsx
- src/components/__tests__/Drawer/__snapshots__/DrawerSection.test.js.snap
PR introduces `Divider` component adjustments according to the latest MD guidelines.
> refactor: adjust divider component insets

- example/src/Examples/ProgressBarExample.tsx
- src/components/ProgressBar.tsx
- src/components/__tests__/__snapshots__/ProgressBar.test.js.snap
Update `ProgressBar` track color to match MD3 guidlines.
Updated snapshots.
> refactor: adjust progress bar track color

- src/components/Card/Card.tsx
- src/components/Card/utils.tsx
- src/components/__tests__/Card/Card.test.js
Refer to https://github.com/callstack/react-native-paper/issues/3477
> fix: add tint to elevated Card

- docs/pages/10.migration-guide-to-5.0.md
- docs/pages/4.fonts.mdx
Updated documentation with fonts variants available in MD3. 
- #3501 
Tested docs locally.
> docs: add table with fonts variants

- src/components/Button/Button.tsx
- src/components/Card/Card.tsx
- src/components/Chip/Chip.tsx
- src/components/FAB/AnimatedFAB.tsx
- src/components/FAB/FAB.tsx
- src/components/List/ListAccordion.tsx
PR introduces the prop `delayLongPress` for the components which are supporting `onLongPress`.
- #3534 
N/A
> feat: add delay long press support

- docs/pages/8.theming-with-react-navigation.md
- example/src/Examples/BadgeExample.tsx
- example/src/Examples/ProgressBarExample.tsx
- example/src/Examples/TouchableRippleExample.tsx
- src/components/Card/Card.tsx
- src/components/Card/CardContent.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Dialog/DialogContent.tsx
- src/components/Dialog/DialogIcon.tsx
- src/components/Dialog/DialogTitle.tsx
Migrate V5 doc to the new MD3 typography (`Paragraph` only).
Happy to migrate the rest of the doc if this makes sense.
> docs: Replace Paragraph with Text anywhere

- src/components/SegmentedButtons/SegmentedButtonItem.tsx
- src/components/__tests__/SegmentedButton.test.js
- src/components/__tests__/__snapshots__/SegmentedButton.test.js.snap
Correct the condition for displaying the icon within the `SegmentedButton`.
- #3570 
Covered by unit tests.
> fix: adjust condition for displaying icon

- docusaurus/docs/guides/01-getting-started.md
- docusaurus/docs/guides/05-react-native-web.md
- docusaurus/docs/guides/09-theming-with-react-navigation.md
- docusaurus/docs/guides/11-migration-guide-to-5.0.md
- docusaurus/docusaurus.config.js
- docusaurus/package.json
- docusaurus/yarn.lock
https://user-images.githubusercontent.com/35961879/215083071-7202672b-7da9-40b9-8833-045cae9fc6a3.mov
> docs: add npm2yarn plugin and update all docs to use it

- docusaurus/.eslintrc
- docusaurus/docusaurus.config.js
- docusaurus/package.json
- docusaurus/plugins/docusaurus-react-native-plugin.js
- docusaurus/src/components/BannerExample.tsx
- docusaurus/src/pages/index.mdx
- docusaurus/tsconfig.json
- docusaurus/yarn.lock
- Created a Docusaurus plugin to run `react-native` components (using React Native for the Web)
- Added a simple components overview example
https://user-images.githubusercontent.com/35961879/215330302-f8cbf7b2-7fba-4718-be86-71b6e521ae19.mov
> docs: add react-native-web support plugin

- src/components/TextInput/Label/InputLabel.tsx
- src/components/TextInput/Label/LabelBackground.tsx
- src/components/TextInput/TextInput.tsx
- src/components/TextInput/TextInputFlat.tsx
- src/components/TextInput/TextInputOutlined.tsx
- src/components/TextInput/helpers.tsx
- src/components/__tests__/__snapshots__/TextInput.test.js.snap
- src/utils/roundLayoutSize.ts
Performance optimizations for TextInput component.
The most I could squeeze off it without major refactor - just by avoiding unnecessary rerenders and interpolations. From my calculations  we managed to:
- speed up first render by 25%
- speed up subsequent renders by 35%
- speed up rerenders after each key stroke by 40%
Check for visible regressions in the test app
> refactor: fix performance of TextInput

- .circleci/config.yml
- package.json
- src/components/Modal.tsx
CI shouldn't fix lint issues
CI fails when there are unfixed lint issues: https://app.circleci.com/pipelines/github/callstack/react-native-paper/3399/workflows/86351c5b-19ab-409d-9700-03fb3629572c/jobs/33187
> ci: disable auto fix for lint

- docs/docusaurus.config.js
Adding algolia search functionality to the docs.
Tested on the local build
> docs: add algolia search functionality

- docs/docusaurus.config.js
> docs: update the editUrl in docusaurus config file

- docs/src/components/BannerExample.tsx
- docs/src/components/GetStartedButtons.tsx
- docs/src/pages/index.mdx
> docs: add get started button on initial page

- docs/package.json
- docs/yarn.lock
> docs: upgrade docusaurus to v2.3.1

- example/babel.config.js
- package.json
Fixes: #3712
Updated devDependencies and babel.config.js file accordingly to expo [docs](https://docs.expo.dev/versions/latest/sdk/reanimated/#web-support)
> fix: add missing babel plugin for expo web support

- docs/docusaurus.config.js
Fixes: https://github.com/callstack/react-native-paper/issues/3695
Configure the URL for `Edit this page` available on each component.
After pressing the `Edit this page` user should be navigated to the specific component on the github.
> docs: configure edit url link

- docs/docs/guides/08-theming-with-react-navigation.md
could save a couple of debugging hours 😅
thank you to all the maintainers and collaborators 🙏
> docs: update code snippets

- src/components/Menu/MenuItem.tsx
- src/components/__tests__/MenuItem.test.tsx
- src/components/__tests__/__snapshots__/Menu.test.tsx.snap
- src/components/__tests__/__snapshots__/MenuItem.test.tsx.snap
Fixes: https://github.com/callstack/react-native-paper/issues/3718
Introducing prop `titleMaxFontSizeMultiplier` which allows specifying the largest possible scale a title font can reach.
https://github.com/callstack/react-native-paper/issues/3718
Added unit test.
> feat: support for titleMaxFontSizeMultiplier

- src/components/TouchableRipple/TouchableRipple.native.tsx
- tsconfig.json
Fixes #3732 
Adds `"moduleSuffixes": [".android", ".native", ".ios", ""]` to tsconfig and fixes errors. 
`yarn typescript` doesn't fail
> fix: sync `TouchableRipple` prop types

- docs/docs/guides/02-theming.mdx
- docs/docs/guides/06-recommended-libraries.md
#3315
As [requested](https://github.com/callstack/react-native-paper/issues/3315#issuecomment-1476119995) by @lukewalczak:
- Add [`pchmn/expo-material3-theme`](https://github.com/pchmn/expo-material3-theme) to the `Recommanded libraries`
- Add a section in `Theming -> Create dynamic theme colors` to explain how to sync dynamic colors with system colors using the library
> docs: explain how to sync dynamic colors with system colors

- src/components/Tooltip/Tooltip.tsx
- src/components/__tests__/Tooltip.test.tsx
Simplified the idea from another Tooltip PR to make the Tooltip works for now, given it wasn't working.
- #3843 
There are test in place, but now the demo app should work
https://user-images.githubusercontent.com/1676818/234320379-2419a4ff-0aff-4f5d-9bf6-dced669ecb74.mp4
https://user-images.githubusercontent.com/1676818/234320415-65aec919-1c3c-4eee-ad81-6a4d692300de.mp4
> fix: Tooltip wasn't showing 

- example/src/Examples/SegmentedButtons/SegmentedButtonMultiselectRealCase.tsx
- example/src/Examples/SegmentedButtons/SegmentedButtonRealCase.tsx
Correct the `SegmentedButton` layout in the example app.
> style: correct segmented buttons container styles

- src/components/FAB/AnimatedFAB.tsx
- src/components/FAB/FAB.tsx
- src/components/FAB/FABGroup.tsx
- src/components/__tests__/AnimatedFAB.test.tsx
- src/components/__tests__/FAB.test.tsx
- src/components/__tests__/FABGroup.test.tsx
Pass the event in FAB.Group `onLongPress`
Added unit tests. CI should pass.
> chore: pass gesture responder event in FAB.Group `onLongPress`

- example/src/Examples/BannerExample.tsx
- src/components/Banner.tsx
Provide a better experience by keeping the `Banner` visible when scrolling content, like in the following [video](https://kstatic.googleusercontent.com/files/5ae335da176da4b26bce49dd228cc0345dd7a0f9f3a3ccf0069562a249692c3ac0dead206897b2f35a45d558e6aba484b5c9236e1c7a5680a921f9b9d6e4c022)
Manual testing
> refactor: keep banner when scrolling

- src/components/DataTable/DataTable.tsx
Fixes: #3949 
Correct example within `DataTable` which had TS issues.
- #3949
> docs: correct the pagination example

- package.json
- patches/@callstack+react-theme-provider+3.0.8.patch
- src/components/Portal/Portal.tsx
- src/core/PaperProvider.tsx
- yarn.lock
Fixes: https://github.com/callstack/react-native-paper/issues/3857
Apply the missing type for `children` prop in `ThemeProvider`. 
- #3857 
Tested in a separate, fresh project, there are no TS errors.
> fix: correct theme provider type

- example/src/Examples/TooltipExample.tsx
- src/components/Card/Card.tsx
- src/components/Chip/Chip.tsx
Fixes: #3928 
Components adjustments to work well with `Tooltip`, to hide it properly on `onPressOut`, when touch was ended.
- #3928 
Tested manually, added new examples.
> refactor: components adjustments to work with tooltip

- src/components/Menu/Menu.tsx
- src/components/__tests__/__snapshots__/Menu.test.tsx.snap
Fixes: #3921 
Adjusted `pointerEvents` on `Menu` wrapper views.
- #3921 
updated snapshots
> fix: adjust pointer events on menu wrappers

- src/components/TextInput/TextInput.tsx
Fixes: https://github.com/callstack/react-native-paper/issues/3982
Improved `selection color` and `cursor color` docs
We can verify docs before merging.
> docs: Improved `selection color` and `cursor color` docs

- docs/src/components/DynamicColorTheme.tsx
Fixes: https://github.com/callstack/react-native-paper/issues/3975
The issue was that keys in custom colors list were not unique
Described in the original issue: go to docs, make a theme, play around with custom colors
> fix: custom colors list in docs theme builder

- src/components/List/ListItem.tsx
- src/components/__tests__/__snapshots__/ListAccordion.test.tsx.snap
- src/components/__tests__/__snapshots__/ListItem.test.tsx.snap
- src/components/__tests__/__snapshots__/ListSection.test.tsx.snap
Correct the flex properties in the `List.Item`
- #4050 
- Updated snapshots
> fix: list item flex properties

- example/src/Examples/AppbarExample.tsx
- src/components/Appbar/Appbar.tsx
- src/components/Appbar/AppbarHeader.tsx
- src/components/Appbar/utils.ts
- src/components/__tests__/Appbar/Appbar.test.tsx
Unblock using `dark` prop in the `Appbar`
> fix: using direct dark prop in appbar

- example/src/Examples/ButtonExample.tsx
- src/components/Button/Button.tsx
- src/components/__tests__/Button.test.tsx
Refactor `Button` touchable styles to respect different variation of passed border-radius.
- #4048
> fix: correct touchable radius

- src/components/Appbar/Appbar.tsx
- src/components/Appbar/utils.ts
- src/components/TextInput/types.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/__tests__/Appbar/Appbar.test.tsx
- src/react-navigation/types.tsx
Resolve circular dependencies in `Appbar`, `TextInput` and navigation components.
- #3740
> fix: resolve circular dependencies

- example/src/Examples/TextInputExample.tsx
- src/components/TextInput/Label/InputLabel.tsx
- src/components/TextInput/TextInput.tsx
- src/components/TextInput/TextInputFlat.tsx
- src/components/TextInput/TextInputOutlined.tsx
- src/components/TextInput/types.tsx
- src/components/__tests__/__snapshots__/TextInput.test.tsx.snap
Fixes: https://github.com/callstack/react-native-paper/issues/3811 https://github.com/callstack/react-native-paper/issues/4039
Setting input min width, to be properly displayed for shorter label and placeholers
Updated snapshots
> fix: set input min width

- example/src/Examples/IconExample.tsx
- src/components/Icon.tsx
- src/components/MaterialCommunityIcon.tsx
- src/components/__tests__/Icon.test.tsx
- src/core/settings.tsx
* Covering `Icon` component with unit test for 3 case where icon is a `string`, image source or render function.
* Adding appropriate example for each case.
- #3979 
Added unit tests
> refactor: add unit test and adjust icon example screen

- src/components/FAB/FABGroup.tsx
Add theme to FAB buttons
FAB.Group is not overriding theme in each FAB button
> fix: update FABGroup.tsx

- src/components/TouchableRipple/TouchableRipple.native.tsx
- src/components/TouchableRipple/TouchableRipple.tsx
https://github.com/callstack/react-native-paper/issues/3988#issuecomment-1817778440
#3988
Closes #3992
CI passes
> chore: wrap `TouchableRipple` in `forwardRef`

- src/components/List/ListItem.tsx
https://github.com/callstack/react-native-paper/issues/3988#issuecomment-1858845783
https://github.com/callstack/react-native-paper/issues/3988
CI passes
> chore: wrap `List.Item` in `forwardRef`

- src/components/ProgressBar.tsx
- src/components/__tests__/ProgressBar.test.tsx
- src/components/__tests__/__snapshots__/ProgressBar.test.tsx.snap
Ability to customize the filled part of the `ProgressBar`
- #4221 
> feat: progress bar fill style

- src/components/BottomNavigation/BottomNavigation.tsx
- src/components/BottomNavigation/BottomNavigationBar.tsx
Adding activeIndicatorStyle to achieve flexibility when using the BottomNavigation component. 
Primarily I was solving this issue: #4143
> feat: add activeIndicatorStyle to BottomNavigation

- src/components/TextInput/helpers.tsx
- src/components/__tests__/TextInput.test.tsx
- src/components/__tests__/__snapshots__/TextInput.test.tsx.snap
Update colors in `TextInput` according to the latest changes in the Material Design documentation.
#4252 
#4250 
Updated tests and snapshots.
> fix: update input colors

- .circleci/config.yml
To solve CI issue in https://github.com/callstack/react-native-paper/pull/4392
Fixes CI in https://github.com/callstack/react-native-paper/pull/4392
CI should be ✅
> chore: bump node to 18 for circle CI

- src/components/Card/Card.tsx
https://github.com/callstack/react-native-paper/issues/3988#issuecomment-1918187955
https://github.com/callstack/react-native-paper/issues/3988
CI passes
> chore: wrap `Card` in `forwardRef`

- src/components/Button/Button.tsx
https://github.com/callstack/react-native-paper/pull/4150#issuecomment-1962734678
CI passes
> chore: add `touchableRef` to `Button`

- src/components/Modal.tsx
Fixes the grammar for the description of two props for the `Modal` component
N/A
N/A
> docs: property description grammar

- docs/docs/guides/08-theming-with-react-navigation.md
Yes, I'm a grammar nazi
I found this doc hard to read.
None
Read it and see if you like this version better!
> make theming-with-react-navigation more readable

- src/components/TouchableRipple/TouchableRipple.tsx
Fix the _cursor_ on web, when the `Touchable..` is _disabled_.
Fixes: #4659
> fix: set cursor to auto when touchable is disabled

- src/components/BottomNavigation/BottomNavigationBar.tsx
Correct the example in the docs for the `BottomNavigationBar` example.
Fixes: #4453
> docs: correct example code

- src/components/Searchbar.tsx
Add missing method `setSelection` to the `SearchBar`
#4603
> fix: add set selection to the searchbar
