example/src/ButtonExample.js
example/src/ExampleList.js
src/components/Button.js
src/components/Card.js

GIF says a thousand words
We probably need a custom loading indicator for iOS, but that's out of scope for this PR

feat: add icon and loading support to <Button />

---

src/components/Card/Card.js
src/components/Card/CardContent.js
src/core/ThemeProvider.js
src/core/withTheme.js

For example, this will allow you to do `<Button theme={{ roundess: 3 }}>Hello world</Button>`

feat: support theme overrides for themed components

---

docs/index.js
docs/package.json
docs/templates/HTML.js
docs/templates/Page.js

This takes care of generating static HTML files as well as JavaScript bundles. This will allow us to use JavaScript in documentation pages, as well as faster development time since you just have to reload the page instead of building all the documentation again.
Hot reloading is a little slow and doesn't work for functional components right now, but I'll need to work on that in `quik`.

docs: enable JavaScript in documentation

---

src/index.js

Since `export * as ...` requires addition of a custom preset, `react-native-stage-0` or `transform-export-extensions` in `.babelrc`.
Fixes #91.

Removed 'export * as' syntax in 'src/index.js'

---

example/src/CheckboxExample.js
example/src/RadioButtonExample.js
src/components/Checkbox.js
src/components/RadioButton.js

Border animations aren't very nice on iOS, so I disabled animations on iOS for now. Let's add animations when we find a better way.
Also native animations don't support borders as of now, so can't enables native animations either, probably can enable in future

feat: add checkbox and radio animations on Android

---

src/components/Card/Card.js

Code from the example project wasn't working properly. The Card wasn't getting displayed. Fixed by removing flex: 1 from a View inside a TouchableWithoutFeedback.
Fixes #94.

fix: use `flexGrow` instead of `flex` to avoid collapsing

---

README.md
src/core/withTheme.js

- Do not add 'ref' to functional components
- Update docs with current supported version of RN

Do not add 'ref' to functional Components

---

example/src/RootNavigator.js
example/src/ToolbarExample.js
src/components/Icon.js
src/components/Toolbar/Toolbar.js
src/components/Toolbar/ToolbarAction.js
src/components/Toolbar/ToolbarBackAction.js
src/components/Toolbar/ToolbarContent.js
src/components/TouchableRipple.js

Fixes #138.
Following https://material.io/guidelines/platforms/platform-adaptation.html

feat: Toolbar platform adaptation for iOS

---

src/components/Paper.js

This fixes the weird shadow that appeared underneath text in buttons
Before:
After:

fix: Buttons shadow

---

docs/.babelrc
docs/.gitignore
docs/index.js
docs/package.json
docs/pages/1.getting-started.md
docs/pages/2.theming.md
docs/yarn.lock

To write custom pages for docs in React, add a JS file which exports a React component inside `pages/` folder and it'll appear as a page. You can use `linaria` for styling, and set metadata such as title, description and permalink using a static property called `meta`.
```js
import * as React from 'react';
import { css } from 'linaria';
const container = css`
padding: 24px;
font-size: 24px;
`;
export default class Custom extends React.Component<{}> {
static meta = {
title: 'Custom 🎉',
description: 'Custom React Component',
permalink: 'index',
};
render() {
return <div className={container}>🌹 🌻 🌷 🌿 🌵 🌾 🌼⁣</div>;
}
}
```

docs: support custom pages in docs

---

example/src/ButtonExample.js

The old URI points to a 404 right now, as the React's logo on Facebook's page is now a data URI. Ideally, we could host the used image on callstack.github.io, but the current push process prevents us from that.

Fixing 'remote image' button example

---

docs/pages/1.getting-started.md
docs/pages/2.theming.md

Hello, Callstack developers
I fixed 2 links to [defaultTheme.js](https://github.com/callstack/react-native-paper/blob/master/src/styles/DefaultTheme.js) which are invalid on GitHub Pages.

Fix links to default theme file

---

src/components/Card/CardCover.js

Added the missing CardCover props documentation. It's now linking to react-native Image component.

docs: add the missing CardCover props

---

yarn.lock

Looks like the [latest master commit](https://github.com/callstack/react-native-paper/commit/5a67be9a2f1e429dc4eae654efba6a579f5c1a83) didn't fully update yarn.lock. The pull request includes the updated lock file.

fix: update the lockfile

---

example/App.js
example/package.json
example/yarn.lock
src/components/Portal/Portal.js
src/components/Portal/PortalConsumer.js
src/components/Portal/PortalHost.js
src/components/Portal/PortalManager.js
src/components/Portal/ThemedPortal.js
src/components/__tests__/Portal.test.js
src/components/__tests__/__snapshots__/Portal.test.js.snap
src/core/Provider.js
src/core/ThemeProvider.js
yarn.lock

The PR reworks the portal implementation so that the portals render under a different tree under a pure component, which is not affected by the parent component's re-renders.
This also updates the portal code to use the new context API.

fix: rework portal to isolate rendering of portals. fixes #216

---

src/components/TextInput.js

The pull request changes the TextInput multiline prop to optional. Defaults to false.
Not providing the multiline prop is causing a flow error, while the docs example states it's not required.

fix: do not require the TextInput multiline prop

---

src/components/TextInput.js

Same as #266, the numberOfLines prop for TextInput shouldn't be required. Causes a flow error when not provided.

fix: do not require the TextInput numberOfLines prop

---

src/components/Toolbar/Toolbar.js

Earlier we used `SafeAreaView` on iOS to offset for status bar height, but seems it doesn't work on iOS < 11. This PR attempts to handle old versions of iOS.

fix: fix statusbar height on old versions of ios

---

CONTRIBUTING.md
README.md
docs/pages/4.contributing.md

It's still pretty big, but all the important stuff about setting up the environment is on the top. Rest is verified by the pre-commit hook, so not a big deal if people don't read them.

docs: simplify contribution guidelines

---

src/components/Dialog/Dialog.js

Hey,
I've been just trying the dialog component docs example. Sending a typo fix.

docs: fix dialog component typo

---

example/src/RootNavigator.js
src/core/withTheme.js

Currently, there is no way to preserve types of static properties of React components when they are wrapped in the `withTheme` HOC. This PR adds a HOC named `withStatics` which helps to add static properties to a component
API:
```js
export default withStatics(withTheme(Toast), {
DURATION_LONG: 3500
});
```
The document generator won't handle such static properties. So we'll need to write those manually.

fix: support static properties in withTheme HOC

---

src/components/Checkbox.js
src/components/RadioButton.js

It was impossible to set the color of Checkbox/RadioButton in the unchecked state.
No, most likely only this way.
List the steps with which we can test this change. Provide screenshots if this changes anything visual.
just pass uncheckedColor="white" to the Checkbox/RadioButton component.
result:

uncheckedColor prop for Checkbox and RadioButton 

---

.circleci/config.yml
.eslintignore
.gitignore
babel.js
docs/pages/2.getting-started.md
package.json
scripts/generate-mappings.js
scripts/validate-commit-message.js
src/babel/.eslintrc
src/babel/__fixtures__/rewrite-imports/code.js
src/babel/__fixtures__/rewrite-imports/output.js
src/babel/__tests__/index.js
src/babel/index.js
yarn.lock

feat: add babel plugin for modular imports

---

src/components/SearchBar.js

added focus(),clear()blur(),isFocused(),setNativeProps() methods to SearchBar.js, exactly the same way as the TextInput.js....
although I prefer adding textInputRef props to expose the TextInput ref to the SearchBar..
onChangeText no longer a required props for the clear button to work.
SearchBar is kind of a  textInput groomed with one additional icon and clear button. Basic  Functionality like focus(), blur() is better exposed to user. a very common use cases is when user click on the search icon, the textinput get focused. something like onIconPress=> this.ref.searchbar.focus().
this issue can be solved with a different approach, that is expose the underlying nativeTextInput ref to SearchBar. But the TextInput already doing it this way, so ... consistent.

update SearchBar.js according to TextInput.js

---

src/components/Checkbox.ios.js

The way is done now, it removes the view completely so the space is not filled anymore (which is weird from check<->uncheck).

fix: hide checkbox on iOS instead of removing it

---

src/components/BottomNavigation.js
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

When routes are inactive, position them offscreen and use `removeClippedSubviews` to optimize memory usage. The basic approach is this:
- Use animated values to specify which routes are offscreen, so we can imperatively set the value and avoid unnecessary re-renders
- Before animation starts, clear offset of previous and new route, so we see the cross-fade animation
- When animation ends, set offset of inactive screens to a large value to position it offscreen
cc @brentvatne

feat: save memory usage for inactive routes in bottom navigation

---

src/components/Portal/PortalManager.js

Components rendered in portals with same elevation prop are placed in different groups.
Components rendered in portals with same elevation should be placed in the same group and should be rendered one by one

Fix issue with portal groups

---

docs/pages/2.getting-started.md

I generated a new project with CRNA. My babelrc file had an `env` key so I thought this clarification could help beginners.
Thanks!

Docs: Add Babel example with env setting from CRNA

---

src/components/Dialog/Dialog.js
src/components/Divider.js
src/components/Modal.js
src/components/Paper.js
src/components/RadioButtonGroup.js

Fixes Text component imports. Prefer paper over react-native. Add missing imports, remove obsolete imports.

docs: change Text imports

---

src/components/DrawerSection.js

Minor docs example improvement for DrawerSection. Since `active` was already extracted, no need to explicitly do `this.state.active`.

docs: Improve the DrawerSection example

---

src/components/Button.js
src/components/Checkbox.ios.js
src/components/Checkbox.js

I have noticed there's a "disabled" prop for TouchableRipple. It should be able to simplify some code areas, like the multiple conditions inside the Button component. Is this okay to use?
Snapshot tests working fine.

refactor: use touchable's disabled prop

---

example/DrawerItems.js
src/components/DrawerItem.js
src/components/__tests__/DrawerItem.test.js
src/components/__tests__/__snapshots__/DrawerItem.test.js.snap

Drawer redesign for 2.0. Changes:
- changed the active state styling
- colors are now theme based, not fixed
- theme based roundness
- removed the "color" prop - it can be now controller with the primaryColor (see [the expo app example](https://github.com/callstack/react-native-paper/pull/377/files#diff-cf8d6e3323746c5c486de08cb0c333c3R59))
- added snapshot tests
Fixes #358.
Snapshot tests added. Run `yarn test`.

BREAKING: Drawer redesign

---

src/components/DrawerItem.js
src/components/DrawerSection.js

Use paper's typography instead of the react-native Text component for DrawerItem and DrawerSection. Other components seem to follow the same principle.

refactor: use paper's typography for drawer

---

src/components/Portal/PortalHost.js

Nesting modals currently cause an exception because the portal manager is not passed on.
```
<Dialog visible={true}>
<Dialog visible={true}>
</Dialog>
</Dialog>
```

fix: make Modal nestable

---

example/yarn.lock
src/components/Portal/PortalHost.js

The ref function is called twice on updates (see https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs). This behaviour causes the variable `this._manager` sometimes to be null during rendering and in that case actions are pushed to the queue again. Since the queue is only processed once (during componentDidMount), somes changes will never be visible. The simple solution is to bind the ref-function as mentioned in the link above.
Dynamically change `visible` parameter of Modal. The Modal won't be visible on the second time.

fix: ref set to null on updates

---

src/components/List/ListItem.js

When `description` is an empty string, the empty string is rendered instead of the `Text` node.
Pass empty string for `description` property.

fix: empty string causes error

---

src/components/Snackbar.js
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

If you have a tabbar or anything at the bottom, and you move the snackbar up, snackbar will block all pointer events at the bottom of the screen.
`pointerEvents="box-none"` on both SafeAreaView and Animated.View will fix this issue but still allow you to add buttons within Snackbar component

Fix bug that blocks touch at the bottom of the screen

---

src/components/TextInput.js

Focus and blur events are still triggered even if the input is disabled
Set disabled to true and see how you can still focus and blur an input field.

fix: prevent focus and blur if disabled

---

src/components/Card/Card.js

Disable `Touchable` if no press handler was passed. Otherwise a pointer cursor will always appear on web platform though it's not clickable.
n/a

fix: disable Touchable if no press handler was passed

---

src/components/Button.js
src/components/List/ListItem.js

I had the same issue described in #477 where I need to pass testID and/or accessibilityLabel to buttons to find them in e2e tests.
The same behaviour is implemented in other components such as [FAB](https://github.com/callstack/react-native-paper/blob/master/src/components/FAB.js#L97)
Create a button and pass a testID
```
function testID(id) {
return Platform.OS === 'android' ? { accessible: true, accessibilityLabel: id } : { testID: id }
}
<Button
{...testID('skip-button')}
onPress={async () => {
// ...
}}
>
Skip
</Button>
```
This works now in appium tests with wd
```
const skipButton = await client.elementByAccessibilityId('skip-button')
await skipButton.click()
```

fix: pass rest props into button

---

src/components/Modal.js

Add `flex:1` to Modal to fix the issue that `Modal` children cannot grow
See https://github.com/callstack/react-native-paper/issues/471
See https://github.com/callstack/react-native-paper/issues/471

Fix issue that `Modal` children cannot grow

---

src/components/Card/Card.js

Change elevation of Card component according to Material Design Guidelines and decrease a bit elevation animation time, it makes elevation change effect more noticeable.

Set proper elevation for Card and decrease animation time.

---

src/components/Modal.js

Since #491 the content is not centered automatically anymore because the children take up 100% and `justifyContent` on the parent container has no effect.
n/a

fix: justify content centered in Modals

---

docs/pages/src/Home.js

I've noticed that link to the _getting started_ page in the docs seems to not working as expected since `*.html` extension is added anyway and it makes the link broken:
`https://callstack.github.io/react-native-paper/getting-started.html.html`.
The documentation is important part of the library and should be working properly.
Enter `/docs`, install using `yarn` and run it with `yarn start`.
> **NOTE:** _the current version works on localhost and breaks only in the prod env. Suggested change will probably work in both, but needs to be verified by someone who knows the deployment process._

docs: fix wrong URL to 'getting started'

---

src/components/Card/Card.js

`TouchableWithoutFeedback` has no style prop. Causes a flow error (flow 0.75). Related to #451.
The PR removes the style prop.
https://facebook.github.io/react-native/docs/touchablewithoutfeedback
The Expo Card example looks the same.

fix: Remove style prop from touchable

---

CONTRIBUTING.md
example/src/CardExample.js
src/components/Card/Card.js

First contribution to this repo; feel free to critique however is needed to merge.  :)
This adds `onLongPress` to `Card.js` so that if you use a `<Card>` you can specify an `onLongPress` instead of just `onPress` if desired.  I have a use case where a long press on a card is desirable.
Makes minor updates to `CONTRIBUTING.md` that I needed and should make it easier for another first contributor.
The `CardExample.js` has been updated with both `onPress` and `onLongPress` examples.
Testing was done primarily on an iPhone X in the iOS simulator running 11.4.
If desired, happy to do other testing.
The current test suites pass fine as well:
```
yarn test v0.27.5
$ jest
PASS  src/components/__tests__/Snackbar.test.js
PASS  src/components/__tests__/ListAccordion.test.js
PASS …
```

feat: add onLongPress to Card

---

example/app.json
example/package.json
example/yarn.lock

This PR upgrades expo in example app to latest version.
Actually, there is no issue for that, but It's good to use latest stable version of libraries.

chore: Update expo to latest version.

---

typings/components/Snackbar.d.ts

paper version: v2.1.3
typescript version: v3.0.1
Below `Snackbar` usage has error.
And error message:
```
path/to/my/component.tsx:131:17 - error TS2322: Type 'string' is not assignable to type 'number | undefined'.
131                 duration={Snackbar.DURATION_SHORT}
~~~~~~~~
node_modules/react-native-paper/typings/components/Snackbar.d.ts:10:3
10   duration?: number;
~~~~~~~~
The expected type comes from property 'duration' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Snackbar> & Readonly<{ children?: ReactNode; }> & Readonly<SnackbarProps>'
```
Because `duration` was defined as a `string` in the type definition file. I fixed it.
Typecheck for below jsx.
```jsx
<Snackbar
visible={true}
duration={Snackbar.DURATION_SHORT}>
Foo
</Snackbar>
```

fix: fix Snackbar static constants type for typescript

---

src/components/Snackbar.js

Snackbar stays hidden if the `visible` property is initially `true`. See: https://snack.expo.io/ryaOtYho7 
n/a

fix: hidden snackbar if initially visible

---

src/components/Banner.js

Other PRs break because of this (e.g. see `typescript` deploy script at https://github.com/callstack/react-native-paper/pull/620)
Run `yarn typescript` and it should not break anymore.

fix: make example typescript compatible

---

src/components/Portal/PortalConsumer.js

This PR makes clear what is the cause of app crash when user doesn't wrap his components' tree with Provider component.
Render Portal component without wrapping components' tree with Provider component.
Nice error message with link to our docs will be presented.

feat: provide nice error message for users that use Portal without Provider.

---

example/src/ListAccordionExample.js
src/components/List/ListAccordion.js
src/components/__tests__/ListAccordion.test.js
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
typings/components/List.d.ts

This PR aims to FIX #616 and FIX #635 and CLOSE #618 
It allows the List.Accordion to behave as a [controlled component](https://reactjs.org/docs/forms.html#controlled-components) by passing a `expanded` and `onPress` prop.
This also enables users to start the accordion as expanded. 
I added a controlled List.Accordion to the example app and also added a snapshot test.
**Thank you @jimmiehansson for starting this out in #618, I left your commits on my branch so you can take your deserved credits ❤️**

Allow List.Accordion to behave as a controlled component

---

src/components/TextInput.js

Fixes `TextInput` alignment with `multiline` set to `true`. #648

fix: TextInput align top with multiline

---

example/metro.config.js
example/package.json
example/yarn.lock

Fixes this issue https://github.com/callstack/react-native-paper/issues/426
Removed `glob-to-regex` module due to this the node_modules in the / and the docs/ were not ignored by the metro-config.json (Expo)
Updated `expo-cli` module to remove the okhttps spam :smile: 
But a new issue is thrown
`Unable to resolve "@babel/runtime/helpers/interopRequireDefault" from "..\src\index.js"`

Ambiguous resolution

---

src/components/Appbar/AppbarContent.js

Fix https://github.com/callstack/react-native-paper/issues/682
Receive on press property on AppBar Content component
Tested on example app and it works perfectly.

feat: add onpress property for appbar content

---

src/components/TextInput.js

Fixes issues like this #562 due to the transformed offset that imitates transform origin on label scale do not count for RTL and make the offset in the wrong direction

fix: textInput label wrong position in RTL

---

example/src/FABExample.js
src/components/FAB/FAB.js
src/components/FAB/FABGroup.js
src/components/__tests__/__snapshots__/FAB.test.js.snap
typings/components/FAB.d.ts

Adds expanding animation for visibility to FAB as described here:
https://material.io/design/components/buttons-floating-action-button.html#behavior
Open examples on device and click first FAB to toggle visibility.

feat: animated visibility for FAB

---

src/components/Searchbar.js

Searchbar doesn't use fontFamily described in custom theme.
I wonder that why Searchbar doesn't use fontFamily of TextInput. maybe someone can explain it.

fix: use fontFamily of theme for Searchbar

---

src/components/Chip.js
src/components/__tests__/__snapshots__/Chip.test.js.snap

The `Chip` component had a strict height on its `Text` component, which would clip the text internally if the user had adjusted the font size of the application.
1. Create an app with a `Chip` component
1. Adjust your font size in the device's Accessibility settings to the largest possible font size
1. Start the app
1. Observe that the text is not clipped inside the `Chip` component

Allow Chip to expand to font sizing changes

---

example/App.js

On the following line the parenthesis are not properly located:
https://github.com/callstack/react-native-paper/blob/bcef4a60ba72669d51cd9418a341193c9bb0cfc8/example/App.js#L41
this is how it is right now:
drawerPosition: Platform.OS === 'android' && (I18nManager.isRTL ? 'right' : 'left'),
this is how it should be:
drawerPosition: (Platform.OS === 'android' && I18nManager.isRTL) ? 'right' : 'left',
since "drawerPosition" accepts the values: { 'left', 'right' }
Thanks.

fixing parenthesis locations

---

src/components/Snackbar.js
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

The `borderRadius` / `roundness` prop was not working as expected because there was a typo in its name.
n/a

fix: replace 'orderRadius' with 'borderRadius' in Snackbar component

---

typings/components/TextInput.d.ts

* paper version: v2.6.1
* typescript version: v3.2.2
The `TextInput` class has public methods `isFocused`, `clear`, `focus`, `blur`.
https://github.com/callstack/react-native-paper/blob/v2.6.1/src/components/TextInput.js#L348-L374
However, they are not declared in d.ts as below.
Typecheck for below function.
```typescript
import { TextInput } from "react-native-paper";
function doAnything(textInput: TextInput) {
textInput.isFocused();
textInput.clear();
textInput.focus();
textInput.blur();
}
```

fix TypeScript typings for TextInput methods

---

src/components/Icon.js

The error messages from try block loading Icons were conditional and did not include the actual error. makes icon load errors more informative
don't install icons, so that you render the squares. look for error in console

fix: makes icon load errors more informative

---

src/components/FAB/FABGroup.js
typings/components/FAB.d.ts

It's currently possible to change the background color for FAB and also items within FAB.Group components. Changing the background color in FAB Group causes the overlay background to change.
This PR makes it possible to change the background for the FAB Group main button.
Current behavior:
https://snack.expo.io/ryjNEaO7E

fix: Allow to change background for FAB Group

---

src/components/FAB/FABGroup.js

The FAB.Groups docs state the style prop can use a margin in order to position it properly. It's a bit misleading since using the margin repositions the overlay as well. Padding might be the way to go.
With margin:
With padding:
Snack https://snack.expo.io/S1YnC9uQE

docs: FAB.Group should use padding instead of margin

---

src/components/Searchbar.js
src/components/__tests__/Searchbar.test.js
src/components/__tests__/__snapshots__/Searchbar.test.js.snap

On web, the width of the search bar was changing as soon as the cancel icon was rendered. This change always renders the cancel icon but with a transparent color if it should not be visible at all. The nice side effect is now that the complete ripple effect is visible (before it was abruptly stopped because the node was removed).
Check examples.

fix: search bar width changing on web

---

example/src/RootNavigator.native.js

Fixes #282 in example app. It gives extra space for gestures in `react-navigation`.
This is also a fix for the previous PR #754 
Open the example app, change screen and test the gestures in iOS.

fix: adjust gestures distance for iOS on example app

---

src/components/ToggleButton/ToggleButton.js

Path to ToggleButtonGroup is wrong and that's why it's not displayed correctly in docs.

fix: fix path to ToggleButtonGroup component.

---

docs/pages/src/components/IconsList.js

On [docs/react-native-paper/icons](https://callstack.github.io/react-native-paper/icons.html), when I click on icon and copy this selection to clipboard it contains whitespace after.
Example:
```js
1  account-balance
2
```
The number represents lines in editor.
To prevent whitespace we can select the inner text node, which will result in trimmed string like this:
```js
1 account-balance
```

Remove whitespace around icon selection

---

src/components/ToggleButton/ToggleButton.js

When using `ToggleButton` like this:
```js
<ToggleButton
icon="update"
status={jobSort === "recent" ? "checked" : "unchecked"}
disabled={jobSort === "recent"}
value={"recent"}
onPress={value => {
console.log(value);
}}
/>
```
the output after pressing on button is `SyntheticEvent`.  Expected output should be the value either `checked` or `unchecked`.
When onPress prop is available, expect return value to be `checked || unchecked`.

fix ToggleButton onPress

---

src/components/DataTable/DataTableTitle.js

If no `onPress` handler is passed, there is no reason to enable the `Touchable`.
n/a

fix: disable unpressable data table title

---

src/components/TextInput.js

There is one magical variable that i can't explain.. Adjusted it with a trial and error method. If you know a good name for it, let me know and I'll change it.

fix: textinput label position.

---

src/components/Avatar/AvatarIcon.js
src/components/__tests__/__snapshots__/Avatar.test.js.snap

The icons in `Avatar.Icon` look quite small if the size is high.
Before:
After:

fix: optimize Avatar.Icon look

---

example/src/Examples/CardExample.js
src/components/Card/CardTitle.js

`Card.Title` breaks on web into multiples lines if the title is long enough. This fix sets `numberOfLines` to 1 but also sets a `minHeight` so letters are not cut at the bottom.

fix: set number of lines to 1 in Card.Title

---

typings/components/Card.d.ts

Currently typescript definition of Card component (Card.d.ts) is missing required imports, and importing an inexistent type from Avatar causing typescript to return errors with the latest release. 
This PR aims to fix that issue by importing the required typings from react-native.
Solve typescript errors for projects that use it.
Simply run tsc on the project and the types should be proper now.

fixed typings on Card.d.ts

---

src/components/FAB/FABGroup.js

FAB Group currently doesn't support SafeAreaView. It results in an inconsistent behavior between different phones when using a bottom navigation or such.
Since SafeAreaView is already there for components like Snackbar or BottomNavigation, it might be a good idea to add it here as well.
It's also not so obvious to handle it per project cause of the dark overlay that breaks when SafeAreaView applied outside the component. For now I've ended up using react-native-iphone-x-helper package for my local projects to apply different padding values when notch is there, so hopefully the PR provides a better solution.
Before:
After:

fix: Add SafeAreaView to FAB Group

---

typings/components/Avatar.d.ts
typings/components/Card.d.ts
typings/components/ProgressBar.d.ts

Some types were inaccurate so I implemented the following fixes:
- updated `ProgressBar` according to https://facebook.github.io/react-native/docs/progressbarandroid
- exported complete `Avatar` component
- remove unnecessary `StyledProps` in `Card`
n/a

fix: update types

---

typings/components/Button.d.ts

Add uppercase property
Missing uppercase typescript definition property for button component.
N/A

fix: update typescript types for button

---

src/components/Card/Card.js
typings/components/Card.d.ts

The testID prop is not accessible on children of the TouchableWithoutFeedback component without explicitly setting accessible={false}. So accessible needs to be passed to touchable to find elements by testID value for Appium testing.
TextInput in Card component will be made accessible by setting accessible={false\} on Card
```
<Card style={styles.container} accessible={false}>
<TextInput 
style={styles.inputContainerStyle}
testID='text-input'
mode='outlined'
/>
</Card>
```
Test will validate that TextInput field is accessible
```
it('test that text input field is accessible', () => {
$('~text-input').addValue('foo')
});
```

fix: pass down accessible from Card props to Touchable for Appium tests

---

src/components/DataTable/DataTableTitle.js

Add a `numberOfLines` prop to `DataTable.Title` 
Try to fix #848

Add numberOfLines prop to DataTableTitle

---

src/components/Searchbar.js
src/components/__tests__/__snapshots__/Searchbar.test.js.snap

https://www.slashgear.com/gmail-app-android-ios-material-design-update-released-21566652/
```
<Searchbar
placeholder={'Zoeken'}
onChangeText={this.props.onSearch}
style={{
shadowOpacity: 0.07,
elevation: 2,
}}
inputStyle={{
fontSize: 16,
}}
value={value}
icon={icon}
onIconPress={this._onMenu}
/>
```
Before:
After:
Related pull request:
https://github.com/callstack/react-native-paper/pull/861

Give user the option to change input style in searchbar

---

typings/components/Card.d.ts

`onLongPress` was missing in Typescript types.
n/a

fix(Card): add onLongPress prop to types

---

example/src/Examples/Dialogs/DialogWithLongText.js
src/components/Dialog/DialogScrollArea.js

If you don't set `maxHeight` on the `DialogScrollArea` itself but instead on `Dialog` (which is mostly what you want) the content of the dialog takes too much space and the actions won't be visible anymore:
Open the example for the dialog with long text:
Tests on iDevice and web.

fix: limit Dialog.ScrollArea height

---

src/components/Searchbar.js

I used the searchbar inside the Appbar. But I wanted to change the background color when it's not active. the porblem was that changing background caused the icons to look awkward, and the color didn't match the other components in Appbar. so I decided to add this prop.
I resized the search bar when it was not active. so the other components in the Appbar will be visible.
```<Searchbar iconColor="black"  {...otherProps} />```

added iconColor to searchbar

---

example/src/Examples/ChipExample.js
src/components/Chip.js

Summary: This PR will add two new props to customize color of Chip component
Issue no #725

feat: expose new props to add custom color in Chip component

---

typings/components/Searchbar.d.ts
typings/components/TextInput.d.ts

Missing TS typings for Searchbar methods

fix: Searchbar TS

---

src/components/Banner.js
src/components/__tests__/__snapshots__/Banner.test.js.snap

fix: hide banner when visible prop is false

---

example/src/Examples/TextInputExample.js
src/components/TextInput/TextInput.js
src/components/TextInput/TextInputFlat.js
src/components/TextInput/TextInputOutlined.js
src/components/TextInput/types.js

Move TextInput API from children components to parent. Forward ref to make blur, focus work (#938).
This is second part of TextInput refactor. I moved TextInput methods to parent component and forwarded state / props / handlers down to TextInputFlat and TextInputOutlined.
Check example

fix: Pass ref to child components, move API to parent TextInput

---

src/components/Chip.js

Fixes #955 
- Tested in the example app by setting the borderRadius on the chip.

fix: fix borderRadius support for the Chip component

---

example/src/Examples/ChipExample.js
src/components/Chip.js
src/components/__tests__/__snapshots__/Chip.test.js.snap
typings/components/Chip.d.ts

It would be nice to be able to customize the style of chip's content .

feat: add prop textStyle to Chip

---

src/components/Appbar/Appbar.js
src/components/__tests__/Appbar/Appbar.test.js
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap

fix(appbar): does not pass any additional props to Searchbar component

---

src/components/Appbar/Appbar.js
src/components/__tests__/Appbar/Appbar.test.js
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap

Comparing a string to `child.type.name` doesn't work when the component is wrapped by `withTheme`. So we need to check against its type.
#972 
Before:
Fixed:

fix(appbar): make allowed children to accept additional props

---

src/components/Modal.js
src/components/Portal/PortalConsumer.js

Check if manager is not null for update and unmount and fix the doc

---

src/components/TextInput/TextInputFlat.js
src/components/TextInput/TextInputOutlined.js

`TextInput` did not use the new types of font definition.
n/a

fix: use theme font in TextInputFlat

---

src/components/Card/Card.js

`defaultProps` should mark as required, and should minimize using `$FlowFixMe`.
[Try flow.js ...](https://flow.org/try/#0PTAEFkHsCcFNQJYDsBmlQAsAuWAOBnALhBQBtIB3AOhgHNhYlgATSAY32DgEM2tg2kALa5ISRlk4BiLOwC0AV3zJac5rBTcFpLHNzRIBAFBGEImFlAAlWLywAaUAG9QWAJ654AUVKwhEgGExFARaUABfUBQDIVAAch4+OIBuE3dPUAAFAwJQAF5nAB8jUFBYXwA3biwEMUJQJAUhACNYaHsjQvDUozZSbnx8UAAVWHwsIPNxJEtYAA8sRmYhmzsqSdFprAAebMN8AD5nEtBx6oQ2UHVNbSw93IKnE9Ly2CqautAARg7S7pNSnAkOpoAAKACUx1KpUESHGrjGWHqjRabXyrgwCHwVH0+yor3etSQPWhoDgWAU0CQDW0pFSfyM4TSHngQVQoXRPj8gWCoW26VgkBQI0RGzEEgOPSq0FAuHqbJCYUeZUq50+XwiqWlsvlvKVzhVbzVSHqCmBGmQsGYmqM2rloAVHOVBON9TicU1oBACPh3CQbhM21G4zFWy9kqMQdFwk2EkNhLEeScX0iwAjUZDMfFM3jxqT7tTkq9YEWvv9RiAA)
Make the codebase better
```
yarn flow
```

fix: <Card/> flow type

---

src/components/List/ListAccordion.js
src/components/List/ListSection.js
src/components/List/ListSubheader.js
src/components/__tests__/ListAccordion.test.js
src/components/__tests__/ListSection.test.js
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
src/components/__tests__/__snapshots__/ListSection.test.js.snap
typings/components/List.d.ts

This PR introduces missing style props:
List.Accordion:
- `titleStyle`
- `descriptionStyle`
List.Section
- `titleStyle`
Also improves `style` prop type and description in these components.
Fixes #973 
You can play around by passing these props to List.Accordion and List.Section examples.

Feat: missing titleStyle and descriptionStyle for List.Accordion and List.Section

---

src/components/RadioButton.js
src/components/RadioButtonAndroid.js
src/components/RadioButtonIOS.js
src/components/__tests__/RadioButton.test.js
src/components/__tests__/__snapshots__/RadioButton.test.js.snap

**What existing problem does the pull request solve?**
`RadioButtonAndroid` wasn't triggering the animation on `componentDidUpdate` when it was wrapped by a `RadioButtonGroup` because it was getting the props in the context.  
Before:
Fixed

fix: component RadioGroup animation

---

src/components/__tests__/BottomNavigation.test.js

Jest was throwing the following warning when running tests:
```
console.warn node_modules/react-native/jest/MockNativeMethods.js:19
Calling .measureInWindow() in the test renderer environment is not supported. Instead, mock out your components that use findNodeHandle with replacements that don't rely on the native environment.
```
1. Run `yarn test`
2. Check if jest will threw any warning

fix: warning in console when running tests

---

src/components/Menu/Menu.js
typings/components/Menu.d.ts

This PR makes sure that
- The correct item is focused when showing/hiding the menu
- The menu can be dismissed by the keyboard with `Esc`
- The menu is not rendered when not visible

fix: make the menu keyboard-accessible in browser

---

typings/components/Searchbar.d.ts

According to official [docs](https://callstack.github.io/react-native-paper/searchbar.html#inputStyle), `inputStyle` should be in `SearchbarProps`. The current typing apparently misses it.
Very minor typing change, could be tested straight away by vscode code intellisense.

fix: add inputStyle prop tying to Searchbar

---

__ts-tests__/Chip.test.tsx
typings/components/Chip.d.ts

As of version 2.15.2 the Chip component accepts the prop `selectedColor`
which it defines as an optional string prop. Though this change was
introduced to the Chip component itself, the typings for the component
were not updated which causes Typescript to complain when using the
`selectedColor` prop. This change adds the missing type to appease
Typescript.
The change to `__ts-tests__/Chip.test.tsx` exposes the issue described in the "Motivation" section. Tests pass with the change to `typings/components/Chip.d.ts` and fail without them. There are no visual changes associated with this change.

fix: correct Chip component typings

---

typings/components/Modal.d.ts

Add contentContainerStyle to ModalProps interface

---

src/components/Button.js
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

The wrong elevation is being applied to an outlined button when it is first being rendered as a contained button.
Reproduce steps:
1. Render a button using `mode={this.propsIsContained ? 'contained' : 'outline'}` and set `propsIsContained = 'true'`.
2. Change the property in the component to false during runtime `propsIsContained = false`
3. Observe that elevation is applied on the outlined button while it shouldn't.
**WRONG**
**GOOD**
FYI: duplicate of #1019 didn't know how to update that one.

fix: elevation being applied after mode changes on a button while it shouldn't

---

src/components/Card/CardTitle.js
typings/components/Card.d.ts

This PR adds style APIs for the `left` and `right` of the `Card.Title` component. See also issue #1015. 
This can be tested by creating a card whose `Card.Title` has `left`, `right`, `leftStyle` and `rightStyle` props. The node passed to `left` should be seen do have the style passed to `leftStyle`, and the node passed to `right` should be seen to have the style passed to `rightStyle`.

add props `leftStyle` and `rightStyle` to `Card.Title` so devs can style the `left` and `right` independently

---

example/src/Examples/FABExample.js
src/components/FAB/FAB.js
typings/components/FAB.d.ts

It is nice to have a loading indicator for a fab button 
1 - open example app in expo
2 -click on FAB example
3 -you can see the example of FAB with loading indicator as similar to a normal button
4 - try out -> 
```
<FAB
icon="cancel"
label="Loading FAB"
loading
style={styles.fab}
onPress={() => {}}
visible={this.state.visible}
/>
```

feat: support loading indicator for FAB

---

src/components/Drawer/DrawerSection.js
src/components/__tests__/Drawer/DrawerSection.test.js
src/components/__tests__/Drawer/__snapshots__/DrawerSection.test.js.snap

Apply marginTop to Divider instead of marginVertical
Apply style and marginBottom to View wrapper
Fix #1062 
1. Download this branch
2. Apply style with backgroundColor to a `Drawer.Section` in the example app.

refactor: restructure DrawerSection component

---

src/components/TextInput/TextInput.js
src/components/TextInput/TextInputFlat.js
src/components/TextInput/TextInputOutlined.js

Allow to lock control (set editable to false) without gray it out.
fix #986 
fix #737 
1. When you pass disable prop control becomes disabled and grayedOut.
2. When you pass editable prop to false the control behaves the same as disabled but without grayedOut
Passing both above options at once will makes control disabled and grayedOut

fix: fix editable disable prop

---

src/components/TextInput/TextInput.js

Use defaultValue prop to make the TextInputs uncontrolled
Please see #154
Passing defaultValue does not make effects on minimize label in textInputs.
Passing value as const it does not became 'uncontrolled'
If you pass value the control stays in controlled mode. If you ommit the value props the input becomes uncontrolled. You can also pass defaultValue to show it at first render

feat: allow to make inputs uncontrolled with defaultValue

---

example/src/Examples/ListSectionExample.js
src/components/List/ListItem.js
src/components/__tests__/ListItem.test.js
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/types.js
typings/components/List.d.ts
typings/types.d.ts

Currently, there's no way to customize the description of `List.Item`. In order to make it able to be customized, `List.Item` now accepts a custom node as description.
With these changes we can implement a list item like Gmail app:
```
<List.Item
left={() => (
<Image
source={require('../../assets/images/email-icon.png')}
style={styles.image}
/>
)}
right={props => <List.Icon {...props} icon="star-border" />}
title="List Item 1"
description={({
ellipsizeMode,
color: descriptionColor,
fontSize,
}) => (
<View style={[styles.container, styles.column]}>
<Text
numberOfLines={2}
ellipsizeMode={ellipsizeMode}
style={{ color: descriptionColor, fontSize }}
>
React Native Paper is a high-quality, standard-compliant
Material Design library that has you covered in all major
use-cases.
</Text>
<View …
```

refactor: make ListItem accepts a custom description

---

.circleci/config.yml
.gitignore
package.json

Sometimes CircleCI is running out of memory when running the job `unit-tests` .
```
Test Suites: 26 passed, 26 total
Tests:       106 passed, 106 total
Snapshots:   105 passed, 105 total
Time:        4.133s, estimated 8s
Ran all test suites.
Done in 5.67s.
```

ci: cache jest tests and fix flaky tests

---

src/components/DataTable/DataTableRow.js

The ability of overriding style properties makes things more flexible. In order to achieve this within DataTableRow,  we have moved paddingHorizontal out from content style which can't be overridden, and put it in container style which can be overridden with the style class property.

fix: move paddingHorizontal out from content style

---

src/components/BottomNavigation.js

fix: use "active" instead of "text" for ripple color

---

src/components/Modal.js

While the animation only last < 300ms, it is still possible for user to interact with the modal during the transition.
This is based on a fix suggested in https://github.com/facebook/react-native/issues/6732

fix: disable interaction when fading out modal

---

src/components/Dialog/DialogScrollArea.js

Add a `<Text>` in the documentation of the `Dialog.ScrollArea` to avoid errors while copying without making changes.
When copying the code and trying it in the editor, an error is returned, demanding that the "This is a scrollable area" text be wrapped in a `<Text>` component.
Although in most cases the scrollable content won't be a `<Text>` component, I think it would nice to do something to avoid the error. As an alternative, a `<View>` with a few `<Text>` inside could be added.
By fixing this, it'll avoid errors by beginners or by someone who's just copying the code and trying to check things out, avoiding the unnecessary trouble.

docs: Adding <Text> to avoid errors

---

src/components/TextInput/TextInputFlat.js
src/components/TextInput/TextInputOutlined.js

If plain styles are passed, they cannot be used to read properties of it.
n/a

fix: pass flattened styles to adjustPadding

---

src/components/TextInput/TextInputFlat.tsx

There is a warning:
```
React does not recognize the `adjustsFontSizeToFit` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `adjustsfontsizetofit` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Checking https://facebook.github.io/react-native/docs/textinput it seems there is no `adjustsFontSizeToFit` on `TextInput`.
n/a

fix: adjustsFontSizeToFit does not exist on TextInput

---

src/components/Button.tsx
src/components/Chip.tsx
src/components/TextInput/TextInput.tsx

This avoids the following in docs:
```
Default value: 'text' as 'text'
```

fix: use Partial<Props> for type of defaultProps

---

src/components/Appbar/AppbarHeader.tsx

Closes #1186
Remove "__expo" prop from Appbar.Header

fix: remove unused prop from Appbar.Header

---

src/components/Appbar/AppbarBackAction.tsx
src/components/HelperText.tsx
src/components/Menu/Menu.tsx
src/components/TextInput/types.tsx
src/types.tsx

Only recently Typescript introduced `Omit`. If you are still with a lower version you will encounter several type issues. This PR will add a local helper `$Omit`.
n/a

fix: add $Omit for lower Typescript versions

---

src/core/theming.tsx
src/index.tsx

Instead of wrapping every component that needs the theme with `withTheme`, in React 16.8+ and RN 0.59+ you can use `useTheme()` as a hook to get the theme with much less hassle.
This would close #994.
I don't believe this would break any tests.

feat: Export useTheme hook from react-theme-provider

---

src/components/Menu/Menu.tsx

The menu does only appear after half a second on iOS and Android. This fix will reduce the delay to milliseconds and was tested on all devices.
Open Menu examples.

fix: reduce delay of Menu

---

src/components/Menu/Menu.tsx

Adds animation scale from theme to animations in Menu.
Change animation scale in theme temporary to 0 and see how the Menu will pop up immediately.

fix: add animation scale to Menu

---

example/src/Examples/TextInputExample.tsx

Fixes: #1212 
Following the MD guidelines I've added character counter example.
with longer message | RTL
--- | ---

feat: add character counter to text input example

---

src/components/Button.tsx
src/components/CheckboxAndroid.tsx
src/components/CheckboxIOS.tsx
src/components/Drawer/DrawerItem.tsx
src/components/FAB/FAB.tsx
src/components/IconButton.tsx
src/components/RadioButtonAndroid.tsx
src/components/RadioButtonIOS.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/Checkbox.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/DrawerItem.test.js.snap
src/components/__tests__/__snapshots__/FAB.test.js.snap
src/components/__tests__/__snapshots__/IconButton.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap
src/components/__tests__/__snapshots__/RadioButton.test.js.snap
src/components/__tests__/__snapshots__/Searchbar.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap
src/components/__tests__/__snapshots__/ToggleButton.test.js.snap

Resolves #1188 
Passing `undefined` to `accessibilityStates` 
https://github.com/callstack/react-native-paper/blob/4fc1eb9b0e4bf418d6262d011e28fe215243aa3f/src/components/Button.tsx#L248
causes unexpecting behaviour that if you switch button or any similar component to disabled and then back to normal it loses ripple effect and a possibility to be clicked.
Problem occurs on android devices with `react-native >= 0.6`
https://facebook.github.io/react-native/docs/view#accessibilitystates
AccessibilityStates accept array of values, so if we don't want to pass anything there we should pass empty array instead of undefined

fix: touchable ripple toggling disable prop

---

src/components/Appbar/AppbarHeader.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap

There was missing usage of old color version function "light"

fix: upgrade color missing changes

---

docs/pages/2.theming.md

docs: missing link (404 Not found) of `default theme` in theming pages.
Just help for new `user` use this library (like me 🙇🏻‍♂️) can't visit theming default pages.
I've read theming from the docs here https://callstack.github.io/react-native-paper/theming.html & visit `default theme` link, but 404 not found.

docs: missing link (404) for DefaultTheme in theming pages.

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx

PR makes few things:
1. Refactor outline input label - moves components to separate folder and extract one of the component (LabelBackground)
2. Fix spacing around label in outline input when control has focus or value
3. Adjust label background when backgroundColor is passed in styles to the outline input
4. change input padding from 12 to 14 according to material guidelines [inputs](https://material.io/design/components/text-fields.html#spec)
**BEFORE**
Note: more white space on right side of the label and gray background outside the outline border
**AFTER**
Note: Equal margin of 4px on both sides of the minimized label, correct spacing and border cutoff view sized properly

refactor: change outline textinput label behaviour

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx

According to #1115 allow to style fontWeight using style prop
Currently it's affects also font of the label and I'm not sure it's behaviour that we really want
@Trancever wdyt ?
Screenshots of the text input flat and outline:

feat: handle fontWeight style-prop

---

docs/assets/styles.css
docs/pages/3.icons.mdx
docs/pages/5.react-native-web.md
docs/pages/src/components/IconsList.js

Since v3.0 is using Material Community Icons we need to update section `Icon` in the documentation.
Closes: #687
Current `Icons` section is outdated.

docs: update font section according to v3.0

---

src/components/ProgressBar.tsx

Currently, the `ProgressBar` restarts in between if any other prop than `visible` changes. This fix only starts/stops the animation if the `visible` prop has change.d
Open `ProgressBar` component in example app.

fix(ProgressBar): only start/stop animation if visible prop changes

---

src/components/TextInput/TextInput.tsx

Currently, it is not possible to pass a `ref` prop to the `TextInput`.
Use `TextInput` with `ref` prop.

fix: expose ref in text input

---

src/components/FAB/FAB.tsx

Displaying activity indicator if loading property is set to true. activity indicator was not displaying if label is not set. 
Removed condition to check for label is loading property is set true.
Pull request to address callstack#1130
Testing different combination like
Icon and Loading 
Label and Loading
No Label and Icon

fix: FAB - always display activity indicator if loading property is set to true

---

src/components/List/ListAccordion.tsx
src/components/List/ListItem.tsx

To address #1242, this PR adds optional `titleNumberOfLines` and `descriptionNumberOfLines` props to the `ListItem` and `ListAccordion` components, keeping the default values as before (1 and 2, respectively). Also, see #1096 for a related feature.
Tested `List.Section` and `List.Accordion` examples using
```
titleNumberOfLines={3}
descriptionNumberOfLines={3}
```

feat: (title|description)numberOfLines prop to ListItem and ListAccordion

---

src/components/Button.tsx
src/components/Snackbar.tsx
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

When testing with `@testing-library/react-native` I want to find buttons by text. However, `Button` component uses `toUpperCase` explicitly, so I have to upprecase all my search strings. This is annoying, especially since I use react-i18next. With this change, I can use the same string in my tests (you can see this from snapshots)
I tested it in example app visually on iOS and Android simulators and web version. Everything looks properly uppercased.

refactor: use textTransform to upperCase Button

---

babel.js
package.json

`babel.js` was removed from the `files` field in package.json. It caused fails in release builds (at least Android #1302 ).
it can be tested with the next alpha release.

chore: fix babel plugin import

---

example/src/Examples/ButtonExample.tsx
src/components/Button.tsx
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

Resolve: #1165, Resolve: #1273  and partialy #1317 
I've added optional labelStyle prop to button.
Currently, we are not able to change button text style to for example make it bold or change the font size

feat: button labelStyle

---

example/src/Examples/BannerExample.tsx
src/components/Banner.tsx
src/components/__tests__/__snapshots__/Banner.test.js.snap

I changed the banner's prop `image` to `icon` to make the component more reusable
@Trancever motivated me.
The current solution can be reviewed using an example app.

refactor: banner - icon prop instead of image

---

src/components/Appbar/AppbarHeader.tsx

Resolve #1225 
Without property elevation in wrapper style there is no shadow on android.
With elevation added to wrapper style
```
<Wrapper
style={
[
{ backgroundColor, zIndex, elevation },
shadow(elevation),
] as StyleProp<ViewStyle>
}
>
```
Additional
since we have default elevation value 
```
const {
[..]
elevation = 4,
[..]
} = StyleSheet.flatten(style) || {};
```
we don't need to check if it's present
```
elevation &&  shadow(elevation),
```
so
```
shadow(elevation),
```
isn't enough?

fix: add elevation to wrapper style

---

package.json
scripts/generate-mappings.js
src/babel/__fixtures__/rewrite-imports/output.js
src/babel/index.js

This PR changes destination of generated mappings from `dist/mappings.json` to `lib/mappings.json` and fixes mapping generation script that generated mappings with incorrect paths.
Also removes `dist` from `files` in `package.json` since dir is empty after changes.
This PR resolves #1302 
Install paper from `fix/babel-plugin` and run `cd android && ./gradlew assembleRelease` inside root of react native app

fix: paper babel plugin

---

src/components/TextInput/TextInput.tsx

Currently, the following warning is printed in console when using a `TextInput` on web:
````
TextInput: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.
````
This is because the types say there is a `ref` prop but in fact the `ref` prop cannot be accessed at runtime.
Open `TextInput` page in example project for web.

fix: omit ref in render method of TextInput

---

docs/pages/4.fonts.md
src/index.tsx
src/styles/DefaultTheme.tsx
src/styles/fonts.tsx

Updated docs for fonts configuration.
Add `configureFonts` method to be able to set fonts on certain platforms and do not override default ones.
No plan.

docs: font configuration

---

src/components/Icon.tsx
src/components/List/ListIcon.tsx

If I want to use images instead of icons in the `ListIcon` a color prop causes the image to have a tint (i.e. all the non-alpha pixels will be converted to the tint color) and thus it appears completely black on web. However, excluding the color would solve the issue:
```
left={props => {
const { color, ...rest } = props
return <List.Icon {...rest} icon={{
uri: providerType.icon || ''
}} />
}}
```
Currently, the color prop is required but this PR makes it optional.
This is just a prop type change.

fix: make ListIcon color optional

---

docs/assets/version.js
docs/component-docs.config.js
docs/pages/src/Home.js
docs/pages/src/Showcase.js

This PR implements dropdown menu in the docs that allows changing documentation version.

feat: implements dropdown menu for changing docs version.

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx

We don't like the `padding` prop in TextInput and that's why we are removing it. Instead it will be possible to pass `paddingHorizontal` via style prop.

fix(BREAKING): remove padding prop from TextInput

---

src/components/TextInput/TextInputFlat.tsx

Fix for issue:
https://github.com/callstack/react-native-paper/issues/1400
Follow instructions from issue.
Replacing `flex: 1` with `flexGrow: 1` in `<TextInputFlat/>` as it is in `<TextInputOutlined/>`.
Probably it was done by a mistake.
With new changes everything work as excepted.

fix: numberOfLines is not working in Android.

---

src/components/TextInput/TextInputFlat.tsx

Fix https://github.com/callstack/react-native-paper/issues/1404
Open `FlatTextInput` example on web.

fix: correct FlatTextInput padding on web

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx

Fix for issue:
https://github.com/callstack/react-native-paper/issues/1403
Follow instructions from issue.
Replacing check for height to determinate if text should be align top or center.
By default it should be top for multiline text inputs.

fix: Multiline aligns text to center in TextInput

---

docs/pages/1.getting-started.md

[react-native-cli](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) package by default allow us auto link any packages.
@satya164 thanks. Please review this PR 🎉 that's my first PR  🙌 
🙌Happy to contribute with your team🙌

autolinking works fine in react-native-cli || vanilla app

---

src/components/Menu/MenuItem.tsx

MenuItem Component's style type was set to `any`.
Since the style prop is used for `TouchableRipple` which takes `StyleProp<ViewStyle>`, I've modified the type of style to match that.
yarn
yarn build
yarn test
yarn lint

chore: add types for MenuItem Style

---

src/components/Portal/PortalHost.tsx
src/components/__tests__/__snapshots__/Portal.test.js.snap

I was running into this issue https://github.com/wix/react-native-navigation/issues/5579 earlier.
Turns out that wrapping my screens in a ThemeProvider wasn't allowing my touches to go thru.
This should fix the issue.

fix: allow touch events to go through in PortalHost

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx

Changes:
1. Minimizing label and placeholder logic doesn't depend now on error state, just on value and focus of the field 
2. Label has new prop `errorColor` and uses it if the field has error for the better user experience
Fixes #1387

fix: placeholder vs error behavior

---

src/components/TextInput/TextInput.tsx

All information is in: 
https://github.com/callstack/react-native-paper/pull/1440
But I don't know how to rebase, so I do another fork.

fix: fix initial label position when value is set on RN 0.61

---

src/components/Banner.tsx

The doc comment says "image", but "icon" is correct.

Fix banner doc comment

---

src/components/CheckboxAndroid.tsx

Checkbox.android now has a faster animation in accordance with the material docs https://material.io/design/motion/speed.html#duration (lowered from 200 to 100).
The animation speed is now also scaled by `theme.animation.scale`
Fixes issue #1467 
- Checkbox.android had too slow animations (200ms instead of 100ms as per material docs)
- Checkbox.android did not use theme.animation.scale for adjusting animation speed
Set `theme.animation.scale = 10` to se a really slow Checkbox.android in action

fix: animation speed for checkbox on Android

---

src/components/TextInput/TextInput.tsx

This pull request fixes the issue mentioned in [Passing TextInput props dynamically hides text input field Value #1346](https://github.com/callstack/react-native-paper/issues/1346). When TextInput is in uncontrolled mode it's text value disappears when blurred. 
- Go to `TextInputExample` component
- Remove `value` and `onChangeText` props from any text input
- Run the example 
- Type something to this input, then focus another one. The value of the blurred input should not disappear

fix: fix text input disappearing value on blur when in uncontrolled mode

---

example/src/ExampleList.tsx
example/src/Examples/RadioButtonGroupWithItemsExample.tsx
src/components/RadioButton.tsx
src/components/RadioButtonItem.tsx

This PR solves [RadioGroup clicking row with children #808](https://github.com/callstack/react-native-paper/issues/808)
Run the app. See `Radio Button Group With Items` example.

feat: add radio button group item to anable pressing the whole row

---

src/components/Modal.tsx

Dismiss with the backdrop does not work since the safeareaview is in front of it.
See here a discussion in another library where this fix is used
https://github.com/react-native-community/react-native-modal/issues/11#issuecomment-318853831

fix: support backdrop dismiss

---

src/components/ProgressBar.tsx

Closes #1499.
Check out an example app with ProgressBar.  
The app should pick up the user's RTL preference and if it's RTL fill the bar from the right. If `indeterminate` prop is set the animation starts from the right as well.

feat: add rtl support to ProgressBar

---

src/components/List/ListItem.tsx
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/components/__tests__/__snapshots__/ListSection.test.js.snap

Consider the following example from `List.Section` :
The description's container can't have `pointerEvents="none"`  in order to make the Chip component able to be pressed.
1. Download this branch
2. Open the `List.Section` example
3. Press on the chip

refactor: remove pointerEvents from ListItem description

---

src/components/Banner.tsx
src/components/FAB/FAB.tsx
src/components/FAB/FABGroup.tsx
src/components/Snackbar.tsx

Following components are using `theme.animation.scale` prop for the animations duration: 
- Header
- FAB 
- Snackbar
All changes were tested in the example app.

feat: config animation duration

---

src/components/Appbar/AppbarContent.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap

Increase accessibility of `Appbar.Content` by adding support for [Accessibilityinfo.setaccessibilityfocus](https://facebook.github.io/react-native/docs/0.48/accessibilityinfo#setaccessibilityfocus) allowing apps to focus screen readers on the `Appbar.Content` title when a screen is initially rendered.
Notes: Android requires the focused component to have `accessible` set in order to focus.
Example:
```
const FocusedHeader = () => {
const ref = useRef<Text>(null);
useEffect(() => {
const handle = findNodeHandle(ref.current);
AccessibilityInfo.setAccessibilityFocus(handle);
});
return (
<Appbar.Header>
<Appbar.Content
titleRef={ref}
title="Screen Title"
/>
</Appbar.Header>
);
};
```
`yarn flow && yarn typescript && yarn lint && yarn test`

fix: appBar Accessibility Focus

---

src/components/Drawer/DrawerItem.tsx

It's not possible to press on a `DrawerItem` using appium without passing an `accessibilityLabel` to the touchable.

feat: add accessibilityLabel to DrawerItem

---

src/components/ActivityIndicator.tsx
src/components/Badge.tsx
src/components/BottomNavigation.tsx
src/components/Button.tsx
src/components/Card/Card.tsx
src/components/Chip.tsx
src/components/HelperText.tsx
src/components/ProgressBar.tsx
src/components/RadioButton/RadioButtonAndroid.tsx
src/components/TextInput/TextInput.tsx

`this.props.theme.animation.scale` applied to the following components: 
- Button
- Card
- Chip
- HelperText
- ProgressBar
- RadioButtonAndroid
- TextInput
The animations were scaled mainly for the touch effects and fading in and -out components. This feature will be helpful for disabling all animations using one prop.

feat: use animation scale on minor animations

---

src/components/Modal.tsx

Currently, even if not `dismissable` the Modal background is clickable on web (i.e. pointer is cursor). This change disables the background view so it does not get a focus index and the cursor is the default one.
Open Modal with `dismissable={false}` on web and ensure that no pointer cursor is used on the background.

fix: disable Modal background when not dismissable

---

.github/workflows/triage.yaml

The GitHub action will comment on any issue when you add a label (currently needs more info and needs repro). This can be helpful to not have to write a descriptive message every time when asking for more details.

chore: add a GitHub action for triaging issues

---

src/components/Appbar/AppbarContent.tsx

Similar to https://github.com/callstack/react-native-paper/pull/1599 the Appbar Content is clickable on web (i.e. pointer is cursor). This change disables the touchable part so it does not get a focus index and the cursor is the default one.
Hover the Appbar Content view and you should not see a pointer cursor.

fix: disable Appbar Content when not pressable

---

example/src/Examples/RadioButtonGroupExample.tsx
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/RadioButtonItem.tsx

`RadioButton.Item`:
- fix: Label element using `./Typography/Text` instead of `react-native/Text` (to support themes).
- feat: add `labelStyle` prop.
- docs: fix link.
Screenshots from examples.

feat: RadioButton.Item add labelStyle prop & support themes

---

src/components/FAB/FAB.tsx

Explicitly mention that the `color` prop of `FAB` refers to its *text* color (and not its *background* color).

docs: clarify color prop for FAB

---

docs/package.json
docs/yarn.lock

Added missing `react-native-vector-icons` dependency to docs so build wont fail

chore: added missing react-native-vector-icons dep to docs

---

src/components/Surface.tsx

Currently, it is not possible to pass `ref` to Surfaces (i.e. also Buttons).
Use `Button`, pass `ref` to it and no typing errors should be there.

fix: expose ref type

---

src/components/Drawer/DrawerItem.tsx

Currently, it is not possible to pass ref to DrawerItem.
Use DrawerItem, pass ref to it and no typing errors should be there.

fix: expose ref on DrawerItem

---

src/components/TextInput/TextInputOutlined.tsx

I was just looking over the code and found that `containerStyle` is not been used.

refactor: remove unused variable in TextInputOutlined

---

src/components/FAB/FAB.tsx
src/components/FAB/FABGroup.tsx

Added a testID to enable testing with detox. You can now add a testID as it is done for other components to the FAB and the FAB.Group.
Additionally the you can hand in testIDs to any action provided to a FAB.Group.
Check, if the way that the testIDs of the FAB children of the FAB.Group are generated in a reasonable way (especially in respect to naming conventions)

feat: added testID to FAB and FAB.Group

---

src/components/Card/CardTitle.tsx

The title property of a card would wrap lines
The subtitle property of a card would wrap lines

feat: Multiple line for card title and subtitle

---

src/components/Searchbar.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/__snapshots__/Searchbar.test.js.snap

We need a way to add a generated accessibility label to the search and clear buttons. The copy changes based on a user's locale settings.
As long as the typescript and eslint checks pass this should be good to go.

feat(searchbar): add search and clear accessibility labels

---

src/components/Card/Card.tsx

I noticed that the Card somehow behaves strange while resizing  and keeps having the same size. It seems that `flexShrink` was missing. This style change should not have any side-effects.
n/a

fix: add flexShrink to inner Card container

---

src/components/RadioButton/RadioButtonItem.tsx

Add preliminary theming support for the RadioButtonItem label field to support Dark mode.
Closes #1587 
* Enable dark mode and view the label text (should match primary dark color)

fix(radiobuttonitem): added label theming support (#1587)

---

example/app.json
example/package.json
example/src/Examples/TextInputExample.tsx
example/yarn.lock
package.json
src/components/Badge.tsx
src/components/Chip.tsx
src/components/HelperText.tsx
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
yarn.lock

Example app should be using the latest expo whenever it's possible 
Run example app on both mobile and web

feat: upgrade example app to expo 37 and bump ts types

---

src/components/Banner.tsx
src/components/Button.tsx
src/components/Card/Card.tsx
src/components/Chip.tsx
src/components/CrossFadeIcon.tsx

We pass false in all animations just to not break users who are still on RN < 0.60. This is gonna be changed to true in 4.0 version.

fix: fix warning when animating without passing useNativeDriver

---

src/components/CheckboxAndroid.tsx

Fix useNativeDriver warning from CheckboxAndroid component. All other places are already fixed by #1796 but this one might have been forgotten.
Check whether useNativeDriver warning is going away from Checkbox component on Android.

fix: useNativeDriver warning from CheckboxAndroid component

---

src/components/Card/CardTitle.tsx

Card titles should be always **1** line. Per https://github.com/callstack/react-native-paper/pull/1576 discussion.

fix: card title with 1 line only

---

src/components/Banner.tsx
src/components/Card/Card.tsx
src/components/CheckboxAndroid.tsx
src/components/Chip.tsx
src/components/CrossFadeIcon.tsx

Running animations without explicitly passing `useNativeDriver` property on React-Native > 0.60 is causing warnings.
Run the example app and check if animations work as expected.

fix: pass useNativeDriver to all animations

---

src/components/FAB/FABGroup.tsx

Fixes #1816 
FAB in FAGBroup is clickable when group is closed/hidden. It also happens when passing `visible={false}`.
See below screen to see what is the issue (observe the pointer) :
I have passed `visible={open}` prop from FABGroup to FAB to set pointer events on fab to `none`
Also depend on `open` state I change pointerEvents in FABGroup to `box-none` or `none`. Put there `none` cause that FAB in Group is not pressable on Android.
After proposed changes it looks like below:
**Web**
**iOS**
**Android**
You can try to test after paste below code in example app in `FABExample.tsx`:
<details>
```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Colors, FAB, Portal, withTheme, Theme } from 'react-native-paper';
type Props = {
theme: Theme;
}; …
```

fix: prevent FABGroup click when its hidden

---

src/components/Menu/MenuItem.tsx

the current implementation of MenuItem does not completely follow the material spec: https://material.io/components/menus#specs
height of item should be 48, but with the current code it is not enforced, and is different.
tested locally
this PR
master branch

fix: fix menu item height

---

src/components/Snackbar.tsx
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

The PR adds a new property to the `Snackbar` in order to overwrite these styles:
https://github.com/callstack/react-native-paper/blob/54254134bd61c5bd259f47ef7ebc9f5e29e14405/src/components/Snackbar.tsx#L289-L293
n/a

fix: add wrapperStyle to Snackbar

---

src/components/RadioButton/RadioButtonAndroid.tsx

Attempts to fix #1870 by adding `useNativeDriver: false` to the `Animated.timing`s in `RadioButton.Android`.
Caveat: I wasn't able to reproduce the original issue (i.e. the yellow box triggering with the warning about `useNativeDriver`), would appreciate if @hugosbg could verify that this resolves it.

fix: add useNativeDriver: false to RadioButton.Android

---

src/components/Appbar/AppbarHeader.tsx

The header shouldn't be setting statusbar style. It won't work properly when using libraries such as React Navigation since multiple screens can be mounted at one time, and user has no way to control it or integrate it with react Navigation's lifecycle this way.
If we really want to do this, a better way is to use the `<StatusBar />` component from React Native which will make sure that the style set gets cleaned up when the component unmounts. though it still won't work with React Navigation.
In addition, it's a side-effect and shouldn't be done in render.

fix: don't set statusbar style in Appbar.Header

---

src/components/RadioButton/RadioButtonItem.tsx

In dark mode, the default color for the RadioButtonItem label is the primary color, which is very hard to read in my case, so I wanted to change the color of the label to the default text color (white in my case). But that isn't possible using the `labelStyle` prop, as the color is always overwritten to primary (and there aren't any other options).
That's how the RadioButtonItem currently looks like with a blue primary color in dark:
and that's how it looks like with this change and `labelStyle={{color: theme.colors.text}}` applied:
Maybe the color of the RadioButtonItem label should be the text color by default? The offical [screenshots of the RadioButton](https://callstack.github.io/react-native-paper/radio-button.html) also have a black label.
There shouldn't be any immediate effects, …

fix: Update RadioButtonItem, reorder label styles

---

example/src/Examples/ButtonExample.tsx
src/components/Button.tsx
src/components/__tests__/__snapshots__/Button.test.js.snap

fix: use same color and size for button text and icon

---

docs/pages/2.theming.md

Add an example for the useTheme hook
In the `Theming` page, in the `Using the theme in your own components` section ([here](https://17506-71323749-gh.circle-artifacts.com/0/docs/theming.html#using-the-theme-in-your-own-components))

docs: add useTheme example

---

src/components/TextInput/Adornment/Affix.tsx
src/components/TextInput/Adornment/Icon.tsx
src/components/TextInput/Adornment/TextInputAdornment.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx

- discussion with @jbinda whether `TextInput` should be focused in case of `IconAdornment` being pressed on

feat: make icon adornment force focus on TextInput

---

src/components/Icon.tsx

#1876
FAB was not working properly when a function was passed to the icon prop. There was no animation and the icon didn't change according to a state. 
I assume that after enabling using custom icons in FAB, sb forgot to add a new type to isValidIcon.
Before: 
After:
Reproduce the scenario in #1876

fix: fab custom icon click and animation

---

src/components/ActivityIndicator.tsx
src/components/__tests__/__snapshots__/ActivityIndicator.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap

I had an issue with the activity indicator crashing on android. Happens when there is an ActivityIndicator on the first page. The same issue as this https://github.com/callstack/react-native-paper/issues/893
I followed what the discussion said and added ```collapsable={false}``` to the Animated view. And it seemed to fix the issue.
Reproducible error on this repo https://github.com/runningdeveloper/crash-test 
I am using expo and pixel 3a emulator. 
I had to update the snapshots on activityindicator and button. Loading on the button still looks normal.
Let me know if I have done anything incorrectly.

fix: activityindictor crash on android

---

src/components/BottomNavigation.tsx
src/components/Button.tsx
src/components/Checkbox/CheckboxAndroid.tsx
src/components/Checkbox/CheckboxIOS.tsx
src/components/Chip.tsx
src/components/Drawer/DrawerItem.tsx
src/components/FAB/FAB.tsx
src/components/IconButton.tsx
src/components/RadioButton/RadioButtonAndroid.tsx
src/components/RadioButton/RadioButtonIOS.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/Checkbox/__snapshots__/Checkbox.test.js.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButton.test.js.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButtonGroup.test.js.snap
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/DrawerItem.test.js.snap
src/components/__tests__/__snapshots__/FAB.test.js.snap
src/components/__tests__/__snapshots__/IconButton.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap
src/components/__tests__/__snapshots__/Searchbar.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap
src/components/__tests__/__snapshots__/TextInput.test.js.snap
src/components/__tests__/__snapshots__/ToggleButton.test.js.snap

`accessiblityStates` is removed in `0.62` and that causing typescript errors. With this PR I'm changing paper to use new `accessibilityState` also we want to update `@types/react-native` because  `accessibilityState` wasn't exist in `0.57.61`|
Issue: #1920 
Unfortunately it's a breaking change for people using older version of react-native and we want to add it to 4.0

[4.0] change deprecated accessiblityStates to accessibilityState

---

src/components/Menu/Menu.tsx

Unmounting a Menu was causing memory leaks because the animation wasn't properly handled.
Animation invokes the completion callback with `{finished: true}`
https://reactnative.dev/docs/animated#working-with-animations

fix: memory leak in Menu hide animation

---

src/components/RadioButton/RadioButtonItem.tsx

It's not possible to press on a RadioButtonItem using appium or other testing tools without passing an accessibilityLabel to the touchable.

feat: add prop accessibilityLabel to RadioButtonItem

---

src/components/BottomNavigation.tsx

There's a bug with animating elevation on Android, so we disable scene animation by default to avoid having such glitches with default props.

fix: disable tab switching animation by default in bottom navigation

---

src/components/TouchableRipple/index.tsx

There are situations when the `touches` array is empty and thus it causes errors.
As I noticed it especially with `react-native-web@^0.13.0` I checked their code and they have a similar check:
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/hooks/usePressEvents/PressResponder.js#L548-L557
Unfortunately, I cannot provide an example that reproduces the issue but I noticed it once in a while with `react-native-web@^0.13.0`.

fix: catch empty touches

---

src/components/TextInput/TextInput.tsx

This Pr is related to [this issue](https://github.com/callstack/react-native-paper/issues/1943). 
A reproducible code can be found [here](https://github.com/callstack/react-native-paper/issues/1943#issue-623397804)
Here is list of screen shots after the change is applied to the TextInput:
Normal:
Error without focus:
Error with focus:

fix: fix the bug of overlap of placeholder and label when error is true

---

src/components/Menu/Menu.tsx

following up #2010
1. Check `accessibilityLabel` of the overlay with TalkBack
1. Check whether `onAccessibilityEscape` dismiss the menu with the escape/scrub gesture

feat(Menu): improve accessibility around dismissing

---

src/components/Appbar/AppbarBackAction.tsx
src/components/Appbar/AppbarBackIcon.tsx

Related to [this issue](https://github.com/callstack/react-native-paper/issues/2046).
[Here](https://github.com/callstack/react-native-paper/blob/4237fd6adce733a628ac553bd4ad933f8d54ffe4/src/components/Appbar/AppbarBackAction.tsx#L85) is how the icon is passed, and causing [this condition](https://github.com/callstack/react-native-paper/blob/4237fd6adce733a628ac553bd4ad933f8d54ffe4/src/components/CrossFadeIcon.tsx#L35) to fail every time and causing a re-render/rotation animation. I also decided to extract the icon to a new file/component.

fix: fix showing unwanted rotations in header back btn on state changes

---

src/components/Card/Card.tsx

On dark themes, the default mode is adaptive. This mode will change the `backgroundColor`. This property is not animatable using the nativeDriver. Upstream issue: https://github.com/facebook/react-native/issues/14178
The bug was introduced in https://github.com/callstack/react-native-paper/pull/1787
Fixes https://github.com/callstack/react-native-paper/issues/2063

fix: ensure compatible animation drive for cards

---

src/components/Menu/Menu.tsx
src/components/Modal.tsx

1. Check `accessibilityLabel` of the overlay with TalkBack
1. Check whether `onAccessibilityEscape` dismiss the modal with the escape/scrub gesture

feat(Modal): improve accessibility around dismissing

---

src/components/BottomNavigation.tsx

The labels of BottomNavigation are not centered on web, especially if the label is long, like "Notifications". This will fix it.
Before:
After:

fix: BottomNavigation center label on web

---

src/components/Dialog/Dialog.tsx

Fix #2125 
The [Dialog](https://github.com/callstack/react-native-paper/blob/master/src/components/Dialog/Dialog.tsx) component follows only the `exact` dark mode. This PR ensures the overlay if using `adaptive` mode.

fix: Dialog background color in dark adaptive mode

---

src/components/Checkbox/CheckboxAndroid.tsx
src/components/Checkbox/CheckboxIOS.tsx
src/components/__tests__/Checkbox/__snapshots__/Checkbox.test.js.snap

This PR improves the accessibility of the checkbox component using the new accessibility props of RN 0.62
2. Test whether the TalkBack(Android) or VoiceOver(iOS) are working as expected.

feat: improve checkbox accessibility

---

src/components/Card/CardTitle.tsx

Sometimes it would be useful to be able to show longer texts without truncation in card titles. 
This PR makes it possible to pass the number of title lines as a parameter.
```
<Card.Title
title="Berries that are trimmed at the end"
titleNumberOfLines={2}
/>
```

feat: Add support for multiline card title

---

src/components/FAB/FAB.tsx

Fixes #2067
Note: For backward compatibility, I kept the default for `animated` as `true`.
However, `IconButton` [uses `false` as the default](https://github.com/callstack/react-native-paper/blob/master/src/components/IconButton.tsx#L95). This feels inconsistent. 
What can we do about it?
Edit:
After trying this out, I am not fully satisfied with this solution, because I have go go to every single place where I use a <FAB> and set the `animated` prop. I will also have to remember to set it each time I use a new one. That is something easy to forget unfortunately. 
This is kinda annoying.
As I said, ideally, we should set `animated`to false by default, but this is a breaking change. 
As I understand, v4 is out of beta, so that would be for version 5?

Fix:Add animated prop to FAB

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx

Related to [this issue](https://github.com/callstack/react-native-paper/issues/1621).
`TextInput` is extending the `react-native` but the `placeholderTextColor` didn't affect. 
Should mention the fact that if user use this prop, then they should handle the cases like the colors for when the `disabled` is true, etc.
just simply passing `placeholderTextColor` prop to `TextInpu`

fix: make the placeholderTextColor work on TextInput

---

src/components/TouchableRipple/TouchableRipple.tsx

There were used incorrect fields from `nativeEvent` to calculate ripple position.
`pageX` and `pageY` returns absolute offset from the edge of the document and it cause incorrect position when the page is scrolled down.
In our case we need to take offset from the window edges and fields responsible for this are `locationX` and `locationY`.
Just add `<TouchableRipple />`  to the page at some scrolled down position.

 incorrect ripple offset

---

src/components/ToggleButton/ToggleButtonGroup.tsx

Currently, the hyperlink to Toggle Button Row is returning 404 as it points to wrong page. Fixed this link to actual ToggleButton.Row page

Fix link to Toggle button Row

---

src/components/DataTable/DataTableTitle.tsx

There currently is a rogue `</Card>` in the docs of data table title:
```
const MyComponent = () => (
<DataTable>
<DataTable.Header>
<DataTable.Title
sortDirection='descending'
>
Dessert
</DataTable.Title>
<DataTable.Title numeric>Calories</DataTable.Title>
<DataTable.Title numeric>Fat (g)</DataTable.Title>
</DataTable.Header>
</DataTable>
</Card>
);
```

docs : Remove rogue </Card> from DataTableTitle doc

---

src/components/TouchableRipple/TouchableRipple.tsx

We were trying to access `touches` on the event, but it is undefined when touchable is pressed using keyboard on web.
In such a situation we simply show ripple in the middle of the touchable.

fix: fix TouchableRipple crash when pressed with keyboard on web

---

example/src/Examples/ChipExample.tsx
src/components/Chip.tsx

It'd be nice to be able to truncate the chip text when it's too big.

feat: add ellipsizeMode prop to Chip

---

src/components/Checkbox/CheckboxItem.tsx

Currently it's not possible to override the text color using `labelStyle` prop due to the internal overriding order.

fix: allow labelStyle to override all built-in styles

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/Adornment/Icon.tsx

It would be nice being able to control whether the adornment should focus the input. 
2. Click on the eye icon in the password input and verify if the input will show the password without being focused.

feat: add prop forceTextInputFocus to icon adornment

---

example/src/Examples/ChipExample.tsx
src/components/Chip.tsx
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap

As described in #2056, the prop `onClose` it's not accessible on iOS.
1. Open the example app with both Android(TalkBack) and iOS(VoiceOver)
2. Check whether Chip is accessible or not

feat: improve chip accessibility

---

src/components/Avatar/AvatarImage.tsx

New PR for https://github.com/callstack/react-native-paper/pull/1817
It will allow you to pass any props to the `<Image>` component inside of `Avatar.Image`.
Eg: `defaultSource`, `resizeMode`, etc...

feat: Add `imageProps` to Avatar.Image

---

src/components/Chip.tsx
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap

Followup to https://github.com/callstack/react-native-paper/pull/2144
By rendering the close button absolutely we ensure that the ripple/highlight effect is displayed on the whole chip and we keep the ability to select only the close button using a screen reader.

fix: fix chip ripple/highlight effect not covering whole component.

---

src/components/TextInput/TextInputOutlined.tsx

#1648
Merge should be done after merging refactor/text-input

fix: textInput label jumps to the center

---

example/src/Examples/TextInputExample.tsx
example/utils/index.ts
src/components/TextInput/Adornment/Icon.tsx

PR resolves an issue with setting custom icon  (e.g material, font awesome)
`<TextInput
label="Email"
value={text}
onChangeText={text => setText(text)}
left={<TextInput.Icon name={() => <IconComponent />} />}
/>`
#2231

feat: change icon prop in TextInput

---

src/components/Menu/MenuItem.tsx

Current implementation of `<Menu.Item />` doesn't allow lib's user to customise maxWidth of the component (which is ok for mobile according to MD guidelines, but is kind of a blocker in the web). This PR adds `contentStyle` prop providing user na option to override the maxWidth value.
BEFORE: 
AFTER:

feat: add content style prop to Menu.Item component

---

src/core/Provider.tsx
src/core/__tests__/Provider.test.js

PR resolves issue:  automatic theme handling is being set up even though the theme prop is passed to the Provider  (#2272)
And also contains refactor Provider component to a functional with hooks.

feat: do not set Appearance module when theme prop is passed

---

example/src/Examples/FABExample.tsx
src/components/FAB/FAB.tsx
src/components/__tests__/__snapshots__/FAB.test.js.snap

Similar to the Button component, in some instances you might not want to uppercase the FAB text. This PR adds that option.
An instance of a non-uppercased FAB has been added to the example app.
1. Verify that by default, the FAB still has uppercase text
2. Verify that the FAB with `uppercase={false}` does not force uppercase

feat: add uppercase prop to FAB

---

src/components/TextInput/Adornment/Affix.tsx
src/components/__tests__/TextInput.test.js
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Fixes: #2194
This PR adds `textStyle` prop to `<TextInput.Affix>` component.
Old PR: #2195 
**Usage:**
```js
<TextInput.Affix text='lbs' textStyle={{ fontFamily: 'Custom Font', color: 'red' }} />
```

feat: add textStyle prop for Affix

---

src/components/Switch.tsx

React-native-web uses different switch color syntax from ios/android,
update the code to work with this syntax. See https://necolas.github.io/react-native-web/docs/?path=/docs/components-switch--active-thumb-color
This pull request solves that the Switch component wasn't rendered correctly in react-native-web. The color of the thumb remained the default React Native color for the switch component. This may be able to be fixed in react-native-web itself?
I already tested my branch on web, ios and android and it works correctly
Open example app, go to switches, check if switch (thumb) color is correct.

fix: switch colors incorrect on react-native-web

---

src/components/BottomNavigation.tsx

Summary
On react-native-web, bottom tabs weren't being rendered on the first click (grey screen), probably due to a issue in the way Animated is implemented on react-native-web. This is fixed by this patch by setting FAR_FAR_AWAY to 0px on web, and setting display:none, like in standard react-navigation bottom tabs.
This fixes issue #2270.
Test plan
Switch to different tab in material-bottom-tabs in example app.

fix: grey screen on first open of tab on react-native-web

---

src/components/Appbar/AppbarHeader.tsx

statusBarHeight prop is now used without default value in condition whether to use View or SafeAreaView

fix: read prop without default value in appbar header

---

src/components/FAB/FAB.tsx
src/components/FAB/FABGroup.tsx

Following up #2263. I missed this one.
1. Open the example
2. Check whether the screen reader will read the `expanded` state

feat: add accessibility state expanded to fab group

---

src/components/BottomNavigation.tsx

Replaced index.toString() by route.key, as loaded.includes needs the key string (album, library) instead of index (0, 1)
This code worked previously with my own repo, but using the new 4.3.0 release didn't work with bottom navigation. `loaded.includes` needs the key string (album, library) instead of index (0, 1), this pull changes that to be right. Somehow I missed this in my pull request https://github.com/callstack/react-native-paper/pull/2280.
`yarn example web`, open bottom navigation and switch between tabs.

fix: fix oversight in BottomNavigation

---

src/components/Button.tsx

Add onLongPress to Button. Current only onPress is supported.
onLongPress support is needed on button for version 3.0.

feat: Add OnLongPress to Button component to version 3.0

---

src/components/RadioButton/RadioButtonGroup.tsx

Overloading of `value` in the original example makes it hard for newcomers to truly understand what is happening in this code.
Should work with whatever existing testing there is for this example.

Clearer example code

---

src/components/Checkbox/CheckboxAndroid.tsx
src/components/RadioButton/RadioButtonAndroid.tsx

Currently, whenever the `Checkbox.Android` is rendered there is a very short animation that is irritating and not necessary.
1. Check any `Checkbox.Android` and see if there is an initial animation (even easier if you set the animation scale in theme to a high number).

fix: avoid initial animation in (Checkbox|RadioButton).Android

---

docs/pages/6.recommended-libraries.md

It has been build for react-native-paper
The library is tested on all platforms (iOS, Android, web)

Add react-native-paper-dates to recommended libraries

---

src/components/MaterialCommunityIcon.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/Checkbox/__snapshots__/Checkbox.test.js.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButton.test.js.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButtonGroup.test.js.snap
src/components/__tests__/__snapshots__/Avatar.test.js.snap
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/DrawerItem.test.js.snap
src/components/__tests__/__snapshots__/FAB.test.js.snap
src/components/__tests__/__snapshots__/IconButton.test.js.snap
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/components/__tests__/__snapshots__/ListSection.test.js.snap
src/components/__tests__/__snapshots__/Searchbar.test.js.snap
src/components/__tests__/__snapshots__/TextInput.test.js.snap
src/components/__tests__/__snapshots__/ToggleButton.test.js.snap

Currently, the icon is slightly shifted to the bottom on web because there is no line height. In this example the size is 24 but the actual height of the rendered icon element is 28:
If we pass a line height as well the height of the icon element will be 24 (as expected):
1. Check if icon (for example in Appbar) is not shifted to the bottom anymore

fix: set line height to Icon

---

docs/pages/1.getting-started.md

Added terminal command in docs to install react-native-paper using npm. This was missing in Getting Started page. This can help users who are using npm.
Only Yarn command was present in Getting Started page. This could be helpful for users using npm to install dependencies.
This change is made in docs. Preview looks fine.

docs: added installation using npm command

---

src/components/TextInput/TextInput.tsx

Recently I noticed that the component `TextInput` is hiding the placeholder as in the gif below when you change the prop error from false to true. I don't think this makes sense since the placeholder is shown after focusing it again.
Snack
https://snack.expo.io/@bruno.castro/paper-textinput-bug
How to reproduce:
1. Click on the textinput
2. Click on the button `Add error` while the input is focused
Following up #1943 and #2032 I didn't have any problems regarding overlapping the label and the placeholder.

fix: keep TextInput placeholder when error is true

---

src/components/TextInput/TextInput.tsx

When trying to blur and set a TextInput as disabled at the same time, the blur does not take effect.
Example use case:
- Form of TextInputs (and other inputs) where fields have their `disabled` prop set to true while submitting
- While a TextInput is focused, user clicks a submit button that sets the above mentioned prop to loading
Expected: The TextInput is blurred
Actual: The TextInput is not properly blurred and left in a semi-focused state (no keyboard and greyed out, but but showing thicker underline)
See https://snack.expo.io/r8Cpj71On for iOS/Android
1. Having the first TextInput focused when clicking the button works fine
2. Focusing the second TextInput and clicking the button leaves the TextInput with a thicker underline as it is still in focused state
This PR fixes this by …

fix: allow bluring of disabled field

---

example/src/ExampleList.tsx
example/src/Examples/CheckboxItemExample.tsx
src/components/Checkbox/CheckboxItem.tsx
src/components/__tests__/Checkbox/CheckboxItem.test.js
src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.js.snap

This makes it so developers are able to specify which checkbox component should be used for `Checkbox.Item`.
My main motivation for this was that, at least for a single checkbox, the iOS checkbox is very difficult to tell there's a thing to check.

feat: let users choose checkbox for Checkbox.Item

---

example/src/ExampleList.tsx
example/src/Examples/RadioButtonItemExample.tsx
src/components/RadioButton/RadioButtonItem.tsx
src/components/__tests__/RadioButton/RadioButtonItem.test.js
src/components/__tests__/RadioButton/__snapshots__/RadioButtonItem.test.js.snap

feat: add mode to radio button

---

example/src/Examples/ButtonExample.tsx
src/components/Button.tsx
src/components/__tests__/Button.test.js
src/components/__tests__/__snapshots__/Button.test.js.snap

Similar to #1370 this adds the ability to put an icon on the right side of buttons. Credit to the author of that PR, I used similar approach but without breaking current functionality for the `icon` prop.
See Button in Example app with icon on the right side.

feat: button right side icon

---

src/components/DataTable/DataTableCell.tsx

The documentation was not clear about multiline support. As mentioned in #2381, the best option is to use `View` instead to keep the library MD compliant.  This PR adds that suggestion into the current docs for ` Datatable.Cell`.
Check the updated documentation in Datatable.Cell

docs: adding documentation for multiline support in Datatable.Cell

---

docs/pages/2.theming.md

In the theming section of the documentation it states that if you don't use a custom theme, then animations will be turned on and off based on device settings.
The same is true for toggling of dark theme based on device settings, react-native-paper does it for the default theme but not if you use a custom theme. It didn't mention this anywhere in the documentation so I added it to the dark theme section

docs: explain how to change theme based on device settings

---

docs/pages/1.getting-started.md

There is no information in documentation that ```MaterialCommunityIcons``` are required for some components to be displayed correctly.
For example ```AppBar.BackAction``` uses ```arrow-left``` from this icon pack.
If user specifies in config what icon packs they want to bundle, it may break display of these icons.

Add info about required icon packs

---

docs/pages/8.theming-with-react-navigation.md

The documentation names the theme setter function as `setTheme` in the context but used `toggleTheme`instead. This replaces `setTheme` in the [Create Context section](https://callstack.github.io/react-native-paper/theming-with-react-navigation.html#creating-context) to `toggleTheme`. 
Check the Create Context section on [Theming with React Navigation](https://callstack.github.io/react-native-paper/theming-with-react-navigation.html) page.

docs: Fix incorrect function name in theming with RN Navigation

---

src/components/List/ListIcon.tsx

Current example does not wrap multiple elements in container component.
Thus it does not work on Snack out of the box.
I added ```React.Fragment``` to fix it.
This is a documentation update.

Fix example in List.Icon

---

docs/pages/5.react-native-web.md
package.json
src/components/BottomNavigation.tsx
src/components/Modal.tsx
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
yarn.lock

fix: replace safe-area-view with iphonex-helper

---

.github/workflows/publish-each-pr.yml
.github/workflows/publish.yml
.yarnrc
CONTRIBUTING.md
example/README.md
scripts/bootstrap.js

Currently we need to run 'yarn bootstrap' to setup the repo. However it's easy to forget. This PR overrides the Yarn command to run the 'bootstrap' script if no arguments are specified.

chore: add a custom yarn script to make setup easier

---

src/components/DataTable/DataTableTitle.tsx
src/components/__tests__/__snapshots__/DataTable.test.js.snap

Fix related to [issue](https://github.com/callstack/react-native-paper/issues/2417).
According to Material design guidelines: `The downward arrow shows that the schedule column is sorted in descending order.`
Currently `sortDirection` prop in `DataTableTitle` set to `descending` was making the arrow to point up instead of down. Documentation is showing correct behaviour but the code was doing the opposite.

fix: Changed sorting arrow direction in data table

---

docs/pages/4.fonts.md

Currently, it's not clear that users must explicitly include in `fontConfig` overrides for `ios`, `android`, and `web` as part of their custom fonts. As such, this PR is to update the font import instructions documentation and the corresponding code example. 
See issue #2317 for more information.
Check the [Configuring fonts in ThemeProvider](https://callstack.github.io/react-native-paper/fonts.html) page.

Update documentation on custom font imports

---

src/components/Checkbox/CheckboxItem.tsx
src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.js.snap

I noticed there is an inconsistency between the `RadioButton.Item` and `Checkbox.Item` components.
Radio is using `colors.text` for its label, however, checkbox is using `colors.primary`.
This PR attempts to fix that by also using `colors.text` for the `Checkbox.Item` component.
Snacks from the doc for quick preview of the issue:
- [Radio](https://snack.expo.io/?name=RadioButton.Item&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fradio-button-item.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20RadioButton%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20React.useState(%27first%27)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CRadioButton.Group%20onVal …

fix: Use text color for Checkbox.Item label

---

src/components/Card/CardCover.tsx
src/components/TextInput/TextInput.tsx
src/components/TouchableRipple/TouchableRipple.tsx
src/components/Typography/AnimatedText.tsx
src/components/Typography/Text.tsx

Based on the reported issue https://github.com/callstack/react-native-paper/issues/2331, there are some broken Link with react-native documentation URL. And, that does not take in account the anchor (#) element in the URL.
Check the updated documentation

fix: broken link react-native URL docs with anchor

---

src/components/Badge.tsx

Similar to #2349, the component Badge is also animating in the first render.
2. Check if the component Badge is working properly.

fix(Badge): avoid initial animation

---

src/components/List/ListAccordion.tsx

Summary
As List.Accordion uses TouchableRipple for onPress handling amongst other things it would be great to offer onLongPress support, too. Since TouchableRipple already offers onLongPress support, the function can simply be forwarded.
No additional handling as for the onPress event (expandable) is required since the onLongPress functionality should not interfere with the default behaviour of List.Accordion, but simply add more press event capabilities.

feat: add onLongPress event to List.Accordion

---

src/components/Button.tsx

In my current project I have a very specific business requirement: in a web version of application few buttons need to be taken out of keyboard navigation flow (using tab key) while at the same time still being clickable by mouse. Using `disabled` prop will obviously break second part of the requirement so I've investigated a little how other accessibility-related props do work in react-native-web and it turned out that `accessible` prop is exactly what I'm looking for. Unfortunately in Paper's `<Button />` component `accessible` prop is passed to the wrapping `<Surface />` component, not the `<TouchableRipple />` which is then rendering `<TouchableWithoutFeedback />`. That is making `accessible` prop have no effect.
This PR is fixing that issue but for some reason some of the library …

fix: allow setting accessibility prop for Button component

---

src/components/Modal.tsx

This prop is necessary when you need to see content in full screen on iPhone X/11
1. Download this branch
2. Open Modal example
3. Pass style prop with this values (iPhone X/11):
```js
{ marginTop: 0, marginBottom: 0 }
```

feat: add style prop in Modal

---

docs/pages/6.recommended-libraries.md

gorhom/react-native-bottom-sheet is really smooth and react-native-paper-tabs has great integration with React Native Paper and fully implements the Material Design Spec + great web support (no dependencies on web)
https://www.reactnativepapertabs.com/
https://github.com/web-ridge/react-native-paper-tabs
https://github.com/gorhom/react-native-bottom-sheet

docs: add react-native-paper-tabs + react-native-bottom-sheet

---

.github/workflows/publish.yml

Currently, publishing an example app on merge to main doesn't work cause wrong credentials are used in the GitHub action.
Merge the PR and check if the app is published successfully..

fix: use correct credentials for publishing example app on merge to main

---

example/src/Examples/ChipExample.tsx

The first Chip in the "flat" example is actually outlined instead of flat. This PR fixes that :) 
Before:
After:

chore: fix flat Chip example

---

src/components/TouchableRipple/TouchableRipple.tsx

While I was working on client's app code I've come to a realisation that in every place where Paper's `<TouchableRipple />` component was used we needed to pass additional style to ensure pointer cursor on the web. After some digging I've found that it's caused because TouchabeRipple is using `<TouchableWithoutFeedback />` under the hood and based on this: https://github.com/necolas/react-native-web/issues/1847#issuecomment-747625960 that's exactly what's causing react-native-web to NOT "inject" `cursor: 'pointer'` style on the web.
In the example app:

feat: set default cursor for TouchableRipple to 'pointer'

---

src/components/BottomNavigation.tsx
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

Originally, when using TalkBack to read through the bottom nav, it would tell me a tab was selected, even when it was not. This PR fixes that, and matches the older behavior that is still in place with `accessibilityTraits`
Open app that utilized bottom nav, turn on screenreader (I'm using TalkBack on Android to test)

fix(BottomNavigation): selected state now reads properly on voiceover

---

src/components/Badge.tsx

Thanks all contributors!
I found inconsistency between type definition and implementation.
Default value `true` is given for `visible` prop of Badge. But `visible` is defined as mandatory. This prop can be optional.

fix: define a prop as optional

---

src/components/List/ListSection.tsx

List.Section tries to render empty string without `Text` when `""` is passed to `title` prop and causes an error:
Render this:
```
<List.Section title="" />
```

fix: do not render empty string as section title

---

src/components/BottomNavigation.tsx

The package `react-navigation-material-bottom-tabs` have a new GitHub repository link ([source](https://github.com/react-navigation/material-bottom-tabs/blob/master/README.md)) and I am updating the reference about it in the `BottomNavigation` component page.
"To preview the generated documentation, run `yarn docs start` in the project root."

docs: update a package's link

---

example/src/Examples/DataTableExample.tsx

Noticed this while I was attempting to create a table using this as my example to reference. You are flooring the page numbers, which is wrong. Changing this to round up using `.round` instead would give you the desired usage.

Fix: Pagination Datatable example

---

src/components/ToggleButton/ToggleButton.tsx
src/components/ToggleButton/ToggleButtonGroup.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/2578
Correct types in `ToggleButton.Group` where the value can be `null` e.g. when neither option is selected.
CI should pass.

fix: correct toggle button type

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/2598
That PR is removing the outline from web text input which is overlapping with component border. 
**NOTE**: we are providing the visual indicator/effect when input if focused, so there is no regression in terms of accessibility.
1. Use text input on the web
2. Focus the text input
3. Expect there is additional `outline`
before | after
--- | ---

fix: remove additional outline from web inputs

---

src/components/List/ListAccordion.tsx
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/2643
PR introduces prop `borderless` to `ListAccordion`. Since component accepts prop style and borderRadius can be defined within we should support `borderless` prop as well
android | ios | web
--- | --- | ---

fix: add prop borderless to ListAccordion component

---

src/components/DataTable/DataTableRow.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/2634
That PR introduces a prop called `pointerEvents` which allows user to specify its value for the `View` container which is wrapping the children within `TouchableRipple` in `DataTableRow` component.
1. Run the example locally on the web
2. Modify current `DataTableExample` e.g.  in the following way (basically specify `pointerEvents` value and add `onPress`):
```
...
<DataTable.Row 
key={item.key} 
onPress={() => console.log('table row pressed')
pointerEvents="none"
>
```
3. Expect onPress is fired on the web

feat: pass pointerEvents to the `DataTableRow` view container

---

src/components/Menu/MenuItem.tsx

The only thing this does is that it changes MenuItem to be a fn component. I replaced withTheme() by useTheme() too
You're probably wondering why I did this, well, it's nicer this way, and secondly, I maintain something like a copy of this in another project, where I changed it into a fn component and I'd like the two implementations to stay similar.
Tested with the example app on ios simulator and android device, all is good.
Thank you!

chore: change MenuItem to function component

---

src/components/Snackbar.tsx

With this feature you can pass Button props to action, for example, style, testID, icon, etc.
1. Download this branch
2. Create Snackbar
3. Pass other props to action

feat: add Button props to Snackbar action

---

src/components/Searchbar.tsx

Closes #2393; Closes #2394
For some reason, returning the reference to underlying method raises `dispatchCommand was called with a ref that isn't a native component` error and doesn't actually focus the input.
Returning new proxy method works as expected (and allows us to remove @ts-ignore too).
Not sure about testing, just wanted to get things moving.

fix: Searchbar focus()

---

src/components/List/ListAccordion.tsx

This pull request addresses issue https://github.com/callstack/react-native-paper/issues/2150. It gives users the flexibility to replace what's rendered on the right-hand-side of the accordion with their own component. The expanded state is passed back to the user so that they can render based on this value.
This feature draws inspiration from the `left` prop on the same component. Instead, this could have been addressed similarly to how Fab Icon is implemented, however the drawback is that the implementation of Fab Icon is a bit more complex when compared to the `left` prop of this component.
Render a `List.Accordion` component and pass in a separate component as the `right` prop. E.g.
Omitting this prop results in the default `MaterialCommunityIcon` element being rendered.

feat: add prop right to List Accordion

---

example/src/ExampleList.tsx

That PR corrects background color on example list.
1. Open example app
2. Switch mode to `dark`
3. Expect example list has correct bg color when bounces
before | after
--- | ---

fix: correct example list background color

---

example/package.json
example/src/index.tsx
example/yarn.lock
src/constants.expo.tsx
src/constants.tsx

We're removing the .expo extension in SDK 41. In the future we should move towards using react-native-safe-area-context to accurately determine the insets rather than estimating, but that will require a major version bump, so I discussed this with @satya164 that the solution in this PR should be fine until then.
I also updated the expo-cli version in the example project and swapped from react-native's `StatusBar` component to expo-status-bar, because its defaults work better in this context (eg: assumes translucent status bar). 
I ran the example project and verified that it works as expected:

chore: remove constants.expo.tsx and move logic to constants.tsx

---

src/components/Checkbox/CheckboxItem.tsx
src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/2542
`flexShrink` on mobile defaults to `0` that's why we need to specify it separately with the value `1`.
It corrects the behavior with missing label in some cases.

fix: correct flex values in checkbox item label

---

src/components/Card/CardCover.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/2538
That PR _unblocks_ the ability to pass the resizeMode to `CardCover`, which was basically not possible before because of no option to override the `resizeMode` value defined in styles.
1. Add `CardCover` with the image source
2. Specify different `resizeMode`
`cover` (default) | `stretch`
--- | ---

fix: remove resizeMode style property from CardCover

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/Adornment/TextInputIcon.tsx

This PR adds a new prop `color` to the component `TextInputIcon`. It accepts whether a function or a string, making it easier to change the icon color when the input is focused as in the MD example below.
Check the example app

feat: add prop color to TextInputIcon

---

src/components/BottomNavigation.tsx

Prevent scene blink fix desynchronization between opacity & top
Sometimes the top property is too far and the opacity = 0 so the screen flash.
Fix screen flash / blink when switching tabs.
https://github.com/react-navigation/react-navigation/issues/9256
Switch between tabs.

fix: component BottomNavigation

---

src/components/TextInput/Label/LabelBackground.tsx

Fix the regression introduced in: https://github.com/callstack/react-native-paper/pull/2672
before | after
--- | ---
1. Set in theme `roundess: 25`
2. Focus outlined text input with label
Expect: there are no bug related to bottom border

fix: patch for text input label

---

src/components/RadioButton/RadioButtonItem.tsx
src/components/__tests__/RadioButton/__snapshots__/RadioButtonItem.test.js.snap

Closes #2688
An issue where Checkbox.Item labels were invisible #2542.  Is also the same issue for 
RadioButtonItem labels.  The following fix was for Checkbox.Item labels being invisible was merged with this pull request https://github.com/callstack/react-native-paper/pull/2659.
This PR is the same fix for RadioButtonItem 
1. create a project using radio button items with a label prop
2. replace the `react-native-paper` version number in your package.json with my fork and branch:
`"react-native-paper": "git://github.com/conor909/react-native-paper.git#2659-radio-button-label-fix"`
3. then run `yarn` / `npm install`
4. The labels should now be showing for RadioButtonItems:

RadioButtonItem label fix

---

src/components/Card/Card.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/2656
That PR fixing the issue with missing animation when `onLongPress` is called.
1. Scan the QR code
2. Run the app and open Card example
3. Scroll to the last example
4. Long press the card and observe the shadow animation

fix: run animation on card long press

---

src/components/Snackbar.tsx

Sometimes we need to import the props definition. It is available for TextInput (https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/TextInput.tsx#L21) but not for the Snackbar.
This very basic change renames the Snackbar props type to `SnackbarProps` and exports it.
```js
import {SnackbarProps} from 'react-native-paper/lib/typescript/components/Snackbar'
// use it
```
Thank you for your library 👍🏻

chore: Expose Snackbar props type

---

example/src/DrawerItems.tsx
src/components/Drawer/DrawerItem.tsx
src/components/__tests__/__snapshots__/DrawerItem.test.js.snap

It would be nice to be able to render a badge or chip in the Drawer.Item
1. Open the example app and see the Drawer.Item using a badge

feat: add prop right to DrawerItem

---

example/src/Examples/CardExample.tsx
package.json
src/components/Card/Card.tsx
src/components/__tests__/Card/Card.test.js
src/components/__tests__/Card/__snapshots__/Card.test.js.snap
yarn.lock

Implement MD outlined card.
https://material.io/components/cards
Elevated | Outlined
--- | ---
Elevated | Outlined
--- | ---
2. Check the example showing an outlined card

feat: add card mode outlined

---

src/components/Button.tsx

It has a bug that Button elevation is still zero after mode is changed to `contained` from other modes.
This PR fixes this.
1. Render a Button with mode other than `contained`.
2. Change the mode to `contained` mode dynamically(e.g. on button press).
3. Check elevation

fix: correct Button elevation

---

src/styles/shadow.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/2733
Fixes the shadow which remains even if the elevation was set to 0.
1. Run the app
2. Set `elevation={0}` on Card component
**3. Expect there is no shadow**

fix: interpolate shadowOpacity to correct its value for the elevation equal zero

---

example/src/Examples/RadioButtonItemExample.tsx
src/components/RadioButton/RadioButtonItem.tsx
src/components/__tests__/RadioButton/RadioButtonItem.test.js
src/components/__tests__/RadioButton/__snapshots__/RadioButtonItem.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/2704
This PR extends `RadioButton.Item` component and introduces new prop to define radio button control position - `leading/trailing`
ltr | rtl
--- | ---
ltr | rtl
--- | ---

feat: introduce prop for defining control position (leading/trailing) fo RadioButton.Item

---

src/components/List/ListAccordion.tsx
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/2683
It turns out there is need to wrap `TouchableRipple` within `View` with specified background color to prevent ripple effect from spreading outside the component area. 
NOTE: the similar approach is applied in Button component, however `Surface` component is used there, which we don't need there. 
1. Run the example app on Android 7
2. Go to list component
3. Press the list item and observe the ripple

fix: add bg color to list accordion to limit ripple area

---

src/components/Drawer/DrawerItem.tsx
src/components/__tests__/__snapshots__/DrawerItem.test.js.snap

Fixes Drawer.Item content not being center aligned
Prior to change:
After change:

fix: Drawer.Item content not center aligned

---

src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/helpers.tsx

When using a `TextInput` in `outlined` mode text can be cut on some device, especially on Android.
This is due to the fact that `adjustPaddingOut` is only based on `fontSize`, and even if you pass `lineHeight` in the style to avoid this, this one is not used.
So, to prevent this issue `adjustPaddingOut` is now based on `lineHeight` when this one is provided.
Before:
After:

fix!: fix TextInput paddingOut not based on lineHeight when provided

---

src/components/List/ListAccordion.tsx

Currently List.Accordion onLongPress prop has a type `() => void`.   List.Accordion pasess this to TouchableRipple in which the type of onLongPress is `(e: GestureResponderEvent) => void`.  When using the List.Accordion component it does passes GestureResponderEvent  but since the type does not have any parameters defined the linter complains about it. List.Item uses the same type as TouchableRipple.
The GestureResponderEvent could be used to correclty locate a contextual menu over the Accordion which will be a diferent callback from onPress (expand)
Currently this works, is just the linter since it passes the prop but the linter complains about it.
Passes  type-check, lint and tests. Reviewed Docs as well.

fix: list.accordion onlongpress type

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx

Following up #2678. `useTheme` doesn't work in the component `LabelBackground` when you pass a custom theme to the TextInput as in the example below:
```js
<TextInput
mode="outlined"
label="Test"
theme={{
roundness: 25,
}}
underlineColor="red"
value="custom rounded input"
/>
```
The solution was to pass the prop `roundness` along under the `labelProps`
Before | After
--- | ---
1. Check it out in the example app

fix: TextInput border being cut out

---

src/components/TextInput/helpers.tsx
src/components/__tests__/TextInput.test.js
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Fixes issue [2740](https://github.com/callstack/react-native-paper/issues/2740). The issue happens to be when we calculate the adjustPaddingOut. 
The change is to not return the centering paddingTop, and paddingBottom in case it is multiline.

fix: outlined TexInput adjustPaddingOut (#2740)

---

src/components/List/ListAccordion.tsx
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap

1. Add prop `accessibilityLabel` to ListAccordion
2. Pass the key `expanded` under `accessibilityState`  to the `TouchableRipple`
1. Test it using TalkBack or VoiceOver

feat: improve ListAccordion accessibility

---

src/components/Chip.tsx
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap

Resolve #2804. 
Testing the web version I also realized that in larger resolutions the touchable was not filling all available space. I fixed that as well.
Before Web | Before Mobile
--- | ---
Web | Mobile
--- | ---

fix: full width Chip touchable not focusing

---

src/components/Card/CardTitle.tsx

I just realized that in the Card.Title paddingRight was missing. So the title was a little bit off when centered.
Before | After
--- | ---

fix: add missing padding to CardTitle

---

.github/workflows/stale.yml

We should not automatically close pull requests or issues where people made an effort to provide a repro.

chore: mark issues with no repro/response as stale

---

src/components/DataTable/DataTableRow.tsx

Missing DataTable Row displayName attribute is causing the page to appear at a wrong level in the hierarchy of the documentation (child of root, not child of DataTable). I assume setting this attribute to "DataTable.Row" will fix the hierarchy issue, as this is the only difference vs. the other DataTable pages.
[DataTable.Row page in question](https://callstack.github.io/react-native-paper/data-table-row.html)

fix: Add displayName attribute to DataTable Row to fix documentation hierarchy

---

src/components/DataTable/DataTableRow.tsx

Add displayName attribute to DataTable Row to fix documentation hierarchy in the documentation.
This is a republish of #2869, pointing to the correct main branch.

fix: Add displayName attribute to DataTable Row

---

docs/pages/9.react-navigation.md

The docs page [Integrate AppBar with react-navigation](https://callstack.github.io/react-native-paper/integrate-app-bar-with-react-navigation.html#adding-appbar) describes using the `previous` prop to detect if a back button should be shown. This is correct for React Navigation 5.x as described here: <https://reactnavigation.org/docs/5.x/stack-navigator/#header>
But in React Navigation 6.x, there is no longer a `previous` prop; instead, there is a `back` prop, as described here: <https://reactnavigation.org/docs/stack-navigator/#header>
As a result, when using React Navigation 6.x with the current instructions, the back button never appears. If you switch to using the `back` prop, the back button starts working again. Repro: <https://github.com/CodingItWrong/rn-paper-navigation>
This PR …

Docs: React Navigation Integration - update previous prop to back for 6.x

---

src/components/TextInput/TextInput.tsx

This PR is a proposal to run animations using the native driver on the iOS platform. It's a little laggy in old devices such as an iPhone 5s  when you have some inputs in a form. It's noticeable in the example app as well.
This was removed in this issue #941 demoed in this snack https://snack.expo.io/ryoVI7WuV
However, I couldn't reproduce this issue anymore either in the snack or on a phone (iPhone 5s). Maybe it was fixed in the newer versions of react-native?
1. Open the example app and goes to the TextInput section
2. Check if the label animations are running smoothly
3. Try to reproduce the problem reported in issue  #941

chore(TextInput): run animations using native driver on iOS

---

example/package.json
example/yarn.lock

While working on #2951, I noticed that we have babel presets that do not seem to be used anymore in the example app. This PR removes it to cleanup project.
This is a maintenance cleanup.
Pipelines are passing and project works and builds correctly.

chore: remove unused babel presets

---

package.json
yarn.lock

Fixes https://github.com/callstack/react-native-paper/issues/2929 - the compiled lib/typescript files include the prop keys and hasTVPreferredFocus & tvParallaxProperties have been removed from the TouchableWithoutFeedback props

chore: update @types/react-native

---

src/components/FAB/FABGroup.tsx

This PR adds properties for the FAB.Group actions to allow for custom styling of the FAB.Group labels.
Provide `labelTextColor` and `labelStyle` properties in the FAB.Group's `actions` array.

feat: Styling of labels in FAB.Group

---

example/src/Examples/ChipExample.tsx
src/components/Chip.tsx
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/2972, https://github.com/callstack/react-native-paper/issues/2959
Setting the `flexGrow` to `Touchable` within `Chip`
Android | ios | web
-- | -- | --
at the same time it's not breaking the previous issue: https://github.com/callstack/react-native-paper/issues/2804
Android | ios | web
-- | -- | --
Run the code below from one of the issues and **expect** Chips are displayed properly:
```javascript
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Chip, List } from 'react-native-paper';
const ChipExample = () => {
return (
<>
<List.Section title="Flat chip">
<View style={styles.row}>
<Chip selected onPress={() => { }} style={styles.chip}>
Simple 1
</Chip>
<Chip selected onPress={() => { }} …
```

fix: correct Chip touchable style

---

example/src/Examples/TextInputExample.tsx
example/utils/index.ts
src/components/TextInput/Label/LabelBackground.tsx
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Fixes: #2954 
PR adding a `maxWidth` for the `label` to correct the spacings after truncating and avoid displaying border.
Android | iOS | web
| - | - | - |
> 
1. Open the app
2. Go to TextInput example
3. Scroll to the example: `Outlined with super long label which is truncating at some point`
4. Expect there is no border

fix: correct long label in outlined text input

---

src/components/TextInput/TextInputOutlined.tsx
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/2935
PR moves the outline outside of `TextInput`, so then it's not affected by input's padding. 
ios | android | web
--- | --- | --- 
1. To one of TextInput example with `mode="outlined"` add to styles some `paddingRight` or use the following snippet:
```
<TextInput
label="Email"
placeholder="Email"
value={text}
multiline={false}
mode="outlined"
onChangeText={(text) => setText(text)}
style={{ backgroundColor: 'aquamarine', paddingRight: 120 }}
/>
```
2. Type some text
3. Expect padding is adjusted properly

fix: move outline outside of input view container

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3003
Setting a height of the masking label spacing.
1. Run the app
2. Type something in outlined input
3. Expect the whole text is displayed properly

fix: correct displaying text in outlined text input

---

src/components/TextInput/TextInputFlat.tsx

This PR fixes issue #3020 , to ensure that the label in TextinputFlat aligns with the backgroundColor of the TextInput AND to not show the label if there is no label specified for the textInput.
See issue, @lukewalczak ran tests and advised on this PR.

fix: fixed backgroundColor of textinput label #3020

---

src/components/Menu/Menu.tsx
src/components/Modal.tsx
src/core/Provider.tsx
src/utils/__tests__/addEventListener.js
src/utils/addEventListener.tsx

PR corrects behavior related to adding and removing listeners in couple components.
Fixes: https://github.com/callstack/react-native-paper/issues/2984
Fixes: https://github.com/callstack/react-native-paper/issues/3023
CI should be green

refactor: create an util for handling event handlers

---

src/components/Modal.tsx

If a modal is getting unmounted and the visible prop is not changed to false beforehand, the hardwareBackPress listener is not getting removed.
This bug was introduced in version 3.10.0, when the change to the functional component happened (#2557). 
1. Show the modal
2. Unmount component
3. The hardwareBackPress is still listening, you can add another hardwareBackPress listener in your parent component to see if it is getting called.

fix: cleanup modal backhandler listener on unmount

---

example/src/Examples/CardExample.tsx
example/src/index.tsx
src/components/Card/Card.tsx

Refreshing the [PR](https://github.com/callstack/react-native-paper/pull/2113) made by @PedroBern fixing the `Card` issue: https://github.com/callstack/react-native-paper/issues/3009
2. Go to card examples
3. Scroll to card which switching the theme on pressing it
4. Press it
5. Expect: app mustn't crash

fix: correct Card animation drivers related to elevation

---

src/components/Avatar/AvatarImage.tsx
src/components/__tests__/Avatar.test.js
src/components/__tests__/__snapshots__/Avatar.test.js.snap

This PR adds necessary event listeners that was missing in `Avatar.Image`.
_Generally I was trying to add all props of standard React Native Image component but then thought that they are unnecessary for Avatar Image. If you guys prefer that then I can make a PR for that too_
_I was confused if I should make one `listener` prop or add them separately for each of them and decided to make one prop, If this is also not recommended then I will update_

feat: add event listeners for Avatar.Image

---

example/app.json
example/src/DrawerItems.tsx
example/src/index.tsx
example/utils/index.ts
package.json
yarn.lock

PR moves back example web support after expo update:
* adds web to  supported platforms in `app.json`
* adds `babel-loader` to devDependencies
* make using expo updates conditionally only for mobile platforms
1. go to example
2. `yarn start`
3. choose web platform
4. expect web example is working properly

chore: web example support

---

example/src/Examples/BottomNavigationExample.tsx
src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/BottomNavigation.test.js
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3099
PR introduces new prop for `BottomNavigation` called `labelMaxFontSizeMultiplier` which specifies the largest possible scale a label font can reach in the similar way as rn text prop [maxFontSizeMultipliers](https://reactnative.dev/docs/text#maxfontsizemultiplier)
before | after - `labelMaxFontSizeMultiplier={2}` | after - `labelMaxFontSizeMultiplier={1}`
--- | --- | ---

feat: introduce new prop labelMaxFontSizeMultiplier for BottomNavigation

---

src/components/DataTable/DataTableCell.tsx
src/components/DataTable/DataTableTitle.tsx

```
DataTable.Title add new props for text style (prop name: textStyle)
DataTable.Cell add new props for text style (prop name: textStyle)
Now users can add change color easily if they need.
```
<-- What existing problem does the pull request solve? Can you solve the issue with a different approach? -->
```
I was facing a problem in Table and cell I don't find any color props for color change so that is why I added some changes and make a pr for this.
```

feat: TextStyle Props Add in Table and Cell

---

example/src/Examples/CheckboxItemExample.tsx
src/components/Checkbox/CheckboxItem.tsx
src/components/__tests__/Checkbox/CheckboxItem.test.js
src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.js.snap

fix(CheckboxItem): properly disable touchable

---

docs/pages/5.react-native-web.md

file-loader is deprecated in Webpack 5 and outputs loader files as JS modules
Using the new Webpack 5 [asset modules](https://webpack.js.org/guides/asset-modules/) feature did the trick

Fix: Updated documentation for Webpack 5

---

src/components/DataTable/DataTableTitle.tsx
src/components/__tests__/__snapshots__/DataTable.test.js.snap

Thanks for react-native-paper you all, it's fantastic.
The DataTable.Title component takes a numberOfLines prop
However, the internal / wrapped Text component has a style applied with height *and* lineHeight fixed at 24.
So it appears that even with numberOfLines > 1, the height of the Text will be fixed and not allow multiple lines.
So without this, it does not appear the numberOfLines prop has an effect, as noticed in #848 and #863
With this, it appears to work exactly as expected.
Text components require special alignment treatment with word wrapping. Normally a word wrap will force text alignment to flex-start. So we align directly when number of lines is > 1, while respecting the numeric property and it's interaction with RTL languages
It's entirely possible I'm missing something, …

fix: datatable.title numberOfLines > 1 height + wrapped text align

---

src/components/HelperText.tsx
src/components/TextInput/Adornment/TextInputAdornment.tsx
src/components/TextInput/Adornment/TextInputAffix.tsx
src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx
src/components/__tests__/TextInput.test.js
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Following the [PR](https://github.com/callstack/react-native-paper/pull/2940), but changing the approach previously introduced in `BottomNavigation` based on using `maxFontSizeMultiplier` rather the disabling font scale.
Passing `maxFontSizeMutliplier` from input to its adornments and labels.
ios | android
--- | ---
* manual testing
* unit tests covering `maxFontSizeMultiplier` use

fix: pass maxFontSizeMultiplier to input label and adornments

---

src/styles/themes/v3/tokens.tsx

Correct the following variants font properties:
* `labelLarge`:
**code:**
```
labelLarge: {
...mediumType,
tracking: 0.1,
lineHeight: 20,
size: 14,
}
```  
**documentation:**
* `bodyLarge`, `bodyMedium` and `bodySmall`:
**code:**
```
bodyLarge: {
...mediumType,
weight: '400',
lineHeight: 24,
size: 16,
},
bodyMedium: {
...mediumType,
weight: '400',
tracking: 0.25,
lineHeight: 20,
size: 14,
},
bodySmall: {
...mediumType,
weight: '400',
tracking: 0.4,
lineHeight: 16,
size: 12,
},
```
**documentation:**

fix: correct font weights

---

src/components/Button.tsx
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3137
Switching button mode from `contained` to `outlined` didn't remove the previously set `elevation`, since `elevation` was wrongly overwritten by `0` instead of `Animated.Value` according to the [shadow](https://github.com/callstack/react-native-paper/blob/main/src/styles/shadow.tsx#L31-L33) logic.
1. Run the example app
2. Switch dynamically button mode from `contained` to `outlined` - you can use the [snack](https://snack.expo.dev/@fabrizio.cucci/ab4d4d) from the issue
3. Expect there are no issues with elevation on android

fix: correct elevation when switching modes

---

src/components/Typography/AnimatedText.tsx
src/components/Typography/Text.tsx
src/styles/themes/v3/tokens.tsx

PR corrects common font weights issue on Android by using appropriate font.

fix: fix font weights for Android

---

example/src/Examples/BadgeExample.tsx
example/src/Examples/BottomNavigationExample.tsx
src/components/Badge.tsx
src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/BottomNavigation.test.js
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

PR:
* adjusts `BottomNavigation` into Material You.
* introduced prop `compact` indicating whether tabs should be spread across the entire width.
* couple changes in `navigationState.routes`:
* renamed from `icon` to `focusedIcon`
* introduced `unfocusedIcon`
* deprecated `color`
* check application in both themes, if `BottomNavigation` works and have correct colors in both themes on both platforms
* rotate the phone to confirm whether `BottomNavigation` works properly in horizontal mode
* snapshots indicate that `BottomNavigation` from theme version 2 wasn't changed.

feat: adjust BottomNavigation

---

example/src/ExampleList.tsx
example/src/Examples/AppbarExample.tsx
example/src/RootNavigator.tsx
example/src/index.tsx
src/components/Appbar/Appbar.tsx
src/components/Appbar/AppbarAction.tsx
src/components/Appbar/AppbarBackAction.tsx
src/components/Appbar/AppbarContent.tsx
src/components/Appbar/AppbarHeader.tsx
src/components/Appbar/utils.ts
src/components/__tests__/Appbar/Appbar.test.js
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap

PR:
* adjusts `Appbar` and its subcomponents to Material You. 
* introduces new props:
* `mode: 'small' (default) | 'medium' | 'large' | 'center-aligned'`
* `elevated` - adding shadow
<details>
<summary>light theme</summary>
small | medium | large | center-aligned
--- | --- | --- | ---
</details>
<details>
<summary>dark theme</summary>
small | medium | large | center-aligned
--- | --- | --- | ---
</details>
<details>
<summary>light theme</summary>
small | medium | large | center-aligned
--- | --- | --- | ---
</details>
<details>
<summary>dark theme</summary>
small | medium | large | center-aligned
--- | --- | --- | ---
</details>

feat: adjust Appbar components into Material You

---

example/src/Examples/ChipExample.tsx
src/components/Chip.tsx
src/components/Chip/Chip.tsx
src/components/Chip/helpers.tsx
src/components/__tests__/Chip.test.js
src/components/__tests__/ListItem.test.js
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/index.tsx

PR:
* adjusts `Chip` component into Material You.
* introduces new props called:
* `compact` for smaller horizontal paddings when there is only a label
* `elevated` whether chip should have elevation
* `showSelectedOverlay` indicating displaying an overlay on the selected chip
* check application in both themes, if `Chip` works and have correct colors in both themes on both platforms
* snapshots indicate that `Chip` from theme version 2 wasn't changed.

feat: adjust Chip

---

example/src/Examples/TextInputExample.tsx
example/utils/index.ts
src/components/TextInput/Adornment/TextInputAdornment.tsx
src/components/TextInput/Adornment/TextInputAffix.tsx
src/components/TextInput/Adornment/TextInputIcon.tsx
src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/constants.tsx
src/components/TextInput/helpers.tsx
src/components/TextInput/types.tsx
src/components/__tests__/TextInput.test.js
src/components/__tests__/__snapshots__/TextInput.test.js.snap

PR adjusts `TextInput` into Material You. There are no changes in API, only visual changes.
* checked `TextInput` on:
* both themes version
* both color themes
* both platforms
* snapshots indicates there are no changes in the previous version

feat: adjust TextInput

---

src/components/Appbar/AppbarContent.tsx
src/components/BottomNavigation/BottomNavigation.tsx
src/components/Button/Button.tsx
src/components/Checkbox/CheckboxAndroid.tsx
src/components/Checkbox/CheckboxIOS.tsx
src/components/Chip/Chip.tsx
src/components/Dialog/DialogTitle.tsx
src/components/Drawer/DrawerItem.tsx
src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx
src/components/FAB/FABGroup.tsx
src/components/List/ListAccordion.tsx
src/components/RadioButton/RadioButtonAndroid.tsx
src/components/RadioButton/RadioButtonIOS.tsx
src/components/Searchbar.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/__snapshots__/Searchbar.test.js.snap

`accessibilityTraits` and `accessibilityComponentType`  were deprecated and removed.
Resolve #2442

chore: remove deprecated accessibility props

---

example/src/Examples/RadioButtonItemExample.tsx
src/components/Checkbox/CheckboxItem.tsx
src/components/RadioButton/RadioButtonItem.tsx
src/components/__tests__/RadioButton/__snapshots__/RadioButtonItem.test.js.snap

PR correct disabling `RadioButtonItem` and adding missing accessibility props.

refactor: correct disabling RadioButtonItem, add missing a11y props

---

src/components/Appbar/AppbarContent.tsx
src/components/Badge.tsx
src/components/Button/Button.tsx
src/components/Drawer/DrawerItem.tsx
src/components/Drawer/DrawerSection.tsx
src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx
src/components/List/ListSubheader.tsx
src/components/Searchbar.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/Typography/AnimatedText.tsx
src/components/Typography/Text.tsx
src/components/Typography/v2/StyledText.tsx
src/components/Typography/v2/Text.tsx
src/components/__tests__/__snapshots__/DrawerItem.test.js.snap
src/styles/themes/v2/DarkTheme.tsx
src/styles/themes/v3/DarkTheme.tsx
src/styles/themes/v3/LightTheme.tsx
src/styles/themes/v3/tokens.tsx
src/types.tsx

PR corrects theme where for MD2 there are `fonts` and `typescale` for MD3. 
Moreover, it introduces the ability to overwrite the theme typescale in several components. 
Typescale properties were refined to be consistent with text styles.

fix: refactor fonts in components, themes and types

---

src/components/TextInput/TextInputFlat.tsx

When using the current `TextInputFlat.js`, I get the error:
> Text strings must be rendered within a <Text> component.
which __breaks my components tree__.
This is how I am using the `TextInput` component:
```javascript
<TextInput
ref={textInputRef}
label="" <---- Try with an empty label
placeholder="Enter a description..."
...
/>
```
The problem is in the __line 311__ of the `TextInputFlat.js` module. If you just do the following:
`{!isAndroid && multiline && Boolean(label) && (`
the error disappears.
Just pass an empty label to the `TextInput` component. Something which, in my opinion, should be accepted.
You can also check this little [snack](https://snack.expo.dev/-QUJzBClx), where the current bug is reproduced.

fix: supporting empty labels

---

src/core/Provider.tsx
src/core/__tests__/Provider.test.js

This change allows specifying `version` in `<Provider>` and does not require to pass the entire theme object anymore
**Tasks**:
1. Go to `example/src/index.tsx`
2. Change `<Provider theme={theme}` into `<Provider theme={{version: 2}}`
3. Provider should automatically pick up Material Design 2 theme
4. Same goes for `version: 3`

feat: add ability to provide version in provider

---

src/components/Card/Card.tsx
src/components/Card/CardCover.tsx
src/components/Card/utils.tsx
src/components/__tests__/Card/Card.test.js

PR corrects `Card` background color for both themes:
* 3 - used proper color from the theme
* 2 - didn't pass the background colors into `Surface`, which was breaking the previous version
Added test for utils.

fix: correct Card colors

---

src/components/Appbar/AppbarHeader.tsx

Hello,
I recently tested `5.0.0-rc2` and noticed a regression on the `Appbar.Header`
I use it this way: `<Appbar.Header statusBarHeight={0}>`.
However, it is not working like before and I have a huge space instead.
The regression seems to come from this change:
https://github.com/callstack/react-native-paper/commit/c0f50076dd71f5d00a67b50500d11681149b9c14#diff-6d75c85ccdc33452375c1e517435df14b568c580a394df5c3c7b3f05add5bfa5R135
```js
paddingTop: statusBarHeight || APPROX_STATUSBAR_HEIGHT,
```
If `0` then it will default on `APPROX_STATUSBAR_HEIGHT` instead of allowing it as valid value.
Before PR: `<Appbar.Header statusBarHeight={0}>` => `paddingTop = APPROX_STATUSBAR_HEIGHT`
After PR: `<Appbar.Header statusBarHeight={0}>` => `paddingTop = 0`

fix: fix regression in Appbar.Header statusBarHeight

---

src/components/Appbar/AppbarHeader.tsx
src/components/Surface.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/Card/__snapshots__/Card.test.js.snap
src/components/__tests__/__snapshots__/AnimatedFAB.test.js.snap
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/Chip.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/FAB.test.js.snap
src/components/__tests__/__snapshots__/IconButton.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap
src/components/__tests__/__snapshots__/Searchbar.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap
src/components/__tests__/__snapshots__/TextInput.test.js.snap
src/components/__tests__/__snapshots__/ToggleButton.test.js.snap

Due to two shadow layers on `ios` there is a need to extract absolute style properties and apply them to the outer layers to achieve the correct behavior.
Snapshots are properly updated.

fix: pass absolute styles to outer shadow layer for ios

---

src/components/Appbar/Appbar.tsx
src/components/Appbar/utils.ts
src/components/__tests__/Appbar/Appbar.test.js

PR introduces a fix for `center-aligned` where the long title was overlapping with the rest of the content.
**Before the fix:**
**After the fix:**
ios one icon | ios two icons
--- | ---
android one icon | android two icons
--- | ---
**Note:** for the shorter title which fits in the header without truncating, with two icons on the right side, the title is a bit left-aligned.  
ios one icon | ios two icons
--- | ---
android one icon | android two icons
--- | ---
Tests updated.

fix: correct center-aligned mode in AppbarHeader

---

src/components/Appbar/Appbar.tsx
src/components/__tests__/Appbar/Appbar.test.js

PR correct `Appbar` on v2 to be centered properly on iOS.
Added test cases.

fix: correct v2 should center appbar

---

src/components/Dialog/Dialog.tsx
src/components/FAB/FABGroup.tsx
src/components/Modal.tsx
src/components/__tests__/Modal.test.js

Fixes: https://github.com/callstack/react-native-paper/issues/3246
* Wrapping `Modal` component in `withTheme` HOC and passing the theme prop into `Modal` within the `Dialog` component.
* Adding a new property called `backdropColor` in `FABGroup` component.
Added tests.

fix: correct changing Dialog backdrop color

---

src/components/Badge.tsx
src/components/__tests__/Badge.test.js
src/components/__tests__/BottomNavigation.test.js

Fixes: https://github.com/callstack/react-native-paper/issues/3251
Adjust `Badge`'s line height to the font scale which increases along with setting a higher system font size.
Updated tests.

fix: adjust Badge line height to the font scale

---

src/components/Button/Button.tsx
src/components/__tests__/Button.test.js

Solves: https://github.com/callstack/react-native-paper/issues/3185
PR extends `Button` component by adding  `onPressIn` and `onPressOut` props.
Refines button's elevation.
New props are covered by tests.

feat: extend Button props by adding onPressIn and onPressOut

---

src/components/Card/CardActions.tsx
src/components/__tests__/Card/Card.test.js

Solves: https://github.com/callstack/react-native-paper/issues/3274
PR extending button within card action by adding condition whether the button's mode in child props is provided.
ios | android
--- | ---
Added test covering change.

feat: allow to specify button's mode in CardAction

---

docs/pages/10.migration-guide-to-5.0.md
docs/pages/2.theming.md
src/components/Dialog/Dialog.tsx
src/components/FAB/FABGroup.tsx
src/components/FAB/utils.ts
src/components/Modal.tsx
src/components/__tests__/FABGroup.test.js
src/components/__tests__/Modal.test.js
src/components/__tests__/__snapshots__/ListSection.test.js.snap
src/styles/themes/v3/DarkTheme.tsx
src/styles/themes/v3/LightTheme.tsx
src/types.tsx

PR is adjusting changes included in the [PR](https://github.com/callstack/react-native-paper/pull/3259) to the `main` branch.
To override color backdrop color in `FAB.Group` the only way is to use `backdropColor` (supported on v4.x as well), since that color is different than typical backdrop used in `Modal` or `Dialog`.
At the same time, to the theme there was added `backdrop` color.
Added tests.

fix: correct changing Dialog backdrop color (#3259)

---

docs/pages/10.migration-guide-to-5.0.md
example/src/Examples/AppbarExample.tsx
src/components/Appbar/Appbar.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3231
PR introduces `safeAreaInsets` prop to the `Appbar` component to make it easier for users to build the `BottomBar`, formed on the `Appbar` components. 
According to that, the documentation received new examples indicating how to build the top and bottom bars.
* MD3
ios | android
--- | ---
* MD2
ios | android
--- | ---

feat: add support for safe area insets in Appbar

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/BottomNavigation.test.js
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3290
PR fixes background color, which is now set accordingly to the docs and the value is `theme.colors.elevation.level2`.
Also it unblocks a possibility to override background color by `barStyle` prop.
* default theme colors
ios | android
--- | ---
* custom colors 
ios | android
--- | ---
Added tests.

fix: correct BottomNavigation background color

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

Fixes issue: #3272 
This was introduced here: https://github.com/callstack/react-native-paper/pull/680 and it seems like it was solving only android bug, so it should be safe to disable it on iOS.
Here is a snack with the issue: https://snack.expo.dev/@tomwaitforitmy/keyboardavoidingview
https://user-images.githubusercontent.com/52801365/184548970-6345eae2-82ad-4775-a471-f37e8c81fedf.mp4
Check if this fixes the repro.

Fix KeyboardAvoidingView not working with BottomNavigation

---

example/src/Examples/SearchbarExample.tsx
src/components/Searchbar.tsx
src/components/__tests__/Searchbar.test.js
src/components/__tests__/__snapshots__/Searchbar.test.js.snap

Added activity indicator in the searchBar. added two props `loading` and `loaderStyle` props for customizing activity indicator.
#3225 
<image src= "https://user-images.githubusercontent.com/22423684/185056075-25fa0dcd-f719-46de-b090-d62bfda2df47.png" height="600" width="300"/>

feat: added loading icon in Searchbar

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx
src/components/__tests__/TextInput.test.js
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3312
PR correct the label color for `TextInput` in flat mode.
Updated tests.

fix: correct text input label color

---

docs/pages/10.migration-guide-to-5.0.md
example/src/Examples/TextInputExample.tsx
src/components/TextInput/Adornment/TextInputIcon.tsx
src/components/__tests__/TextInput.test.js

Fixes: https://github.com/callstack/react-native-paper/issues/3258
Renamed `TextInput.Icon` prop `name` to `icon` since the name is inappropriate - it accepts not only the icon name but also the function.
Updated tests.

refactor: rename TextInputIcon prop from name to icon

---

src/components/BottomNavigation/BottomNavigation.tsx

Missing NotificationsRoute and notifications key in SceneMap

fix: NotificationsRoute causing error

---

docs/pages/1.getting-started.md

DefaultTheme.tsx doesn't exist in the main branch, link should stick to the 4.0 branch
Go to "Getting started" docs page, link should now work

docs: Fix link to DefaultTheme.tsx in "getting started"

---

src/components/Portal/Portal.tsx

The existing Portal documentation doesn't note that `Provider` supplies a `Portal.Host`; you have to click through to the documentation for `Portal.Host` to find this out. This is key information for using this component, and should be available on this page. 
I also corrected a grammatical error in the same paragraph.
Load the documentation; the extra sentence should be added.

docs: noting that Provider includes Portal.Host

---

src/components/Avatar/AvatarText.tsx
src/components/__tests__/__snapshots__/Avatar.test.js.snap

Similarly to #3264 , this PR adjusts the `Avatar.Text` component's text line height to the font scale. Fixes the following bug in `Avatar.Text`:
Updated test snapshots.

fix: adjust avatar text line height to font scale

---

src/components/FAB/FAB.tsx
src/components/__tests__/FAB.test.js
src/components/__tests__/__snapshots__/FAB.test.js.snap

PR corrects `FAB` touchable ripple behaviour which was overflowing the background, when the user sets a custom border radius and custom size.
Added and updated tests.

fix: correct custom border radius in FAB

---

src/components/TextInput/TextInputFlat.tsx
src/components/__tests__/TextInput.test.js

Fixes: https://github.com/callstack/react-native-paper/issues/3132
PR corrects padding passed to the `InputLabel` within `TextInput` on Android in the RTL mode.
before | after
--- | ---
Added tests.

fix: correct padding offset in TextInput on Android when RTL

---

src/components/Searchbar.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/Searchbar.test.js
src/components/__tests__/__snapshots__/Searchbar.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3371
Replaced `disabled={!value}` in favour of a clear icon view wrapper with conditional `pointerEvents`, because custom `iconColor` is overwritten by disabled color.
Clear icon should always be rendered within Searchbar – it's transparent, without touch events, when there is no value. It's done to avoid issues with the abruptly stopping ripple effect and changing bar width on web, when clearing the value.
Related: https://github.com/callstack/react-native-paper/pull/748.
Added tests.

fix: correct Searchbar clear icon

---

src/components/Appbar/utils.ts
src/components/__tests__/Appbar/Appbar.test.js

Fixes: https://github.com/callstack/react-native-paper/issues/3368
PR unblocks the possibility to customize `AppbarAction` color.
ios | android
--- | ---
ios | android
--- | ---

fix: unblock using custom color in AppbarAction

---

src/components/FAB/FABGroup.tsx
src/components/__tests__/FABGroup.test.js

Initially `FabGroup` component did not have a `prop` for overriding styling in fab action label. Thus, there was no direct way to override the styling of fab action label. This pr adds `labelStyle` to `actions` prop as well as renaming the previously existing `labelStyle` to `containerStyle` as it might cause further confusion. `labelStyle` should stand for style for label rather than the card style.

fix: allow styling fab-group action label, renamings

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3372
Make an animated pill shape effect only on `focused` tab.
Updated tests removing shape pill from not focused tabs.

fix: display pill shape only on focused tab

---

example/src/index.tsx
src/components/Appbar/AppbarBackIcon.tsx
src/components/DataTable/DataTablePagination.tsx
src/components/DataTable/DataTableTitle.tsx
src/components/Icon.tsx
src/components/List/ListAccordion.tsx
src/components/Menu/Menu.tsx
src/components/Searchbar.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/Typography/AnimatedText.tsx
src/components/Typography/Text.tsx
src/components/Typography/v2/StyledText.tsx

PR introduces migration to use `getConstants` from `I18nManager` since `react-native-web`removed `I18nManager.isRTL`
CI should pass.

refactor: replace I18nManager.isRTL with 18nManager.getConstants().isRTL

---

src/components/Button/Button.tsx

Fix: #3387 
In the case when the` borderRadius` was `0` the condition was treating it as a falsy value.
Replaced it  with a check of `Nullish coalescing operator` so that it check only for null and undefined values
Checked manually by applying a style with borderRadius : 0 in the button component

fix: button ripple radius

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/__tests__/TextInput.test.js
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Due to the [commit](https://github.com/callstack/react-native-paper/commit/25cd448f7eafc62e68844a44056a54b707b7e1e8), where `testID` was extracted from `rest` there was a need to adjust the `testID` in user's tests. After revisiting that change and I've noticed it was not required so current PR is patching the previously mentioned commit.
- #3376
Adjusted unit tests.

fix: allow to fully override testID in TextInput

---

src/components/Typography/Text.tsx
src/components/__tests__/Typography/Text.test.js
src/components/__tests__/__snapshots__/Avatar.test.js.snap
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/components/__tests__/__snapshots__/ListSection.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

PR sets default font properties such as `fontFamily` and `fontWeight` in `Text` component without specified `variant`.
- #3358 
Covered by unit test along with updated snapshots.

fix: set default font properties for Text component without variant

---

src/components/Snackbar.tsx
src/components/__tests__/Snackbar.test.js
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

This PR adds support to snackbar to allow laying out it's non-text children gracefully, without overflowing the view. This effort fixes #3360.
<details>
<summary> Web </summary>
</details>
<details>
<summary> Android </summary>
</details>
<details>
<summary> iOS </summary>
</details>
With introducing these changes, we get the desired results without breaking the previous functionality. However, the text overflows behind the **Undo** button due to the icon view in snackbar. 
This can be handled by the users by configuring the text styles like so:
```
text: { 
...other properties,
flexWrap: 'wrap',
flexShrink: 1 
}
```
Unit test coverage and tested on Web, Android & iOS. (screenshots above)

feat: Snackbar support for any children

---

src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/helpers.tsx
src/components/__tests__/TextInput.test.js

`TextInput` component in v5 is using two different theme colors for text content within `TextInput`:
* flat input - `onSurfaceVariant`
* outlined input - `onSurface`
To simplify overriding it new prop is going to be introduced called `textColor`.
- #3381 
Covered by unit tests

feat: add textColor prop for input content text custom color

---

example/src/Examples/ProgressBarExample.tsx
src/components/ProgressBar.tsx
src/components/__tests__/ProgressBar.test.js

Fixes #3366
Introduces the `animatedValue` prop to allow usage for controlling the progress bar using animated value created by Animated API. This prop is different when compared to `progress`, since progress isn't designed to support values that change continuously as it triggers another animation under the hood to populate progress bar. So we allowed the users to pass in their own `animatedValue` to control the progress bar.
<details>
<summary>android</summary>
https://user-images.githubusercontent.com/47336142/196183132-227320fd-1561-47e1-83f6-0e893aeeda41.mp4
</details>
<details>
<summary>iOS</summary>
https://user-images.githubusercontent.com/47336142/196184210-cba73bab-4dda-46ca-a72c-07bdbd00b8f5.mp4
</details>
<details>
<summary>web</summary> …

fix: progress bar animated value

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/BottomNavigation.test.js

After rebasing #3408 I noticed that this regression has been introduced in V5. The BottomNavigation breaks when you try to render it with a single tab.
1. Open the example APP
2. Go to the example/src/Examples/BottomNavigationExample.tsx
4. Modify the routes to have a single one instead
5. Should render a single tab as in the following screenshot

fix(regression): BottomNavigation can't render a single tab

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/BottomNavigation.test.js

Recently when working on a new feature I realized that the component BottomNavigation crashes when the prop `shifting` is true but the number of tabs is < 2 as in the following screenshot
1. Open the example APP
2. Go to the example/src/Examples/BottomNavigationExample.tsx
3. Pass the prop `shifting` to the BottomNavigation component
4. Modify the routes to have a single one instead
5. See the warning popping up

fix: BottomNavigation warn when shifting with the wrong number of tabs

---

src/components/Banner.tsx
src/components/__tests__/Banner.test.js

This PR is a proposal to make the prop `actions` of the Banner component optional. Although not specified in MUI docs(https://material.io/components/banners) RNP supports non-actionable banners. So I thought defaulting the prop `actions` to `[]` would be a nice API change
N/A

refactor: make Banner actions optional

---

docs/pages/2.theming.md
docs/pages/8.theming-with-react-navigation.md
src/core/__tests__/theming.test.js
src/core/theming.tsx
src/index.tsx
src/types.tsx

PR introduces an `adaptNavigationTheme` utility function returning provided React Navigation compliant theme, adapted in terms of colors, to the Material Design 3 color system.
- #3380 
```js
import { NavigationContainer, DefaultTheme } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { Provider, MD3LightTheme, adaptNavigationTheme } from 'react-native-paper';
const Stack = createStackNavigator();
const { LightTheme } = adaptNavigationTheme({ lightTheme: DefaultTheme });
export default function App() {
return (
<Provider theme={MD3LightTheme}>
<NavigationContainer theme={LightTheme}>
<Stack.Navigator initialRouteName="Home">
<Stack.Screen name="Home" component={HomeScreen} />
<Stack.Screen name="Details" component={DetailsScreen} /> …
```

feat: add adaptNavigationTheme utility

---

docs/component-docs.config.js
src/components/Menu/Menu.tsx

There's a Dropdown component built using TextInput + Menu in a project that I work and the only way to make the inner ScrollView with the MenuItem components able to capture taps was to patch `keyboardShouldPersistTaps` with the value "always" or "handled"
Before(Notice how a double tap is needed) | After
--- | ---
N/A - just exposing a new prop for the Menu component

feat: add prop keyboardShouldPersistTaps for Menu

---

example/src/Examples/MenuExample.tsx
src/components/Menu/Menu.tsx

Fixes #2769 
This PR allows the **Menu** to adjust it's layout if keyboard is opened, so that **Menu** doesn't overflow. 
<details>
<summary>android</summary>
https://user-images.githubusercontent.com/47336142/196435075-83b09d1b-b37b-4abe-9154-9327e59e067f.mp4
</details>
<details>
<summary>iOS</summary>
https://user-images.githubusercontent.com/47336142/196435314-60992e9c-470c-4b76-9f64-8d24e82c4a0e.mp4
</details>

fix: adjust menu layout when keyboard opens

---

src/components/Typography/Text.tsx
src/components/__tests__/__snapshots__/Avatar.test.js.snap
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/components/__tests__/__snapshots__/ListSection.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap
src/styles/themes/v3/tokens.tsx
src/types.tsx

Fixes https://github.com/callstack/react-native-paper/issues/3435
Support the possibility to override the default `Text`s component font styles, via theme property `theme.fonts.default`
- #3435 
Updated snapshots

fix: add default property to the v3 theme fonts

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

Fixes #3263 
We add `needsOffscreenAlphaCompositing` to the `Animated.View` wrapping the scene to preserve the alpha. We also use `renderToHardwareTextureAndroid` in combination with the former to avoid re-calculating for hardware texture.
More info: [here](https://reactnative.dev/docs/view#needsoffscreenalphacompositing)
Updated snapshot 🧪
Previous output on android:
https://user-images.githubusercontent.com/47336142/197985504-3f3461c2-000f-4380-a205-c1a600896ca1.mp4
Updated output on android:
https://user-images.githubusercontent.com/47336142/197985570-b1bcf67d-6bda-4ca1-8dda-11ccb8aec180.mp4

fix: added offscreenAlphaCompositing for android only

---

example/src/Examples/BottomNavigationExample.tsx
src/components/BottomNavigation/BottomNavigation.tsx
src/components/__tests__/BottomNavigation.test.js
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

Fixes #3085 
Introduces `getLazy` callback prop which allows the user to set lazy for each screen as they want leveraging the `route` parameter received in the callback. If user wants to set lazy for every screen, they can simply return `true` from the callback.
Usage:
```
<BottomNavigation
{...otherProps}
getLazy={({ route }) => route.key !== 'album'}
/>
```
Unit test coverage 🧪

feat: getLazy prop for bottom-navigation

---

src/components/List/ListIcon.tsx
src/components/List/ListItem.tsx
src/components/List/utils.ts
src/components/__tests__/ListUtils.test.js
src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/components/__tests__/__snapshots__/ListSection.test.js.snap

Matches the `List.Item` and `List.Icon` layout specs to the material v3 layout [guidelines](https://m3.material.io/components/lists/specs#eeeb78e0-265d-4e81-96ba-c2340c348a90). It has backward support for paper v2.
Manual testing ✍️

feat: List Item v3 adjustment

---

example/src/ExampleList.tsx
example/src/Examples/ListItemExample.tsx

Introduces the `List.Item` examples to the _example app_ following the [configurations](https://m3.material.io/components/lists/specs#e00879ab-2633-473f-8317-30c96b14645d) from MD3 guidelines.
This also requires [PR](https://github.com/callstack/react-native-paper/pull/3442) to be merged, which allows the `List.Item` and `List.Icon` adjustments a/c to MD3.
<details>
<summary>web</summary>
https://user-images.githubusercontent.com/47336142/198975614-56b32e7a-b85f-41ef-8a83-a46a24150733.mp4
</details>
<details>
<summary>android</summary>
https://user-images.githubusercontent.com/47336142/198975678-fe6a36ce-6913-4f9b-8655-5705b6872363.mp4
</details>
<details>
<summary>iOS</summary>
https://user-images.githubusercontent.com/47336142/198975709-2ef90b09-652c-4b0f-8e11-16e660a2866b.mp4 …

feat: added List.Item examples

---

docs/pages/8.theming-with-react-navigation.md

- Use `MD3DarkTheme` and `MD3LightTheme` instead of `MD2DarkTheme` and `MD2LightTheme` in `8.theming-with-react-navigation.md` file
N/A
**Screenshot**

docs: update 8.theming-with-react-navigation.md with MD3DarkTheme and MD3LightTheme

---

src/components/TextInput/TextInput.tsx

The TextInput component is having an unexpected behavior. When the user tries to use the contextMenu to paste a text, it's closing itself.
To test the bug, just press for a long time text input for the context menu to appear and then close.
To test the solution, just press for a long time on an input where the placeholder was not specified.

fix: unwanted closing of contextMenu

---

src/components/Card/Card.tsx
src/components/Card/utils.tsx
src/components/__tests__/Card/Card.test.js
src/components/__tests__/Card/__snapshots__/Card.test.js.snap

Fix `Card` and `Card.Cover` border radius
ios | android | web
--- | --- | --- |
- #3460 

fix: card border radius

---

src/components/Card/Card.tsx
src/components/__tests__/Card/__snapshots__/Card.test.js.snap

- #1775 
PR correct `Card` sizes when it's contained within another container, by removing the `flexGrow` style from `innerContainer`.
ios | android | web
--- | --- | ---
Updated snapshot.

fix: correct card size within container

---

src/styles/fonts.tsx
src/styles/themes/v3/LightTheme.tsx

Improve types for `configureFonts` which should display an error when:
* user defines new `variant` without all font properties
in other cases like changing any font property for all variants or a specific one, TS should not raise any error.
CI passes.

refactor: adjust configure fonts overloads

---

src/components/SegmentedButtons/SegmentedButtonItem.tsx
src/components/__tests__/__snapshots__/SegmentedButton.test.js.snap

Fix for issue #3481. SegmentedButtons are not equal in widths

fix: segmented-button-item-style

---

docs/pages/2.theming.mdx
src/core/__tests__/theming.test.js
src/core/theming.tsx

Extended `adaptNavigationTheme` to accept custom, but compliant with MD, user themes in both modes.
* extends `adaptNavigationThemes` by two new (optional) themes object properties: `materialLight` and `materialDark`where the user can pass custom theme compliant with MD and Paper.
* currently existing properties `light` and `dark` were renamed to `reactNavigationLight` and `reactNavigationDark`
- #3476 
Covered by the additional unit test.

refactor: extend adaptNavigationTheme

---

docs/pages/10.migration-guide-to-5.0.md
example/src/Examples/SnackbarExample.tsx
src/components/Snackbar.tsx
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

Updates `Snackbar` according to the latest [guidelines](https://m3.material.io/components/snackbar/specs#06833484-2cc8-491a-8869-0224835ebae3)
There are 3 new props related to the optional Icon button -optional close affordance - placed after action button:
*  icon - icon to display when `onIconPress` is defined. The default will be `close` icon.
*  onIconPress - function to execute on icon button press. The icon button appears **only** when this prop is specified.
*  iconAccessibilityLabel - accessibility label for the icon button. This is read by the screen reader when the user taps the button.

refactor: adjust Snackbar to Material You

---

docs/pages/10.migration-guide-to-5.0.md
example/src/DrawerItems.tsx
example/src/index.tsx
src/components/Drawer/DrawerCollapsedItem.tsx
src/components/Drawer/DrawerSection.tsx
src/components/__tests__/Drawer/DrawerCollapsedItem.test.js

Reactor `Drawer.CollapsedItem` to support both `focusedIcon` and `unfocusedIcon`.
In `Drawer.Section` there is a new property for handling `Divider` visibility.
Covered by unit tests.

refactor: adjust drawer collapsed item icons

---

src/components/Menu/Menu.tsx

Menus currently don't show correctly in RN `Modal`, but do work correctly within Paper `Modal`. Updating the docs to caution users who hit #2593 because of this.
`yarn serve` within /docs, and verified the new stuff shows correctly:

docs: update Menu docs for RN Modal

---

docs/pages/1.getting-started.md
docs/pages/10.migration-guide-to-5.0.md
example/package.json
example/src/ExampleList.tsx
example/src/Examples/SnackbarExample.tsx
example/src/index.tsx
example/yarn.lock
package.json
src/components/Appbar/AppbarHeader.tsx
src/components/BottomNavigation/BottomNavigation.tsx
src/components/FAB/FABGroup.tsx
src/components/Modal.tsx
src/components/Snackbar.tsx
src/components/__tests__/Appbar/Appbar.test.js
src/components/__tests__/BottomNavigation.test.js
src/components/__tests__/FABGroup.test.js
src/components/__tests__/Modal.test.js
src/components/__tests__/Snackbar.test.js
src/components/__tests__/Tooltip.test.js
src/components/__tests__/__snapshots__/Snackbar.test.js.snap
src/core/Provider.tsx
src/core/SafeAreaProviderCompat.tsx
src/core/__tests__/Provider.test.js
yarn.lock

feat: replace rn iphone x helper with safe area context

---

src/components/Card/Card.tsx

Disable `useNativeDriver` within `Card` animation, to avoid crashes.
- #3511 
App cannot crash when tapping last 3 items.

fix: disable native driver in Card elevation animation

---

docs/pages/8.theming-with-react-navigation.md

Documentation code fix on page: https://callstack.github.io/react-native-paper/theming-with-react-navigation.html under the 2nd part of _Using Context_.
Problems using `<TouchableRipple onPress={() => toggleTheme()}>` wrapper on `<Switch>`  causes:
1. Not to work on mobile (it does work on web).
2. Causes the whole width of the screen to toggle the switch, instead of the switch itself.
In addition, adding the `onValueChange={onToggleSwitch}` prop to `<Switch>` enables it to toggle after removing `<TouchableRipple>`.
[Expo snack](https://snack.expo.dev/@m0de/switch?name=Switch&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fswitch.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Switch%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyC …

docs: fixed <Swtich> example for  Theming with React Navigation - Using Context

---

src/components/Menu/Menu.tsx

The dimensions was set outside the component and therefore didn't change when the screen size was adjusted.
This was introduced in in rc9 so I just moved it back to where it was before when it worked.
Fixes #3515

fix: fix position of menu when dimensions change

---

example/src/Examples/TextInputExample.tsx
example/utils/index.ts
src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx
src/components/__tests__/TextInput.test.js
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Adds `customInputStyle` prop to `TextInput` as requested in #3434 
This prop allows to pass style props directly to the input itself, not the container. 
The tests and examples are already updated.
Tested on both IOS and Android with `StyleProp<ViewStyle>` props like `paddingLeft`, `backgroundColor` etc.
**Custom style input example:**
`customInputStyle={{ paddingLeft: 50  }}`

feat: add customInputStyle to TextInput

---

src/components/List/ListAccordion.tsx

This component can receive a custom prop `right`, so the following code is allowed: 
```js
const renderRight = ({ isExpanded }) =>
(
<IconButton
icon={isExpanded ? 'chevron-up' : 'chevron-down'}
size={24}
onPress={myCustomOnPress}
/>
);
```
However, the onPress passed to the IconButton won't be triggered since the View container has a hard-coded `pointerEvents="none"`
N/A

feat: add prop pointerEvents for ListAccordion

---

src/components/IconButton/IconButton.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/IconButton.test.js.snap
src/components/__tests__/__snapshots__/Searchbar.test.js.snap
src/components/__tests__/__snapshots__/TextInput.test.js.snap
src/components/__tests__/__snapshots__/ToggleButton.test.js.snap

When using the keyboard and you tab to an IconButton, the outline is "cut" on all sides making it hard to see that the button is focused.
The solution was just to add the same `borderRadius` to the `TouchableRipple` as the parent `Surface` has.
Tab to an IconButton. When it is focused, you will now see the whole outline instead of partial one.
Before: 
After:

fix: Visual fix on IconButton when focused

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Change flex behaviour in `TextInput` by removing `flexGrow` which makes wrapped inputs occupy the whole height. 
- #3530 
Tested manually, on all platforms, checked if doesn't break multiline inputs,

refactor: correct input flex behavior

---

src/components/Menu/Menu.tsx

The previous fix that I did that was recently merged (https://github.com/callstack/react-native-paper/pull/3521) worked fine when I tested it (both with the example app and with the code from this snack: https://snack.expo.dev/@fyranollfyra/menu-with-keyboard).
But when I tested the released version with my own app where I originally discovered this bug, the bug was still there when changing width of my window.
So I started digging into the code some more and made it a bit simpler and removed unnecessary listeners since we now get the window layout when opening the menu (the same time as we get the anchor and menu layout as well). 
I also cleaned up some of my previous code (`windowLayout.width` instead of `this.state.windowLayout.width`) to be more in line how we use variables from state …

fix: menu position fix when dimensions change

---

example/src/Examples/ButtonExample.tsx
src/components/Button/Button.tsx
src/components/__tests__/Button.test.js
src/components/__tests__/__snapshots__/Banner.test.js.snap
src/components/__tests__/__snapshots__/Button.test.js.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.js.snap
src/components/__tests__/__snapshots__/Snackbar.test.js.snap

Adjust icon styles for the `compact` Button to avoid overlapping icon and label.
- #3550 
Added units tests.

fix: adjust icon styles in compact button

---

src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx
src/components/FAB/utils.ts
src/components/__tests__/AnimatedFAB.test.js
src/components/__tests__/FAB.test.js
src/components/__tests__/__snapshots__/AnimatedFAB.test.js.snap

By destructuring the styles and extracting the `backgroundColor`, it won't be passed into `AnimatedFAB` container styles whose background color should always be `transparent`
- #3547 
Added unit test cases.

fix: correct animated fab container bg color

---

example/src/Examples/IconButtonExample.tsx
src/components/Card/Card.tsx
src/components/IconButton/IconButton.tsx
src/components/__tests__/Card/Card.test.js
src/components/__tests__/Card/__snapshots__/Card.test.js.snap
src/components/__tests__/IconButton.test.js
src/components/__tests__/__snapshots__/ToggleButton.test.js.snap

Corrects the border behavior in `IconButton` which affects the `ToggleButton` and makes it circle, after merging https://github.com/callstack/react-native-paper/pull/3531. Additionally within the `Card` component, there was no option to override the `outline` radius which is going to be supported after merging that PR. 
- #3563 
Added appropriate unit tests.

fix: correct border radius in icon button and card components

---

src/components/Card/Card.tsx

docs: Fix typo in `Card` doc

---

src/components/Card/Card.tsx
src/components/__tests__/Card/Card.test.js

PR unifies the approach of the possibility to override the `borderColor` in `Card` via styles.
- #3563 
Covered by a unit test.

fix: allow to override card border color using styles

---

example/src/Examples/ToggleButtonExample.tsx
src/components/ToggleButton/ToggleButtonGroup.tsx

fix: Now you can use `ToggleButton.Group` with Union Types and Enums (default string)
Before you couldn't use Union types or enums without TS complaining about the type
```
type Fruits = 'watermelon' | 'strawberries' | 'apple';
```
with this new change, TS will get the right type and won't complain
- Use different types, like string, enums and union types
- Check if the IDE get the right type

fix: Made ToggleButton.Group TS compatible

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/BottomNavigation/utils.ts
src/components/__tests__/BottomNavigation.test.js
src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap

Made available the props `activeColor` and `inactiveColor` to the labels
https://user-images.githubusercontent.com/1676818/211879937-e3888c34-c84d-46f7-8ac9-f05e90b6d9c3.mov
- #3576
Cover by tests
Use `@react-navigation/material-bottom-tabs` 
Use `BottomNavigation` from Paper

fix: activeColor and inactiveColor to match icon colors

---

src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx

PR adjust types in `FAB` component to make one of `icon` or `label` props optional if one of them is currently defined, however, both mustn't be undefined at the same time.
- #3594 
N/A

fix: adjust label and icon props optionality

---

src/components/Appbar/AppbarContent.tsx
src/components/__tests__/Appbar/Appbar.test.js
src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap

PR introduces adjustments for handling the `title` prop in `Appbar.Content` to wrap **only** the title string within the default `Text` component. Other types passed into `title` are rendered directly in the `View` container.
- #3572 

fix: appbar content title container adjustments

---

src/components/TextInput/Adornment/TextInputAffix.tsx
src/components/__tests__/TextInput.test.js
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Fixes missing possibility to invoke `onLayout` on `TextInput.Affix` which is mentioned in the documentation.
- #3589 
Added unit test.

fix: calls onLayout on input affix

---

.circleci/config.yml
scripts/typescript-output-lint.js
src/components/Appbar/AppbarAction.tsx
src/components/Appbar/AppbarBackAction.tsx
src/components/FAB/FAB.tsx
src/components/IconButton/IconButton.tsx
src/components/Searchbar.tsx
src/components/TextInput/TextInput.tsx
src/utils/forwardRef.tsx

Related to #3595 #3517
The `lib/typescript` folder is filled with a lot of bloat (as shown in screenshot below). This PR removes all instances of that kind of bloat and adds a script to prevent a regression.
For example: the source code doesn't contain any `accessibilityLabelledBy` but there are 40 occurrences in `lib/typescript`. This causes an issue in React Native 0.71 where this prop has a type of unknown and is required (the prop is missing from the type definitions in 0.71.0).
|Before|After|
|-|-|
|<img width="265" alt="image" src="https://user-images.githubusercontent.com/8790386/213297005-177925e3-5377-4b63-a2d8-594e313f3a08.png">|<img width="265" alt="image" src="https://user-images.githubusercontent.com/8790386/213297245-479e69d5-197c-4991-95c6-26ee07e28211.png">|
|<img …

fix: TypeScript bloat

---

src/components/Banner.tsx
src/components/Modal.tsx
src/components/ProgressBar.tsx
src/components/__tests__/Banner.test.js
src/components/__tests__/Modal.test.js
src/components/__tests__/ProgressBar.test.js

As an addition to https://github.com/callstack/react-native-paper/pull/3583 this PR fixes suppressed `exhaustive deps` errors in:  ProgressBar, Banner, Modal
There should be no functional changes at all after this refactor. Added unit tests to check for regression where applicable.
After https://github.com/callstack/react-native-paper/pull/3583 gets merged there will be some conflicts which I'll happily resolve.

refactor: Fix exhaustive deps linting errors

---

.eslintrc
eslint-local-rules/index.js
eslint-local-rules/no-import-react-forwardref.js
eslint-local-rules/no-react-forwardref-usage.js
package.json
src/components/Surface.tsx
src/components/ToggleButton/ToggleButton.tsx
src/components/Typography/Text.tsx
src/components/Typography/v2/Text.tsx
src/utils/forwardRef.tsx
yarn.lock

I noticed that I missed to remove `React.forwardRef` from some places when working on #3603 so I decided to make a couple of ESLint rules
|Before|After|
|-|-|
|<img width="1341" alt="image" src="https://user-images.githubusercontent.com/8790386/215465771-a259e188-8be9-4704-956f-dc1f6679b384.png">|<img width="932" alt="image" src="https://user-images.githubusercontent.com/8790386/215465736-e380cd48-23c9-4829-8cbe-96bc3de2833d.png">|
|<img width="1283" alt="image" src="https://user-images.githubusercontent.com/8790386/215465937-3f053755-f20f-4b28-858f-b08d09196605.png">|<img width="1060" alt="image" src="https://user-images.githubusercontent.com/8790386/215465425-c9a803fd-9feb-4c6e-a8fd-f999b5657bd3.png">|
CI passes

chore: linter rules to detect `forwardRef` usage

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInput.tsx
src/components/__tests__/__snapshots__/TextInput.test.js.snap

Based on work started in https://github.com/callstack/react-native-paper/pull/3642 fixes https://github.com/callstack/react-native-paper/issues/3648
Please note that this branch is based of the refactor branch, so if the other goes into `main` first, the target here should be updated to `main` as well.
The app should now behave as presented:
https://user-images.githubusercontent.com/7429558/216358415-f9909a7f-9870-41b3-967c-473f5ad24cd1.mov

fix: custom input styling in TextInput (#3648)

---

example/src/Examples/CardExample.tsx
src/components/Card/CardActions.tsx
src/components/__tests__/Card/Card.test.tsx

Fixes: #3633 
PR fixes the possibility to pass custom `Button`'s styles when it's wrapped within the `Card.Actions`
- #3633 
Added unit test and additional example in the demo app.

fix: custom Button styles nested in Card.Actions

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/Button/Button.tsx
src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx
src/components/__tests__/AnimatedFAB.test.tsx
src/components/__tests__/BottomNavigation.test.tsx
src/components/__tests__/Button.test.tsx
src/components/__tests__/FAB.test.tsx
src/components/__tests__/__snapshots__/AnimatedFAB.test.tsx.snap
src/components/__tests__/__snapshots__/Banner.test.tsx.snap
src/components/__tests__/__snapshots__/BottomNavigation.test.tsx.snap
src/components/__tests__/__snapshots__/Button.test.tsx.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/FAB.test.tsx.snap
src/components/__tests__/__snapshots__/Menu.test.tsx.snap
src/components/__tests__/__snapshots__/Snackbar.test.tsx.snap

Fix the issue with overriding default props of some components that was caused by #3606 
It's worth to go through affected components and check if it's possible to override props.

fix: fix overriding default props

---

src/core/Provider.tsx
src/core/__tests__/Provider.test.js

This pull request wants to allow an override of the animation field of the default theme.
Before it was possible now not anymore.

feat: allow override of custom theme animation

---

src/components/Surface.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Card/__snapshots__/Card.test.tsx.snap
src/components/__tests__/Surface.test.js
src/components/__tests__/__snapshots__/AnimatedFAB.test.tsx.snap
src/components/__tests__/__snapshots__/Banner.test.tsx.snap
src/components/__tests__/__snapshots__/BottomNavigation.test.tsx.snap
src/components/__tests__/__snapshots__/Button.test.tsx.snap
src/components/__tests__/__snapshots__/Chip.test.tsx.snap
src/components/__tests__/__snapshots__/DataTable.test.js.snap
src/components/__tests__/__snapshots__/FAB.test.tsx.snap
src/components/__tests__/__snapshots__/IconButton.test.tsx.snap
src/components/__tests__/__snapshots__/ListItem.test.js.snap
src/components/__tests__/__snapshots__/Menu.test.tsx.snap
src/components/__tests__/__snapshots__/Searchbar.test.tsx.snap
src/components/__tests__/__snapshots__/Snackbar.test.tsx.snap
src/components/__tests__/__snapshots__/TextInput.test.js.snap
src/components/__tests__/__snapshots__/ToggleButton.test.tsx.snap

PR refines styles in the `Surface` views for `iOS` platform, to pass the `flex` into all its layers.
- #3652 
Added unit test covering Surface's layer styles.

fix: passing flex to the shared and inner layer Surface styles

---

example/babel.config.js
example/src/DrawerItems.tsx

|Android|iOS|
|-|-|
|<img width="489" alt="image" src="https://user-images.githubusercontent.com/8790386/216077340-1f4766cc-90d9-48e6-b30e-049735126d6a.png">|<img width="498" alt="image" src="https://user-images.githubusercontent.com/8790386/216077785-96b6b3af-02e1-4e39-b05c-2a31cc8e4c4f.png">|
Version is visible in drawer in example app

chore: show library version in drawer in example app

---

src/components/Card/Card.tsx
src/components/__tests__/Card/Card.test.tsx
src/components/__tests__/Card/__snapshots__/Card.test.tsx.snap

PR introduce new prop called `contentStyle` to allow override the view styles which is wrapping `Card`'s content.
- #3646 
New prop covered by unit test.

feat: add content style prop to the Card

---

docs/pages/10.migration-guide-to-5.0.md

There's a small copy/paste error in the "Typography" section of the Migration guide to Material You 5.0.
That line and the original also read better with an additional "the" added.
N/A

docs: fix copy/paste error

---

docs/.eslintrc
docs/src/components/BannerExample.tsx

The Banner Example component always "light" till manually toggle the mode
React Native Paper isn't optimized for Server-Side-Rendering, so it's always rendered in the light mode on the server.
Render example only on the browser (Client-Side)

fix: BannerExample component theme in production

---

docs/src/components/BannerExample.tsx
docs/src/components/GetStartedButtons.tsx
docs/src/pages/index.mdx

When opening the new docs, the screen flashes for a brief moment. This is caused by Docusaurus rendering full-screen loader via `react-loadable` (https://github.com/jamiebuilds/react-loadable#avoiding-flash-of-loading-component)
I guess the way to fix it is to defer using `useColorMode` hook until page is fully hydrated.
Go to https://callstack.github.io/react-native-paper/index.html and use Analyze page lode via Chrome's Lighthouse.

docs: screen flash on initial docs load

---

docs/src/components/GetStartedButtons.tsx

Get started button in docs doesn't work
For Docusaurus to prepend `baseUrl` the href needs to start with `/`: https://github.com/facebook/docusaurus/blob/50b1dc7db33f570f15942f8414be84f5d471282f/packages/docusaurus/src/client/exports/Link.tsx#L28
Get started button in docs works

docs: fix get started button

---

src/components/Appbar/AppbarContent.tsx
src/components/__tests__/Appbar/Appbar.test.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap

Resolves problem for accessibility label when Appbar.Content has no OnPress action
detailed info: https://github.com/callstack/react-native-paper/issues/3704
- Start the app
- Open Xcode, then go to the Xcode menu -> Open Developer Tool -> Accessibility Inspector
- Select the heading
|   case | expected result  |
|---|---|
|  **when Appbar.Content hasn't onPress callback: content is recognized as a text** |  ![image](https://user-images.githubusercontent.com/7682108/222532538-bce91603-7df1-42cb-a9d3-3454d13a8575.png) |
|  **when Appbar.Content has onPress callback:  component is recognized as a button** |   ![image](https://user-images.githubusercontent.com/7682108/222532749-91edf103-7ded-4d37-93b0-fdebbc0e5725.png)
|

fix: changed accessibility label based on onPress callback

---

package.json
yarn.lock

Fix paths in sourcemap files.
After migrated to Expo SDK 48, more than 150 warnings appeared with the text "Failed to parse source map from sourcemap". The same problem was also in @react-navigation which was fixed by upgrading react-native-builder-bob from version 0.20.3 to 0.20.4
https://github.com/callstack/react-native-paper/issues/3717

fix: fix paths in sourcemap files

---

src/components/HelperText.tsx
src/components/__tests__/HelperText.test.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/3684
Correct text color in `HelperText`
- #3684 
Added unit test.

fix: correct text color

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx

Another round of performance improvements over `TextInput`. This time we managed to memoize `InputLabel` so it does not re-render on each key stroke. 
Essentially to do so, I had to inline the `parentState` and `labelProps` objects, so that reconciler has a chance to diff changes in props. Previously both objects would be created on each render.
This work results in slower first render (10% comparing to previous) but faster response on each key stroke (by 25%)
Click through in the example app. No changes to the previous implementation should occur.

refactor: fix performance of InputLabel

---

docs/docs/guides/04-fonts.md
example/src/Examples/TextExample.tsx
src/components/Appbar/AppbarContent.tsx
src/components/Typography/AnimatedText.tsx
src/components/Typography/Text.tsx
src/components/Typography/types.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.tsx.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButtonItem.test.tsx.snap
src/components/__tests__/Typography/Text.test.tsx
src/components/__tests__/Typography/__snapshots__/Text.test.tsx.snap
src/components/__tests__/__snapshots__/Banner.test.tsx.snap
src/components/__tests__/__snapshots__/BottomNavigation.test.tsx.snap
src/components/__tests__/__snapshots__/Button.test.tsx.snap
src/components/__tests__/__snapshots__/Chip.test.tsx.snap
src/components/__tests__/__snapshots__/DataTable.test.tsx.snap
src/components/__tests__/__snapshots__/DrawerItem.test.tsx.snap
src/components/__tests__/__snapshots__/FAB.test.tsx.snap
src/components/__tests__/__snapshots__/ListItem.test.tsx.snap
src/components/__tests__/__snapshots__/ListSection.test.tsx.snap
src/components/__tests__/__snapshots__/Menu.test.tsx.snap
src/components/__tests__/__snapshots__/MenuItem.test.tsx.snap
src/components/__tests__/__snapshots__/SegmentedButton.test.tsx.snap
src/components/__tests__/__snapshots__/Snackbar.test.tsx.snap
src/index.tsx

Fixes #3658
Closes #3659
- Updated docs
- Updated example
- Added tests
|iOS|Android|
|-|-|
|<img width="548" alt="image" src="https://user-images.githubusercontent.com/8790386/217033819-facdee97-c7f9-4574-8940-88d3b1b7a326.png">|<img width="526" alt="image" src="https://user-images.githubusercontent.com/8790386/217033801-0ed32380-b08e-4866-b6e1-aac0788a39b1.png">|
CI passes. Example works as expected.

fix: allow for custom variants in `Text` (with factory)

---

src/components/BottomNavigation/utils.ts
src/components/__tests__/BottomNavigation.test.tsx

Corrects label color for `BottomNavigation` for `v2`.
Added a unit test case.
before | after
--- | ---

fix: correct label color for v2

---

src/components/Banner.tsx
src/components/__tests__/__snapshots__/Banner.test.tsx.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3703
According to the issue, PR adjusts the `opacity` of the `Banner` component, to set it to `0` once the component is not **visible**.
- #3703

fix: adjust surface wrapper opacity

---

src/components/Appbar/AppbarBackIcon.tsx
src/components/Checkbox/CheckboxAndroid.tsx
src/components/Checkbox/CheckboxIOS.tsx
src/components/Chip/Chip.tsx
src/components/DataTable/DataTablePagination.tsx
src/components/DataTable/DataTableTitle.tsx
src/components/Icon.tsx
src/components/List/ListAccordion.tsx
src/components/RadioButton/RadioButtonIOS.tsx
src/components/Searchbar.tsx
src/components/Snackbar.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/3688
Replace the `MaterialCommunityIcons` used in several components in favour of using the internal `Icon` _(created at the top of the Material Icon)_ to allow to customize them by providing the custom icon according to the [documentation](https://callstack.github.io/react-native-paper/docs/guides/icons/#4-use-custom-icons)
- #3688 
Testing the app manually.

refactor: replace MaterialCommunityIcon in favor of internal Icon

---

example/src/Examples/SearchbarExample.tsx
src/components/Searchbar.tsx
src/components/__tests__/Searchbar.test.tsx

This PR adds the `onClearIconPress` prop to the `Searchbar` component. If `onClearIconPress` is defined when pressing close button on search the default behaviour will be executed and after that users' hook will be executed. This for an example allows `Keyboard.dismiss()` to be called from hook.
There is no visually changes. Adding 
`  onClearIconPress={() => /* delete query text (default behaviour) and dismiss keyboard */ Keyboard.dismiss()}` to ` SearchBar` should dismiss keyboard after clearing text.
This feature was requested in #1970

feat: Add onClearIconPress to SearchBar

---

src/components/Menu/MenuItem.tsx
src/components/__tests__/MenuItem.test.tsx

The component `Menu.Item` accepts a prop `icon` which is useful when displaying a multi-selectable list of options with a checkbox. In this case, the accessibilityState `checked` makes total sense to be used.
A new test was added to exercise this change.

feat: add prop accessibilityState for Menu.Item

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx

RNP v5.1.4 introduced regression in positioning of label on outlined TextInput:
This was caused by https://github.com/callstack/react-native-paper/pull/3642. Reason:
Outlined TextInput uses additional mask to cover bigger round corners:
Working on performance of this component I decided to apply this mask only on outlined TextInput and only if the roundness is greater than 6pt. What I did not anticipated is that in V2 the this additional mask was used to cover left-most side of the label.
With this additional mask fixed, we can now unify math behind label for both V2 & V3. This should solve the issue.
All outlined inputs were affected.

fix: input label positioning regression

---

example/src/Examples/SearchbarExample.tsx
example/src/ScreenWrapper.tsx
src/components/Searchbar.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Searchbar.test.tsx
src/components/__tests__/__snapshots__/Searchbar.test.tsx.snap

PR is about adjusting `Searchbar` to the latest MD guidelines. According to the [specs](https://m3.material.io/components/search/specs) there is Search View and Search Bar, that's why there was introduced property `mode`:
* `mode="bar"`
* `mode="view"`
Additionally, the `Searchbar` with `mode="bar"` can receive the `traileringIcon` with its `onPress` and `accessibility`  or custom color properties. 
```
<Searchbar
mode="bar"
placeholder="Trailering icon"
onChangeText={(query) =>
setSearchQuery({ ...searchQueries, traileringIcon: query })
}
value={searchQueries.traileringIcon}
traileringIcon={'microphone'}
traileringIconColor={
isVisible ? MD3Colors.error40 : colors.onSurfaceVariant
}
traileringIconAccessibilityLabel={'microphone button'}
onTraileringIconPress={() => setIsVisible(true)} …
```

refactor: adjust searchbar to the latest md guidelines

---

src/components/Appbar/AppbarBackIcon.tsx
src/components/Checkbox/CheckboxAndroid.tsx
src/components/Checkbox/CheckboxIOS.tsx
src/components/Chip/Chip.tsx
src/components/DataTable/DataTablePagination.tsx
src/components/DataTable/DataTableTitle.tsx
src/components/Icon.tsx
src/components/List/ListAccordion.tsx
src/components/RadioButton/RadioButtonIOS.tsx
src/components/Searchbar.tsx
src/components/Snackbar.tsx

PR reverts the previously merged and released in `5.3.0` [changes](https://github.com/callstack/react-native-paper/pull/3699) related to replacing `MaterialCommunityIcons` in favor of internal `Icon`, which introduced a **breaking change**. 
Unfortunately, I made a mistake and overlooked the fact that some custom fonts don't have hardcoded icons like `search` or `magnify` 😞 
N/A

fix: revert 'replace MaterialCommunityIcon in favor of internal Icon'

---

package.json
src/components/Banner.tsx
src/components/BottomNavigation/BottomNavigation.tsx
src/components/Modal.tsx
src/components/Snackbar.tsx
yarn.lock

Fixes: https://github.com/callstack/react-native-paper/issues/3737
Replace the `use-event-callback` with `use-latest-callback` to avoid warnings.
Following steps from the issue:
Create a new Expo project:
`yarn create expo-app folder-to-install-app-in`
`yarn add react-native-web react-dom @expo/webpack-config`
Run yarn web and it will start fine without any warning.
Add React Native Paper with `yarn react-native-safe-area-context react-native-paper`
Wrap App.js with <Provider>...</Provider>.
Run `yarn web`.

chore: install use-latest-callback

---

docs/component-docs-plugin/generatePageMDX.js
docs/docusaurus.config.js

Solves: #3682 
Extends docusaurus config **customFields** with the property `moreExamples` which can be supplemented with links to the snack / github repositories containing additional component's examples.
Based on the linked issue, added the first additional user's example for `Portal` component 
_(provided snack in the issue was copied into `react-native-paper` expo account with credits to the author)_
- #3682

docs: add configuration for component's more examples

---

CONTRIBUTING.md
docs/component-docs-plugin/generatePageMDX.js
docs/docs/guides/01-getting-started.md
docs/docs/guides/02-theming.mdx
docs/docs/guides/04-fonts.md
docs/docs/guides/10-migration-guide-to-5.0.md
docs/docusaurus.config.js
docs/src/components/PropTable.tsx
src/components/BottomNavigation/BottomNavigation.tsx
src/components/Dialog/Dialog.tsx
src/components/Drawer/DrawerCollapsedItem.tsx
src/components/FAB/FABGroup.tsx
src/components/IconButton/IconButton.tsx
src/components/Modal.tsx
src/components/Portal/Portal.tsx
src/components/Surface.tsx
src/components/TextInput/TextInput.tsx
src/components/ToggleButton/ToggleButtonGroup.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/3731
Addressing leftovers from the list within the [issue](#3731):
* corrects link to the egghead on the contribution guide
* adding admonitions in several places: 
* add support for `@extends` annotation, for prop extension:
* correct links for `Edit this page` in `guides`
* correct links for types such as `IconSource` and `ThemeProp`

docs: correct type links, add admonitions, support extends annotation

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/BottomNavigation/BottomNavigationBar.tsx
src/components/__tests__/BottomNavigation.test.tsx

This fix Implements: https://github.com/callstack/react-native-paper/issues/3690
Add long press action on the bottom navigation tabs
1. Start the example app 
2. Click on the Bottom Navigation
3. Click and hold any of the bottom tabs for at least 370 milliseconds.
https://user-images.githubusercontent.com/33870502/225570574-dd95eba1-afc7-4a26-9666-b80d141dfc1b.mp4

fix: add onTabLongPress for Bottom Navigation

---

src/react-navigation/types.tsx

Fixes conflict between https://github.com/callstack/react-native-paper/pull/3758 and https://github.com/callstack/react-native-paper/pull/3741
`yarn bootstrap` works

fix: ignore onTabLongPress in MaterialBottomTabNavigationConfig

---

docs/docs/guides/04-fonts.md

#3763
TypeScript infers `fontWeight` as `string` and cannot pick the correct overload. The expected `fontWeight` is a union:
https://github.com/callstack/react-native-paper/blob/844a2b192cc223ed3d024b01d17ea5773776078c/src/types.tsx#L7-L18
Nothing, docs only change

docs: comment for TypeScript users

---

src/react-navigation/types.tsx
src/react-navigation/views/MaterialBottomTabView.tsx

Fixes event emitter for https://github.com/callstack/react-native-paper/pull/3758
`yarn bootstrap` works

fix: add event emit for long press

---

src/utils/splitStyles.ts

Paper 5.5.0 cannot be used in Expo Snack.
Tested the changes in this Snack: https://snack.expo.dev/@dimitarnestorov/mad-tortilla

refactor: fix `splitStyles` for Expo Snack

---

src/react-navigation/types.tsx
src/react-navigation/views/MaterialBottomTabView.tsx

Remove abstraction function for event emitter https://github.com/callstack/react-native-paper/pull/3769
`yarn bootstrap` works

fix: remove abstraction function from event emitter

---

docs/docs/guides/08-theming-with-react-navigation.md

Corrected a typo in the documentation page [Theming with React Navigation](https://callstack.github.io/react-native-paper/docs/guides/theming-with-react-navigation/#material-design-2-1), where in the code snippet it incorrectly merged the React Native Paper "MD3DarkTheme" with the React Navigation "LightTheme" into "CombinedDefaultTheme". Same typo with "CombinedDarkTheme".
(N/A)

docs: correct typo in code snippet for combining themes with React Navigation

---

example/src/Examples/AppbarExample.tsx
src/components/Appbar/AppbarContent.tsx
src/components/Card/Card.tsx
src/components/Card/CardTitle.tsx
src/components/__tests__/Appbar/Appbar.test.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Card/Card.test.tsx
src/components/__tests__/Card/__snapshots__/Card.test.tsx.snap

It's kinda weird to hear "not enabled" for elements of the UI that will never become interactable.
I tried messing around with the `accessibilityState` prop but I couldn't figure out a way without removing the element: https://snack.expo.dev/@dimitarnestorov/touchablewithoutfeedback-can-not-remove-disabled-trait
|Before|After|
|-|-|
|<img width="881" alt="Showcasing traits for AppbarContent before changes in PR" src="https://user-images.githubusercontent.com/8790386/229113325-2d5a3318-56cf-4f69-8c66-dc5e2153818b.png">|<img width="887" alt="Showcasing traits for AppbarContent after changes in PR" src="https://user-images.githubusercontent.com/8790386/229113611-f52b1f62-ddb0-465b-97a1-6a6632f10f25.png">|
|<img width="862" alt="Showcasing traits for Card before changes in PR" …

chore: remove disabled accessibility trait for `AppbarContent` and `Card`

---

example/src/Examples/SurfaceExample.tsx
src/components/Banner.tsx
src/components/Button/Button.tsx
src/components/Card/Card.tsx
src/components/Chip/Chip.tsx
src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx
src/components/Snackbar.tsx
src/components/Surface.tsx
src/components/__tests__/Surface.test.tsx

Fixes: #3790 
- #3790 
Introducing prop `mode` to the `Surface` component with two possible options `elevated` (default) and `flat`.
The `flat` mode indicates the `Surface` component will have the background color appropriate to the set level, however, it will not have a `shadow`.
ios | android | web
-- | --- | ---
New prop `mode` covered by unit tests.

feat: support flat and elevated mode

---

example/src/ExampleList.tsx
example/utils/index.ts

* adding `unstable_pressDelay` - there is an issue with `react-native` related to detecting gestures, especially when it comes to scrolling the list with touchables – when a user tries to scroll a list, the system may mistakenly detect it as a tap or swipe gesture, which can lead to unexpected behaviour.
* correct `inputReducer` - avoid modifying the state, which is again the principles of immutability 
- #3806 
Testing on the physical device, on both platforms.

fix: demo app tweaks

---

src/components/Checkbox/CheckboxItem.tsx
src/components/__tests__/Checkbox/CheckboxItem.test.tsx
src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.tsx.snap

Added max font scaling support for the Checkbox.Item component
Easy way to test it is by running the example on an iOS simulator and start Increasing/Decreasing the Preferred Text Size (on default I set it to 0, meaning it's disabled, set it to 1.1 or more to test it works)

feat: support for maxFontSizeMutliplier on Checkbox.Item

---

src/components/FAB/AnimatedFAB.tsx
src/components/__tests__/AnimatedFAB.test.tsx
src/components/__tests__/__snapshots__/AnimatedFAB.test.tsx.snap

Fixes: #3805 
Fixes `elevation` value in shadow views for `Animated.FAB`, which should be `3` for MD3 and `6` for MD2.
- #3805 

fix: correct animated fab elevation value

---

src/components/TextInput/TextInput.tsx

Correct the type of `contentStyle` prop passed to the `styles` of the `TextInput` from `react-native `which means, the type should be the same as in the source – `StyleProp<TextStyle>`
- #3814 
N/A

fix: correct content style type

---

docs/docs/guides/9-react-navigation.md

Path to images didn't link to anything, now it should link correctly, at least according to the docs at https://callstack.github.io/react-native-paper/docs/guides/react-navigation/
Fixed images linking to incorrect path
Tested directly on https://callstack.github.io, changing the links from `../../` to `/react-native-paper/` makes them show up

docs: Fixed images linking to incorrect path

---

src/components/FAB/FAB.tsx

(Note: This is a copy of now-closed #3873 , with required commit message formatting.)
Trying to make the FAB description a little more comprehensive and precise.
I think noting what distinguishes an FAB from a normal button is helpful to someone not familiar with Material-UI.
I also changed "application" to "screen," as an FAB represents the most important action on a screen - not necessarily the most important action in the entire application.
Load the docs for FAB, verify that they make sense.

docs: Update FAB.tsx

---

example/src/Examples/ButtonExample.tsx
src/components/Surface.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Card/__snapshots__/Card.test.tsx.snap
src/components/__tests__/__snapshots__/AnimatedFAB.test.tsx.snap
src/components/__tests__/__snapshots__/Banner.test.tsx.snap
src/components/__tests__/__snapshots__/BottomNavigation.test.tsx.snap
src/components/__tests__/__snapshots__/Button.test.tsx.snap
src/components/__tests__/__snapshots__/Chip.test.tsx.snap
src/components/__tests__/__snapshots__/DataTable.test.tsx.snap
src/components/__tests__/__snapshots__/FAB.test.tsx.snap
src/components/__tests__/__snapshots__/IconButton.test.tsx.snap
src/components/__tests__/__snapshots__/ListItem.test.tsx.snap
src/components/__tests__/__snapshots__/Menu.test.tsx.snap
src/components/__tests__/__snapshots__/Searchbar.test.tsx.snap
src/components/__tests__/__snapshots__/Snackbar.test.tsx.snap
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap
src/components/__tests__/__snapshots__/ToggleButton.test.tsx.snap
src/utils/splitStyles.ts

Fixes #3882 
Added examples in example app. They should work fine.

fix: iOS Surface flex styles moved to outer layer

---

src/components/CrossFadeIcon.tsx
src/components/TouchableRipple/TouchableRipple.native.tsx
src/components/__tests__/Appbar/Appbar.test.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Checkbox/__snapshots__/Checkbox.test.tsx.snap
src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.tsx.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButton.test.tsx.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButtonItem.test.tsx.snap
src/components/__tests__/TouchableRipple.test.tsx
src/components/__tests__/__snapshots__/AnimatedFAB.test.tsx.snap
src/components/__tests__/__snapshots__/Banner.test.tsx.snap
src/components/__tests__/__snapshots__/Button.test.tsx.snap
src/components/__tests__/__snapshots__/Chip.test.tsx.snap
src/components/__tests__/__snapshots__/DataTable.test.tsx.snap
src/components/__tests__/__snapshots__/DrawerItem.test.tsx.snap
src/components/__tests__/__snapshots__/FAB.test.tsx.snap
src/components/__tests__/__snapshots__/IconButton.test.tsx.snap
src/components/__tests__/__snapshots__/ListAccordion.test.tsx.snap
src/components/__tests__/__snapshots__/ListItem.test.tsx.snap
src/components/__tests__/__snapshots__/ListSection.test.tsx.snap
src/components/__tests__/__snapshots__/Menu.test.tsx.snap
src/components/__tests__/__snapshots__/MenuItem.test.tsx.snap
src/components/__tests__/__snapshots__/Searchbar.test.tsx.snap
src/components/__tests__/__snapshots__/SegmentedButton.test.tsx.snap
src/components/__tests__/__snapshots__/Snackbar.test.tsx.snap
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap
src/components/__tests__/__snapshots__/ToggleButton.test.tsx.snap

Correct the `TouchableRipple` underlay color support, when the ripple is not supported, so the additional layer is displayed, to have a similar effect to `TouchableHighlight`.
- #3871

fix: touchable ripple overlay

---

example/src/Examples/FABExample.tsx
src/components/FAB/FABGroup.tsx
src/components/__tests__/FABGroup.test.tsx

Added `onLongPress` support. Allows to revert the logic of displaying actions stack from `onPress` to `onLongPress`.
https://github.com/callstack/react-native-paper/issues/3180

feat: add long press support for fab group

---

src/components/List/ListItem.tsx
src/components/__tests__/__snapshots__/ListAccordion.test.tsx.snap
src/components/__tests__/__snapshots__/ListItem.test.tsx.snap
src/components/__tests__/__snapshots__/ListSection.test.tsx.snap

Fixes: #3841 
When `List.Item`s are contained within the `View` with `alignItems` then the item's row is not filling whole space – adding `width: '100%'` to the row wrapper solves the issue.
Tested manually on the apps.

fix: list item row width

---

example/src/Examples/DialogExample.tsx
example/src/Examples/Dialogs/DialogWithDismissableBackButton.tsx
example/src/Examples/Dialogs/index.tsx
src/components/Dialog/Dialog.tsx
src/components/Modal.tsx
src/components/__tests__/Dialog.test.tsx

Solves: #3810 
Introducing new prop:
```
/**
* Determines whether clicking Android hardware back button dismiss dialog.
*/
dismissableBackButton?: boolean;
```

feat: add dismissableBackButton prop to Dialog

---

docs/.eslintrc
docs/component-docs-plugin/generatePageMDX.js
docs/docusaurus.config.js
docs/src/components/ThemeColorsTable.tsx
docs/src/data/themeColors.js
docs/src/utils/__tests__/themeColors.test.tsx
docs/src/utils/themeColors.tsx

We're adding a "Theme colors" section to each component's doc to simplify the process of identifying theme color names and their corresponding roles without diving into the source code
* Colors are manually collected within the file `docs/src/data/themeColors` for each component
* Colors are defined for possible component's:
* states such as `active` or `selected`
* modes such as `flat` or `outlined`

docs: add section for component theme colors

---

docs/docs/guides/10-migration-guide-to-5.0.md
src/components/Appbar/AppbarHeader.tsx

Default height for Appbar.Header component was not matching the actual height (56 vs. 64).

docs: fix Appbar.Header default height

---

src/components/List/ListAccordion.tsx
src/components/__tests__/ListAccordion.test.tsx

Fixes: #3902 
Corrects the condition to not throw an error when `id={0}` since it's typed to accept the string or number.
- #3902 
Covered with unit tests.

fix: correct condition to accept id equal zero

---

src/components/Checkbox/utils.ts
src/components/__tests__/Checkbox/utils.test.tsx

This fixes an issue where on MD2 themes, the Android Checkbox component did not use the correct color when disabled.
The issue can be reproduced in this expo snack: https://snack.expo.dev/@jvsalas/restless-bagel

fix: MD2 Checkbox.Android disabled color

---

src/components/SegmentedButtons/SegmentedButtonItem.tsx
src/components/SegmentedButtons/SegmentedButtons.tsx
src/components/__tests__/SegmentedButton.test.tsx
src/components/__tests__/__snapshots__/SegmentedButton.test.tsx.snap

Currently there is no way to change the style of the label of a `SegmentedButton`. This PR introduces the ability to give each element of the `buttons`-list an individual style.
```tsx
{
value: 'test',
label: 'Test',
style: {
// Some wrapper style
},
labelStyle: {
fontSize: 5,
},
}
```
Like in the example above, just apply some label style to a specific `SegementedButton` item.

feat: add label style to segmented buttons

---

src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx
src/components/__tests__/TextInput.test.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

This PR adds support for the recently introduced cursorColor feature https://reactnative.dev/docs/0.70/textinput#cursorcolor-android

feat: add cursorColor to TextInput RenderProps types

---

src/components/Surface.tsx
src/components/__tests__/ListItem.test.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/3898
Sets the default value for `pointerEvents` in web `Surface` component, to avoid the case where it's overwritten by `none !important` when it's not specified, which in results makes nested touchable within `TouchableRipple` not pressable.
Covered

fix: set default pointer events on web Surface

---

src/components/TextInput/Adornment/TextInputIcon.tsx
src/components/TextInput/Adornment/utils.ts

Fixes: https://github.com/callstack/react-native-paper/issues/3901
Corrects using the custom color in to `TextInput.Icon`.
- #3901 
Tested manually in the app on the second example.

fix: input icon custom color

---

src/components/Tooltip/Tooltip.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/3917
Correct setting the `cursor` type to be set only on the `web` platform.
- #3917 
N/A

fix: correct setting cursor type

---

example/src/Examples/ButtonExample.tsx
example/src/Examples/ChipExample.tsx
src/components/Typography/Text.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Checkbox/__snapshots__/CheckboxItem.test.tsx.snap
src/components/__tests__/RadioButton/__snapshots__/RadioButtonItem.test.tsx.snap
src/components/__tests__/Typography/Text.test.tsx
src/components/__tests__/Typography/__snapshots__/Text.test.tsx.snap
src/components/__tests__/__snapshots__/Banner.test.tsx.snap
src/components/__tests__/__snapshots__/BottomNavigation.test.tsx.snap
src/components/__tests__/__snapshots__/Button.test.tsx.snap
src/components/__tests__/__snapshots__/Chip.test.tsx.snap
src/components/__tests__/__snapshots__/DataTable.test.tsx.snap
src/components/__tests__/__snapshots__/DrawerItem.test.tsx.snap
src/components/__tests__/__snapshots__/FAB.test.tsx.snap
src/components/__tests__/__snapshots__/ListItem.test.tsx.snap
src/components/__tests__/__snapshots__/ListSection.test.tsx.snap
src/components/__tests__/__snapshots__/Menu.test.tsx.snap
src/components/__tests__/__snapshots__/MenuItem.test.tsx.snap
src/components/__tests__/__snapshots__/SegmentedButton.test.tsx.snap
src/components/__tests__/__snapshots__/Snackbar.test.tsx.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3945
- #3945

refactor: typography text styles adjustments

---

react-navigation/package.json

here is the link to the issue https://github.com/callstack/react-native-paper/issues/3959

fix: missing react-navigation types

---

src/components/__tests__/SegmentedButton.test.tsx

Attempt to fix flaky test in SegmentedButton suite
Let's see if tests pass on CI

fix: flaky test for Segmented button

---

src/components/Chip/Chip.tsx

Update description
Small expansion of the Chip documentation.
The current Chip documentation doesn't give much info as to how the Chip element is intended to be used in Material UI. While the user can certainly look it up, most Material UI libraries give at least a brief summary of [the usage guidelines](https://m2.material.io/components/chips) in their own documentation, and I think it's helpful. 
So this PR adds some brief guidance as to how the Chip component is used in the Material UI system. (I thought a link to the [official guidelines](https://m2.material.io/components/chips) might also be nice, but wasn't sure if that might be against policy, since it's not already being done...? If not, and you think it's a good idea, I can include one.)
Check the description for the Chip …

docs: Update Chip.tsx description

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/__tests__/TextInput.test.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

In `outlined` mode, the background color of the label is derived from `colors?.background` in theme or the `backgroundColor` style. When `backgroundColor` style is passed as `transparent` that would affect the border cover as well, resulting in border & label overlapping in active state.
This PR switches background of the cover from `transparent` back to theme's background as a last resort.
Closes: https://github.com/callstack/react-native-paper/issues/3759
Tested on the example app + simple unit test added.

fix: use theme background for transparent text inputs

---

example/src/Examples/ProgressBarExample.tsx
src/components/ProgressBar.tsx
src/components/__tests__/ProgressBar.test.tsx
src/components/__tests__/__snapshots__/ProgressBar.test.tsx.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3984
Correct view wrapper styles for the web to properly display `ProgressBar` with the percentage height.
Added new example and unit test case.

fix: adjust progress bar wrapper height on web

---

example/src/Examples/CardExample.tsx
src/components/Card/Card.tsx
src/components/Card/CardCover.tsx
src/components/Card/utils.tsx
src/components/__tests__/Card/Card.test.tsx
src/components/__tests__/Card/__snapshots__/Card.test.tsx.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3924
Allow customizing `borderRadius` value in `Card.Cover`.
Adding new example and unit test case.

fix: correct overriding border radius

---

src/components/Chip/Chip.tsx
src/components/__tests__/__snapshots__/Chip.test.tsx.snap
src/components/__tests__/__snapshots__/ListItem.test.tsx.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3916
Chip component was having `"flexGrow": 1,` style because of which it was taking the entire parent size when a parent has aligned item style. 
I have removed `flexGrow`. 
I simulated and tested the example given in the [issue](https://github.com/callstack/react-native-paper/issues/3916)

fix: chip style 

---

src/components/BottomNavigation/BottomNavigation.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/3467
Adjust the value for offset, depending on the scene activity. 
Tested manually on the example app, based on the expo SDK 49 attached in the issue.
Tested also in the Paper example app.

fix: adjust offset target value for translation on axis y

---

src/components/FAB/AnimatedFAB.tsx

On Android, the text on AnimatedFAB is calculated using a 2nd component, but this component doesn't take the text style into account. This leads to incorrect text measurement.
This issue is easy to see on Android if you're using the MD2 theme. Depending on the length of your label, the spacing between the icon and the text will look different because the width of the label is wrong.

fix: added style to component used for text measurement on Android

---

src/components/FAB/FABGroup.tsx
src/components/__tests__/FABGroup.test.tsx

Fixes: https://github.com/callstack/react-native-paper/issues/3999
Add the missing `rippleColor` to the `FAB.Group` as well as to its item.

fix: add missing `rippleColor` in `FAB`

---

src/components/Chip/Chip.tsx

Added optional prop for enabling/disabling default checkmark icon when selecting a chip.
Testable using a Chip component with a selected item.  The check mark next to the selected chip should be hidden if the prop option "showSelectedIcon" is set to false, and shown if the option is set to true. It is set to true by default.

feat: option for hiding check icon on selected chip

---

src/components/Appbar/AppbarAction.tsx
src/components/DataTable/DataTablePagination.tsx
src/components/Searchbar.tsx
src/components/Snackbar.tsx
src/components/TextInput/Adornment/TextInputIcon.tsx
src/components/ToggleButton/ToggleButton.tsx
src/components/__tests__/Appbar/Appbar.test.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Searchbar.test.tsx
src/components/__tests__/Snackbar.test.tsx
src/components/__tests__/ToggleButton.test.tsx
src/components/__tests__/__snapshots__/Searchbar.test.tsx.snap
src/components/__tests__/__snapshots__/SegmentedButton.test.tsx.snap

Follow up to: https://github.com/callstack/react-native-paper/pull/4001
Fixes: https://github.com/callstack/react-native-paper/issues/3987
Add the missing `rippleColor` to components' nested pressable elements.

fix: add missing `rippleColor` in components' nested pressables 

---

docs/component-docs-plugin/generatePageMDX.js
docs/src/components/PropTable.tsx
docs/src/css/custom.css
src/components/Card/CardTitle.tsx
src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx

* creating TOC with props on the right side
* updating annotation badge to be displayed next to the header prop, and just the dot badge within TOC
Manual testing and checking

docs: create correct prop header to be displayed in TOC

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/Addons/Outline.tsx
src/components/TextInput/Addons/Underline.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/helpers.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

Fixes: https://github.com/callstack/react-native-paper/issues/4011
* adjusting default selection color on Android, which was opaque
* extracting `Underline` and `Outline` to separate files in `Addons` directory
* adjust example for `TextInput`
Updated snapshots

fix: selection and cursor colors

---

src/components/RadioButton/RadioButtonItem.tsx

This PR contains two fixes for RadioButtonItem when passing custom colors through `theme` property:
```
theme={{
colors: {
onSurface: ....,
onSurfaceDisabled: ...,
},
}}
```
1. Fix for type error:
```
error TS2740: Type '{ onSurface: string; onSurfaceDisabled: string; }' is missing the following properties from type 'MD3Colors': primary, primaryContainer, secondary, secondaryContainer, and 27 more.
```
Solution: Change `theme` type to `ThemeProp`.
2. Radio button icon does not apply disabled color from custom `onSurfaceDisabled` theme color.
Solution: pass `theme` down to the components handling icon colors.

fix: custom theme property for RadioButtonItem component

---

src/components/Card/Card.tsx

Fix `accessible` prop not being passed to `TouchableWithoutFeedback`.
In the update to 5.6.0, the Card component was refactored, and in the refactor, the `accessible` property, passed in as a prop, was assigned to the component's inner `View`, rather than the `TouchableWithoutFeedback`, as it had been previously - and as it needs to be to have effect. 
This meant that passing `accessible={false}` had no effect, and thus there was no way to make content within a card's content area accessible to VoiceOver on iOS (which, by default, aggregates the accessibility tree if it encounters an element with an `onPress` handler).
I removed the ineffectual `accessible` prop on the inner content, and added it back to `TouchableWithoutFeedback`. This fixes the issue in my tests.
I have tested locally …

fix: apply accessible prop to touchable in Card.tsx

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx

The `TextInput` label disappears when the input is unfocused on React Native's New Architecture (on both Android and iOS). After some digging, I noticed the root cause is switching between an `Animated.Value` and some `number`s depending on some booleans:
```ts
const placeholderOpacity = hasActiveOutline
? parentState.labeled // <-- `Animated.Value`
: parentState.labelLayout.measured
? 1
: 0;
```
If we switch between `Animated.Value` instances, the problem disappears:
```ts
const { current: placeholderOpacityAnims } = React.useRef([
new Animated.Value(0),
new Animated.Value(1),
]);
const placeholderOpacity = hasActiveOutline
? parentState.labeled
: placeholderOpacityAnims[parentState.labelLayout.measured ? 1 : 0];
```
#3776 has more details about the issue and contains an example repo to …

fix: unfocused TextInput label disappears on new architecture (#3776)

---

src/components/Menu/Menu.tsx
src/components/Modal.tsx
src/components/__tests__/__snapshots__/Menu.test.tsx.snap
src/utils/BackHandler/BackHandler.native.tsx
src/utils/BackHandler/BackHandler.tsx

In `react-native-web` version `0.19.x` the `BackHandler` was removed. To avoid errors on the `web` when `BackHandler` is imported and used, we are introducing the internal `BackHandler`, which for `web` returns empty functions. 
- #4079

fix: create internal back handler to avoid errors on web

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/Addons/Outline.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

Fixes: https://github.com/callstack/react-native-paper/issues/3669
Sets the `paddingTop` value according to the `label` visibility.
Updated snapshot.

fix: adjust top padding for outlined input without label

---

docs/docs/guides/02-theming.mdx

The example of providing a custom color is incorrect. `DefaultTheme.colors` should be spread inside the `colors` object, not in the root theme object.

docs: correctly spread default theme colors

---

example/src/Examples/TextInputExample.tsx
example/utils/index.ts
src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx

Fixed issue #4114.
Removed duplication of label in TextInput component when using label as a component ( and not string )
Added example, so that it can be checked and used in future

fix(text-input): remove text duplication of label as component

---

src/styles/__tests__/fonts.test.js
src/styles/fonts.tsx

Fixes #4094 
Every call to `configureFonts` should always return the same result for a given configuration.
Previous calls to `configureFonts` mutated the base typescale object, resulting in a corrupted fonts object.
Each call to `configureFonts` should be the result of a fixed default config plus a custom config passed as argument.
If you call `configureFonts` multiple times with different configs, you should not find custom config from previous calls in your resulting object.

fix: configureFonts should be deterministic

---

docs/docs/guides/09-bottom-navigation.md
src/components/BottomNavigation/BottomNavigation.tsx
src/react-navigation/types.tsx

Adds annotation about `tabBarColor` working only with theme version 2.
- #4129

docs: add annotation for bottom navigation tab bar color prop

---

src/components/DataTable/DataTableCell.tsx
src/components/__tests__/DataTable.test.tsx
src/components/__tests__/__snapshots__/DataTable.test.tsx.snap

Avoid wrapping React Element passed into the `DataTable.Cell` as a children into `Text` container.
- #4119  
* added unit tests

docs: render cell react element without text container

---

src/components/Button/Button.tsx
src/utils/forwardRef.tsx

Closes #3988 and #3992
#3988
CI passes

chore: forward ref to `Button`

---

example/src/Examples/TooltipExample.tsx

In this PR, missing tooltips for the 'bold' icon have been documented in the TooltipExample.tsx file. This ensures that all icons are adequately explained, contributing to a more comprehensive and user-friendly documentation.
Related issue
Tooltip is missing for bold icon
https://github.com/qburst/react-native-paper-qb-1/assets/134603758/8bd6b3d7-dd77-470e-8ea6-2cbeb7ba35e5

docs: Added missing tooltip for 'bold' icon

---

src/components/Checkbox/CheckboxItem.tsx
src/components/RadioButton/RadioButtonItem.tsx

Add missing `rippleColor` in control inputs such as `CheckboxItem` and `RadioButtonItem`
- #4165 
N/A

fix: add rippleColor prop

---

src/components/Menu/Menu.tsx

Set `default` cursor for the `Menu` pressable overlay.
- #4167 
N/A

fix: set default cursor for menu pressable overlay

---

src/components/Typography/Text.tsx
src/components/__tests__/Typography/Text.test.tsx

When a component is used as a child to Text i.e. `<Text><MyComponent /></Text>` the variant specified in the text is ignored.
i.e.
```tsx
function Custom() {
return <>{'<Custom /> nested in headlineMedium'}</>;
}
function Example() {
return (
<Text>
<Custom />
</Text>
);
}
```
This is due to [logic inside of the Text component trying to deal with nested Text components](https://github.com/callstack/react-native-paper/blob/main/src/components/Typography/Text.tsx#L98-L130). This logic however applies to all components and breaks rendering components within Text.
#4172 
1. `Text.test.tsx` contains tests for regressions - nested text with variant should override parent's variant
2. Added test to `Text.test.tsx` - nested non-text component should not override parent's variant

fix(text): variant loss with child component

---

example/src/Examples/TooltipExample.tsx
src/components/Tooltip/Tooltip.tsx

Improper handling of  timeout IDs in `onHoverIn` and `onHoverOut` in `Tooltip` component, causing invalid behaviour and sometimes getting stuck with open tooltips (described in https://github.com/callstack/react-native-paper/issues/4139#issuecomment-1780617238)
See #4139

fix: tooltip behaviour on web

---

example/src/Examples/TextInputExample.tsx
src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/constants.tsx
src/components/TextInput/helpers.tsx
src/components/TextInput/types.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

Set input's label max width to not overflow the input boundaries.
- #4164 
- #4186 
- #4168
ios | android
--- | ---

fix: correct input label max width

---

example/src/Examples/ChipExample.tsx
src/components/Appbar/AppbarContent.tsx
src/components/BottomNavigation/BottomNavigation.tsx
src/components/BottomNavigation/BottomNavigationBar.tsx
src/components/Card/Card.tsx
src/components/Chip/Chip.tsx
src/components/DataTable/DataTableTitle.tsx
src/components/Drawer/DrawerCollapsedItem.tsx
src/components/Drawer/DrawerItem.tsx
src/components/FAB/FABGroup.tsx
src/components/Modal.tsx
src/components/__tests__/Card/Card.test.tsx
src/components/__tests__/__snapshots__/BottomNavigation.test.tsx.snap
src/components/__tests__/__snapshots__/Chip.test.tsx.snap
src/components/__tests__/__snapshots__/DataTable.test.tsx.snap

* Replace the internally used `TouchableWithoutFeedback` in favor of `Pressable` component.
* correct disabled prop in `Chip`
* added `disabled` prop to `DrawerItem` and `DrawerCollapsedItem`
* extended `Chip` example

refactor: replace `TouchableWithoutFeedback` with `Pressable`

---

docs/src/css/custom.css
src/components/BottomNavigation/BottomNavigation.tsx
src/components/BottomNavigation/BottomNavigationBar.tsx
src/components/FAB/FAB.tsx

Correction jsdoc `deprecated` annotation, for documentation purposes, which makes `navigationState` as deprecated, which actually is required.
- #4213 
`navigationState` is still required and IDE doesn't mark it as `deprecated`. Documentation work as expected.

fix: bottom navigation navigation state type correction

---

src/components/Button/Button.tsx
src/components/Chip/Chip.tsx

Adjust the `useNativeDriver` value in shadow animation to be based on the `react-native` version.
- #4224 
Tested on react-native version 0.71, 0.72 and 0.73

fix: adjust native driver value based on the rn version

---

src/components/Card/Card.tsx

Using v4 Card with a OnPress in light mode crashes when using react-native version 0.73.
#4224
Tested on react-native version 0.64 and used the pressable theme change button in example app, also tested manual node_modules Card.tsx edit in react-native 0.73.

fix: v4 card onPress crash when using RN 0.73

---

src/components/Button/Button.tsx
src/components/Chip/Chip.tsx

in #4246 a check based on react native version was introduced, however the `Platform.constants` property is `undefined` when targetting web using the `react-native-web` approach [listed in the docs](https://callstack.github.io/react-native-paper/docs/guides/react-native-web), as the platform object is simply:
```
{"OS":"web","isTesting":false}
```
adjust it to check if the `OS` is `web` and use the native driver as before if so.
whilst I'm not totally sure whether using the "native driver" is the best option on web, until #4246 this was the case, so seemed the best option to revert to.
In the meantime, rather than monkey patching `react-native-paper` I'm working around by monkey patching the constants like so:
```
// TODO: workaround for react-native-paper issue
// …
```

fix: platform constants is undefined on web

---

src/components/Dialog/Dialog.tsx

Update marginHorizontal when iphone's orientation change to landscape.

feat: dialog support safe area context

---

src/components/TextInput/types.tsx

Typescript definition are not up to date with the actual usages. TextInputOutlined uses this to measure the layout, but we have it optional since TextInputFlat doesn't pass it along. 
https://github.com/callstack/react-native-paper/blob/c190a95e6b2b3842d372ba8f75477752d1042034/src/components/TextInput/TextInputOutlined.tsx#L377
https://github.com/callstack/react-native-paper/blob/c190a95e6b2b3842d372ba8f75477752d1042034/src/components/TextInput/TextInputFlat.tsx#L383
Run typescript type check to verify it.

fix: include onLayout in TextInput render props

---

src/components/List/ListItem.tsx
src/components/__tests__/ListItem.test.tsx
src/components/__tests__/ListSection.test.tsx
src/components/__tests__/__snapshots__/ListAccordion.test.tsx.snap
src/components/__tests__/__snapshots__/ListItem.test.tsx.snap
src/components/__tests__/__snapshots__/ListSection.test.tsx.snap

Possibility to override styles of the item container which wraps title and description.
- #4109 
- #4180 
updated snapshot.

feat: add contentStyle to the list item title and description container

---

src/components/Menu/Menu.tsx

Adds `elevation` property for Menu component so we can customize Surface shadow in MD3.
This PR makes it possible to redefine Surface elevation in the Menu component, so shadow and default background color will be picked based on this value.
Make sure when the property is omitted the component looks the same as before the change. Provide Menu component with a custom elevation value.

feat: add `elevation` property for Menu component

---

src/components/Checkbox/CheckboxItem.tsx
src/components/RadioButton/RadioButtonItem.tsx
src/components/__tests__/Checkbox/CheckboxItem.test.tsx
src/components/__tests__/RadioButton/RadioButtonItem.test.tsx

RadioButton.Item currently does not pass the "onLongPress" prop to the TouchableRipple component. This would be useful to implement to make RadioButton.Item elements be able to handle a secondary action.
#4214 
Create a RadioButton.Item and pass it an onLongPress prop with a function that logs something into the console.

feat: added onLongPress to `RadioButton.Item` and `Checkbox.Item`

---

src/components/Searchbar.tsx

When reflecting on the architecture and simplicity of implementing components in React, I sought to improve the code of the provided example, incorporating practices that make it easier to maintain and promote compatibility with both JavaScript and TypeScript.

feat(search-bar): minify the SearchBar component usage example

---

src/components/TextInput/Adornment/TextInputAffix.tsx
src/components/__tests__/TextInput.test.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

Add `Pressable` to [`TextInput.Affix`](https://callstack.github.io/react-native-paper/docs/components/TextInput/TextInputAffix) text input adornment and `onPress` prop.
Related issue #3968 
`yarn test`

feat(text-input): add onPress to affix adornment

---

src/components/Chip/Chip.tsx
src/components/FAB/utils.ts
src/components/__tests__/Chip.test.tsx
src/components/__tests__/FAB.test.tsx

Make the border radius in `Chip` and `FAB` based on the `roundness` value from the `theme`.
#4238
Added unit tests

fix: correct border radius based on roundness

---

src/components/Button/Button.tsx
src/components/Checkbox/CheckboxAndroid.tsx
src/components/Checkbox/CheckboxIOS.tsx
src/components/Checkbox/CheckboxItem.tsx
src/components/Chip/Chip.tsx
src/components/Drawer/DrawerItem.tsx
src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx
src/components/List/ListAccordion.tsx
src/components/Menu/MenuItem.tsx
src/components/RadioButton/RadioButtonAndroid.tsx
src/components/RadioButton/RadioButtonIOS.tsx
src/components/RadioButton/RadioButtonItem.tsx
src/components/SegmentedButtons/SegmentedButtonItem.tsx

Introduce `background` prop into pressable components containing nested `TouchableRipple` to allow customization of the ripple configuration properties.
- #4035

feat: pass background prop to nested touchables

---

src/components/TextInput/Adornment/TextInputAffix.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

Pass absolute styles to the pressable affix container as it is in the `affix` itself
- #4269

fix: correct affix pressable container styles

---

example/src/Examples/TooltipExample.tsx
src/components/Tooltip/Tooltip.tsx

Adding a fix preventing triggering children's `onPress` callback wrapped within a `Tooltip` component.
- #4282 
Tested on app, updated example.

fix: prevent pressing disabled children within tooltip

---

src/components/Button/Button.tsx

Fixes `elevation` value - reset it to 0 - when `Button` is disabled in MD2.
- #4151 
Tested according to the latest expo snack attached in the issue.

fix: correct elevation in disabled button for MD2

---

src/components/TextInput/Adornment/TextInputIcon.tsx

This PR prevents the error log warning the "defaultProps" will be removed (visible in RN0.74.0)
Addresses #4382
Ensure that use of the `TextInputIcon` does not produce the error (included in linked issue) when run using RN0.74.0

fix: remove deprecated use of defaultProps

---

src/components/Snackbar.tsx

This bug is only available on android with new architecture enabled and is well described (with and example) in the related issue #4445 
From what I've been able to find, the problem occurs when the animation is started before the component is rendered.
In our scenario, the component returns null as long as the `hidden` state is set to true. In the `handleOnVisible` function we have the main steps `setHidden(false)` and Animation start. To fix the bug, I moved the start of the animation to a useEffect that depends on the `hidden` value, so that the animation will start after the state is changed (and component re-rendered).
btw, since this bug only occurs with the new architecture, it is either also a react-native bug or an expected change. I have not found an answer yet. 
#4445 
Run …

fix(snackbar): fix show animation on new architecture

---

src/components/Menu/Menu.tsx
src/components/__tests__/Menu.test.tsx

I prefer the "flat" design approach on my components, and would like to be able to use the `Menu` component in flat mode.
You cannot currently change the `mode` on the `Surface` that is used in the `Menu` component.
Pull up the menu example and pass `mode="flat"` to one of the menus to test.

fix: add support for changing the surface mode in the menu

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

The label in the TextInput component (both flat and outlined) is truncated when it is longer than the available width. This is expected behaviour, but the issue occurs when the label is moved over an input (focus on input or input with a value). The entire label is scaled, which causes the label to continue to be truncated even though we have space to show the rest of the content. 
Increase maximum text width to the maximum possible space.
#4350 
Use TextInput with very long label. You can use example app

fix(text-input): very long input label truncated when scaled

---

src/components/TextInput/Adornment/TextInputAffix.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

The position of the right TextInput.Affix is not calculated correctly when the onPress method is provided. 
#4407 
Run Example and add a right affix to TextInput with the onPress property. Affix should render the same as without onPress. You can also try the example from the related issue.
**The first recording shows how the component behaves before the fix (without and with the onPress property). The second is the result after the fix.**
https://github.com/callstack/react-native-paper/assets/165782545/91013325-ef40-458f-817e-7b6207961945
https://github.com/callstack/react-native-paper/assets/165782545/1b7e2a75-49bd-471a-8542-dc073c3f57da

fix(text-input-affix): fix right TextInput.Affix alignment with onPress

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/helpers.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

**Platform: Android only**
This pull request fixes two bugs that are related to each other.
1. TextInput `mode="outlined"` with `height` style property blocks parent scroll. 
https://github.com/callstack/react-native-paper/assets/165782545/e7b8e7b8-157e-41d0-bbf0-8673a5d01466
2. `mode="outlined"` Left/right suffix is not correctly aligned to input when height style is provided
3. `mode="flat"`(default) blocks scrolling of the parent with a large font. The bug can be reproduced in the example app “Flat input large font”.
https://github.com/callstack/react-native-paper/assets/165782545/20bf336d-9ed2-4cad-853e-82e8e0159641
#1556, #4390,  
1. To test issue 1 and 2 run example app and set `height` style of the Text input prop
2. To test issue 3 run example app, and try to scroll starting from …

fix(text-input): parent scroll with text input height

---

src/components/Drawer/DrawerItem.tsx
src/components/__tests__/__snapshots__/DrawerItem.test.tsx.snap

Platform: WEB
This pull request fixes issue #4435. `Drawer.Item` component does not have hover effect on WEB platform. 
#4435
The author of the issue report has prepared an example to reproduce the bug. It can also be reproduced on the example app. Simply run the web version, then hover over one of the items in the "Example items" section.
| **Before** | **After** |
|------|------|
|   ![image](https://github.com/callstack/react-native-paper/assets/165782545/9a0f8529-ed45-423a-95d2-a962e0022cc3)   |   ![image](https://github.com/callstack/react-native-paper/assets/165782545/e59de30b-ca32-4d7a-9100-6c32377dc60d)   |

fix(drawer-item): hover effect background color

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx
src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/TextInput/types.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

Label with nested text components are displayed twice.
Previously, to calculate the background of a label, the label itself was rendered and the color of its text was set to `transparent`. Everything worked for the label as a string or a single <Text> element. For nested <Text> components, setting `color: "transparent"` didn't work and the text was duplicated (nested text color was not set as transparent). This pull request changes the way to get the right shape, as we already store the height of the label. Instead of rendering the label, we simply use the height value. 
#4441 
Run example app and use label from the related issue or example below
```js
<TextInput
mode="outlined"
label={
<Text style={{ color: 'red' }}>
First <Text style={{ color: 'blue' }}>Second</Text>
</Text>
} …
```

fix(text-input-label-background): custom component background height

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

After the recent update, we've encountered an issue with the TextInput styling where the input field appears collapsed.
Before applying `flexGrow: 1`:
After applying `flexGrow: 1`:
https://github.com/callstack/react-native-paper/issues/4463
Screenshots are above.

fix: fixed issue with textinput styling after new release

---

.github/workflows/check-repro.yml
.github/workflows/publish-each-pr.yml
.github/workflows/semantic-pr.yml
.github/workflows/stale.yml
.github/workflows/updates.yml

- The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-node@v1, actions/cache@v1, actions/github-script@v3.
- For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
- Please update the following actions to use Node.js 20: actions/stale@v3.
- For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

chore: Node.js 16 actions are deprecated.

---

docs/src/data/themeColors.js

[1] Typo fix in docs. Link - https://callstack.github.io/react-native-paper/docs/components/HelperText/#:~:text=theme.colors.onSurfaceDisabled-,defualt,-theme.colors.onSurfaceVariant

Typo fix in docs

---

docs/docs/guides/01-getting-started.md

Current v5 docs are misleading for versions older than 5.8.0 because they mention PaperProvider export which doesn't exist in older v5 versions.
Avoid confusion for new users starting in 5.0.0 - 5.7.2 version range
N/A
N/A

docs: mention Provider on Getting Started for older v5 versions

---

docs/src/data/themeColors.js

fix default mode name for HelperText

docs: fix default mode name for HelperText

---

src/components/TextInput/Label/InputLabel.tsx
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap

This PR solves this [issue](https://github.com/callstack/react-native-paper/issues/4482). "When focusing into a TextInput (when mode='flat'), the label disappears. It shows up normally when multiline=false, and this is only a problem on iOS."
[issue](https://github.com/callstack/react-native-paper/issues/4482)
I've checked it on ios simulator and android emulator, since example project is on expo 48 i cannot install it on my phone.
I've also updated `TextInput.test.tsx.snap` snapshot since tests were failing.

fix: input label not visible on ios if multiline, fixes #4482

---

src/components/ActivityIndicator.tsx

Seems like a word in this sentence was accidentally dropped, "replacement". (The phrase in English is that something is a "drop-in replacement", not a "drop-in" - a "drop-in" refers, rather, to a patient who has arrived at a medical office without an appointment.)
Replacing the word just adds a bit more clarity to the instructions for the component, and reduces potential confusion.
N/A
Just look at the docs page.

docs: Replace missing word in ActivityIndicator.tsx

---

src/components/FAB/AnimatedFAB.tsx
src/components/FAB/utils.ts
src/components/Typography/AnimatedText.tsx

Currently, whole styling related logic in AnimatedFAB component relies on `onTextLayout`, which is mobile specific, so FAB's label is not styled well in web.  
https://github.com/callstack/react-native-paper/issues/4478
* Animated FAB is looking good when example app is running in web browser and there's no regression for mobile devices.

fix(animated-fab): label styling (web)

---

src/components/FAB/AnimatedFAB.tsx
src/components/Typography/AnimatedText.tsx

PR fixes Typescript issue present in AnimatedFAB and AnimatedText components, which currently is breaking ts check on the main branch.
TS compilation succeeds.

fix: animated-fab & animated-text ts issues

---

src/components/Menu/Menu.tsx

PR simplify and fix `updateVisibility` function in `Menu` component.
#4631
- Menu component should work as before
- Example mentioned in the issue #4631 is resolved
I tested changes using slightly changed example from the issue, which I'm attaching below and it's working fine
```
const ReproExample: React.FC<{ navigation: any }> = ({ navigation }) => {
const [menuVisible, setMenuVisible] = useState(false);
const [textValue, setTextValue] = useState('');
const data = ['first', 'second', 'third'];
useEffect(() => {
console.log(menuVisible);
}, [menuVisible]);
return (
<View>
<Menu
visible={menuVisible}
onDismiss={() => setMenuVisible(false)}
anchorPosition="bottom"
children={getMenuItems(data)}
anchor={
<TextInput
value={textValue}
onChangeText={(newText: string) => {
setTextValue(newText); …
```

fix(menu): fix menu visibility based on props

---

example/src/Examples/FABExample.tsx
src/components/FAB/FABGroup.tsx

**Goal**: Improve the accessibility of the `FAB.Group` component by preventing hidden items from being focused.
Previously, FAB.Group items were accessibility focusable even when the menu was collapsed:
[recording1.webm](https://github.com/user-attachments/assets/f239db6e-8d22-4de7-8d14-0c89f6cab775)
**Note**: This only fixes the issue on Android and iOS. A similar issue persists on web.
**iOS**:
1. Open the example app in the simulator.
2. Open the "Floating Action Button" example.
3. Enable VoiceOver system-wide.
4. Move VoiceOver focus to the simulator.
5. Move VoiceOver focus to the next item. Verify that the item is not a hidden member of the `FAB.Group`.
6. Repeat step 5 until focus is on the "+" FAB.
7. Activate the current item.
8. Move VoiceOver focus to the next item until the …

fix(fab.group): subitems are accessibility focusable when collapsed

---

src/components/Card/Card.tsx
src/components/List/ListItem.tsx

Fixing components names presented in the documentation:
List.Item | Card
--- | ---
Fixes: https://github.com/callstack/react-native-paper/issues/4656

docs: correct Card and List.Item displayed names

---

src/components/Card/Card.tsx

This PR fixes an error that occurs when trying to animate elevation on a Card component in "contained" mode when pressing Card in contained mode, by preventing elevation animation, in contained mode, where elevation is always 0.
Fixes: #4673
Fixes: #4617 
Tested in the rn template app, on the latest rn:

fix: prevent elevation animation for contained Card mode

---

docs/docs/guides/10-migration-guide-to-5.0.md

Provide context to the phrase "in the theme".
There is insufficient context for someone not intimately familiar with the Theme system to understand what `version` and "the theme" means.

docs: add link to Theme documentation

---

src/components/Card/CardCover.tsx

Removing padding around the image within `Card.Cover`
Fixes:  #4648 
Tested on iOS, Android and web, with all three modes `elevated`, `outlined` and `contained`.

fix: remove cover padding

---

src/components/DataTable/DataTableTitle.tsx

Currently, text inside DataTable.Title gets cut off vertically when users increase font size in accessibility settings. This happens because the maxHeight does not account for scaled font sizes.
This PR ensures that the component properly respects PixelRatio.getFontScale(), preventing text clipping when font size is increased.
Fixes: [#4490](https://github.com/callstack/react-native-paper/issues/4490)
Steps to Reproduce the Issue (Before Fix)
- Open a screen with DataTable.Title.
- Go to Device Settings > Accessibility > Font Size and increase the font size.
- Observe that the text gets cut off vertically.
Steps to Verify the Fix
- Apply this PR’s changes.
- Increase font size in accessibility settings.
- Verify that the text is now fully visible and scales correctly without clipping.

fix: ensure DataTable.Title respects font scaling to prevent clipping

---

src/core/PaperProvider.tsx

If an app has components surrounding PaperProvider that occasionally refresh, then components that use the theme provided by PaperProvider will refresh even if they don't need to. E.g. { animation: { scale: 1 } } changes every time because object equality is violated, even though the theme object contents are the same from render to render.
The theme is unlikely to change often, so memoizing it should not have much memory overhead.
n/a
An app's appearance should continue to follow theme changes, but the react-devtools profiler should not show components re-rendering because of theme (or settings) changes when there haven't been any, even if a PaperProvider parent is re-rendered.
One can also use a hook like the following to look for changes to a theme fetched with useTheme():
export const …

Avoid gratuitous re-rendering of components using settings or theme

---

example/src/Examples/ButtonExample.tsx
example/src/Examples/IconButtonExample.tsx
src/components/Button/Button.tsx
src/components/Button/utils.tsx
src/components/IconButton/IconButton.tsx
src/components/TouchableRipple/TouchableRipple.tsx
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap
src/components/__tests__/Button.test.tsx
src/components/__tests__/IconButton.test.tsx
src/components/__tests__/__snapshots__/Button.test.tsx.snap
src/components/__tests__/__snapshots__/DataTable.test.tsx.snap
src/components/__tests__/__snapshots__/IconButton.test.tsx.snap
src/components/__tests__/__snapshots__/Menu.test.tsx.snap
src/components/__tests__/__snapshots__/Searchbar.test.tsx.snap
src/components/__tests__/__snapshots__/TextInput.test.tsx.snap
src/components/__tests__/__snapshots__/ToggleButton.test.tsx.snap

Resolve issue #4266 
Using `overflow: hidden` is enough for the inner views to fit the parent view, even taking care of the parent view `borderRadius`.
| Before | After |
| ------- | ------- |
| ![Shot 2024-01-15 at 20 26 40](https://github.com/callstack/react-native-paper/assets/10360816/3191bd4e-c42d-48f9-bb67-58ada411746a) | ![Shot 2024-01-15 at 20 27 22](https://github.com/callstack/react-native-paper/assets/10360816/7d12c952-ec2a-41fa-ad55-394dbd3a4349) |
After the changes, we can even set custom border radius for each corner of `IconButton` and the `TouchableRipple` will fill the button properly
https://github.com/callstack/react-native-paper/assets/10360816/55de1430-d59f-4844-a7bf-fc43b69aa731
The `overflow: hidden` trick could not be applied to `Button` as its `Surface` can be …

fix: Button and IconButton TouchableRipple borderRadius

---

src/components/TextInput/TextInputFlat.tsx
src/components/TextInput/TextInputOutlined.tsx

[Comment #4294](https://github.com/callstack/react-native-paper/issues/4294#issue-2094449471)
Isuue [ #4294](https://github.com/callstack/react-native-paper/issues/4294#issue-2094449471)
CI passes ✅

fix: :bug: Remove outline on web from TextInputFlat component

---

src/components/Appbar/AppbarHeader.tsx

Update types to omit the `safeAreaInsets` prop from `Appbar.Header`, as it is not intended to be a user-facing prop.
Detected via: https://github.com/callstack/react-native-paper/pull/4331

fix: omit safe area insets in appbar header types

---

example/src/Examples/SegmentedButtons/SegmentedButtonCustomColorCheck.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonDefault.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonDisabled.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonMultiselect.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonMultiselectIcons.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonMultiselectRealCase.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonOnlyIcons.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonOnlyIconsWithCheck.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonRealCase.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonWithDensity.tsx
example/src/Examples/SegmentedButtons/SegmentedButtonWithSelectedCheck.tsx
src/components/SegmentedButtons/SegmentedButtons.tsx

> Add stricter typing for onValueChange in SegmentedButtons component to support union types in TypeScript projects.
Refreshing and rebasing the [PR](https://github.com/callstack/react-native-paper/pull/4532)
#4528

refactor: segmented button typing

---

src/components/TextInput/TextInput.tsx

Adding the `setSelection` method to the `TextInput` component, allowing programmatic control over text selection.
Fixes: https://github.com/callstack/react-native-paper/issues/4603

fix: add missing setSelection method on text input

---

src/components/Drawer/DrawerCollapsedItem.tsx

Changed the condition from `badge && (...)` to badge `!== false && (...)` to properly handle the case when `badge === 0`. 
This ensures that numeric badges with value 0 are displayed correctly within the Badge component rather than being improperly rendered as plain text. 
The previous implementation caused JavaScript to evaluate 0 && (...) as falsy, resulting in the `Badge` component wrapper being skipped when the badge value was zero.
Fixes: #4492

fix: zero badge rendering

---

src/components/FAB/FABGroup.tsx

Added `isClosingAnimationFinished` state to track animation completion, so then actions container can be hidden after closing animation. Also extracted event handlers into separate functions for better code organization
Fixes: #4513 
Fixes: #4467 
Tested on mobile and web platform.

fix: hide actions after closing fab group

---

src/components/BottomNavigation/BottomNavigationBar.tsx
src/components/__tests__/__snapshots__/BottomNavigation.test.tsx.snap

This PR fixes the opacity behavior of labels in the `BottomNavigationBar` component - fix properly applies active/inactive opacity values based on the component's state and version.
Fixes: #4369 
Fixes: #4348 
empty label when not focused | bold label for focused
--- | ---

fix: adjust label opacity

---

src/components/Appbar/Appbar.tsx
src/components/Appbar/AppbarAction.tsx
src/components/Appbar/utils.ts
src/components/__tests__/Appbar/__snapshots__/Appbar.test.tsx.snap

This PR fixes the behavior of the `isLeading` prop in Appbar actions by ensuring consistent handling of leading and trailing in all modes.
Fixes: #4638 
Tested on mobile and web platforms.

fix: isleading prop behaviour

---

src/components/Snackbar.tsx
src/components/__tests__/__snapshots__/Snackbar.test.tsx.snap

This PR adds a new `contentStyle` prop to `Snackbar` component allowing for more styling control.
Fixes: #4133

feat: add content style prop

---

src/components/Card/CardActions.tsx

Enable an option to override the `justifyContent` whic gives users more flexibility in styling their layouts. 
According to the MD documentation, action buttons can be placed on both sides of the container.
Fixes: #4302

fix: allow to override content style

---

src/components/Typography/v2/Caption.tsx
src/components/Typography/v2/Headline.tsx
src/components/Typography/v2/Paragraph.tsx
src/components/Typography/v2/Subheading.tsx
src/components/Typography/v2/Title.tsx

In the MD2 we had Caption, Paragraph, Subheading, Title and Headline as typography components, but in MD3 we [introduced](https://callstack.github.io/react-native-paper/docs/guides/migration-guide-to-5.0#typography) new approach based on one Text component.
In the migration guide our recommendation was to replace old components in favour of the new Text with specific variant, as presented below, so I believe we should mark them as deprecated – going to handle that.
Fixes: #4629

refactor: mark MD2 typography as deprecated

---

docs/docs/guides/02-theming.mdx
example/src/index.native.tsx
example/src/index.tsx
example/utils/themes.ts
src/core/__tests__/theming.test.tsx
src/core/theming.tsx
src/types.tsx

This PR adds support for adapting fonts when using `adaptNavigationTheme`. The changes include:
- Added type definitions for navigation theme fonts
- Enhanced `adaptNavigationTheme` to adapt font configurations
- Added unit tests to verify font adaptation behavior
- Moved theme configuration logic to a separate utility file for better organization
Fixes: #4540 
Fixes: #4573

feat: adjust adaptNavigationTheme to the latest navigation theme changes

---

src/components/FAB/FABGroup.tsx

Added an `actionWrapper` prop to the action object, enabling the ability to add styles of the action-item wrapper.
Currently, there is no way to access the wrapper component of a FABGroup action item. It prevents modifying aspects like spacing between action items. To address this, I added an `actionWrapper` prop within the action prop, allowing the ability to add styles to the wrapper styles.
https://github.com/callstack/react-native-paper/pull/1435

feat: add ability to add styles to the action-wrapper in FABGroup

---

src/components/Modal.tsx

Currently, the RNP modal is nearly totally non-accessible, because it renders outside the normal element hierarchy, and so a screen-reader user, navigating by the most common methods (next-element swipe or next-heading), will continue on the page without even being aware the modal has opened. The intended behavior for modals (as seen with the [React Native modal](https://reactnative.dev/docs/modal), or web modals), is for focus to shift to the modal as soon as the modal opens. With the RNP modal, focus remains unaffected, leaving the screen-reader user unaware a modal has even opened, and unable to reach it via the most common navigation actions (next-element or next-heading). 
This adds a note to the docs making end-users aware of this limitation. **This is vitally important, as …

docs: Update Modal.tsx description to note a11y limitations

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx

This pull request aims to resolve the TextInput flickering issue caused by the use of translateX to adjust the label position. The recent addition of transformOrigin in React Native 0.73 allows us to set the transform origin directly to the left, removing the need for translateX adjustments and preventing flickering.
#4341 
#4245 
#4299 
#4340 
1. Run the application on React Native 0.73 or later.
2. Test TextInput components with floating labels in with mode "outlined"
3. Verify that the label no longer flickers or jumps during state changes.

fix: use transformOrigin to fix TextInput label position flickering in RN 0.73

---

src/components/Button/Button.tsx

Fix `hitslop` on the Button component which was previously being passed to the wrong child component
#4677 
1. Create a button
2. Apply a large value with the `hitslop` prop
3. Observe that you can press outside of the button which triggers both the animation and `onPress` action
e.g.
```tsx
<Button
mode="contained"
onPress={() => console.log("pressed")}
hitSlop={300}
>
Press me
</Button>
```

fix(button): pass hitSlop to touchable

---

scripts/typescript-output-lint.js
src/components/Checkbox/CheckboxItem.tsx
src/components/Chip/Chip.tsx
src/components/Drawer/DrawerItem.tsx
src/components/FAB/AnimatedFAB.tsx
src/components/List/ListAccordion.tsx
src/components/Menu/MenuItem.tsx
src/components/RadioButton/RadioButtonItem.tsx
src/components/SegmentedButtons/SegmentedButtonItem.tsx

Fix the possibility to pass a `hitSlop` prop to components based on the `TouchableRipple`
Addition to https://github.com/callstack/react-native-paper/pull/4678
Fixes: #4677

fix: allow to override hitSlop

---

src/components/Surface.tsx

PR fixes the issue when flex is applied to the Surface component and flex style is re-applied only to outer component, not the nested one, so styles can be broken if e.g `flex` and `justifyContent` are applied together.
Exact repro is provided in #4632
Fixes #4632

fix: fix Surface styling when flex set

---

src/components/SegmentedButtons/utils.ts
src/components/__tests__/__snapshots__/SegmentedButton.test.tsx.snap

Fixing the `rtl` layout for `SegmentedButton`. It requires `react-native@0.77.0` since there was an issue internally in the framework -> #4716 
That PR is an addition to fix the end border.
Fixes: #4649 
ios | android
--- | ---

fix: correct border end width

---

src/components/TextInput/Label/InputLabel.tsx
src/components/TextInput/Label/LabelBackground.tsx

The label for a `Text Input`, when not in focus, overlaps the `left` component. This PR updates the threshold values required for `translationX` to be in accordance with support for React Native version `0.77` as release `5.14.1` mentions in the [changelog](https://github.com/callstack/react-native-paper/releases/tag/v5.14.1).
`InputLabel` does not translate accordingly when `left` component is present on react native `0.77`.
Create a simple `TextInput` with a text `label` and any `left` element (either `TextInput.Icon` or `TextInput.Affix`). The current version (`5.14.1` with react native `0.77`) works like this:
After updating threshold for `translateX` the result is:

fix: Text Input Label overlaps Left element on react native 0.77

---

src/components/FAB/AnimatedFAB.tsx

`onTextLayout`  sets the width of the text for the `AnimatedFAB` when the text changes.  If the `label` is an empty string the `nativeEvent.lines[0]` is undefined for iOS.  This change handles this case and defaults to `0`.
On iOS, when the `label` is changed from a non-empty string to and empty string, it throws an Uncaught error
`Cannot read property 'width' of undefined`
None
Tested on iPhone 11 by changing the `label` from a non-empty string to an empty string.  Before the fix, this would throw an Uncaught error.  After the fix, not error was thrown and the component resized as expected.

fix: fix error on width change of AnimatedFAB when label is empty string

---

src/components/Appbar/Appbar.tsx
src/components/Banner.tsx
src/components/BottomNavigation/BottomNavigationBar.tsx
src/components/Button/Button.tsx
src/components/Card/Card.tsx
src/components/Chip/Chip.tsx
src/components/FAB/AnimatedFAB.tsx
src/components/FAB/FAB.tsx
src/components/IconButton/IconButton.tsx
src/components/Menu/Menu.tsx
src/components/Modal.tsx
src/components/Searchbar.tsx
src/components/Snackbar.tsx
src/components/Surface.tsx

This PR improves the behavior of the `Surface` component regarding flexbox layout and style inheritance, especially on iOS, and introduces a new **internal** `container` prop for more explicit control. 
This prop allows internal components (like Button, Card, etc.) to explicitly specify whether the `Surface` should behave as a main layout container or as a simple wrapper.
#3652 
#4632 
Tested against two mentioned issues:

fix: add container prop and improve flex/layout handling

---

src/components/Card/Card.tsx
src/components/__tests__/Card/__snapshots__/Card.test.tsx.snap

This PR resolves an issue with the `Card` component's elevation handling. 
Previously, `elevation` was applied via _styles_, which works for the _old_ Material Design system, but in MD3, it needs to be set directly using the `elevation` prop.
Fixes: #4714 
Tested on both Expo SDK 52 and 53 - with `react-native` `0.77.2` and `0.79.2`
Run the android app, pressed the `Card` in all 3 modes - the crash doesn't occur.

fix: apply elevation as prop for md3
